### ISSUE TITLE
More highlight options

### ISSUE THREAD

**Issue by 0xdabbad00** [spf13/hugo#1021]
Syntax highlighting only allows option for the language.  However pygments provide many options (http://pygments.org/docs/formatters/).  Specifically, I would like to be able to use `linenos` and `hl_lines` in order to show line numbers, and be able to highlight specific lines.  Highlighting lines means the background color is changed for that line so you can show changed lines.

**Comment by alaska** [comment]
I have actually been working on something similar with rainbow.js that uses shortcode to accomplish all of this as well as subsequent ```{{<link>}} {{</link}}``` items to highlight lines in the most recent code block. I'll see if I can't adapt what I've got to the core and issue a pull request.

**Comment by owenwaller** [comment]
Hum...guess I need to sort out pushing what I have then. Assuming you are after a static solution, rather than an linking to an external site, or using a blob of Javascript on the client.

I have already have an extension that replaces pygments with the `highlight` tool. See http://www.andre-simon.de/doku/highlight/en/highlight.php

The extension supports the line number feature you are after. It adds a new shortcode "hilight" and you can use it like this:

{{< hilight lang="go" style="edit-gedit" lineNumbers="n" >}}
fmt.Println("This is a string!")
fmt.Print("and so is this.")
{{< /hilight >}}

Which generates this

```html
<pre style="color:#3a3935; background-color:#ffffff; font-size:=14pt; font-family:'Courier New';">
fmt
<span style="color:#3a3935">.</span><span style="color:#3a3935;font-weight:bold">Println</span>
<span style="color:#3a3935">(</span><span style="color:#ff00ff">"This is a string!"</span>
<span style="color:#3a3935">)</span>
fmt
<span style="color:#3a3935">.</span>
<span style="color:#3a3935; font-weight:bold">Print</span>
<span style="color:#3a3935">(</span>
<span style="color:#ff00ff">"and so is this."</span><span style="color:#3a3935">)</span>
</pre>
```

You can specify the source language and the theme. Obviously you need the highlight tool installed.

I developed this because I didn't have pygments installed, and had used highlight before. On significant advantage of moving away from pygments is speed. With highlight the slowdown isn't noticeable. I am currently building a code heavy site with the extension so this is important to me. 

I'll see what I can do to sort out a pull request.

Owen

**Comment by alaska** [comment]
Other options are certainly welcome, but I'd be prepared to push the framework to support selectable highlight options in that case.

That said, it's yet another external dependency and, currently, I have a built-in solution based on the language independent lexer at https://github.com/sourcegraph/syntaxhighlight.  It is basically ready for push right now, but I'm taking a week or so to work on an even BETTER one that's more extensible and supports more languages.

**Comment by bep** [comment]
What on earth are you ( @owenwaller and @alaska ) talking about?

The thread started asks about exposing the Pygmentize options `linenos` and `hl_lines`.

A very clear and good suggestion.

As this would a "per code sample setting" (I guess), it should be set as parameters in the `hithlight` shortcode.

No other frameworks needed. Just a couple of lines of code.

**Comment by alaska** [comment]
You're absolutely right. I was talking about providing an option via rainbows to render to tables. Then this guy starts talking about highlight frameworks, and I forgot what the original question was about. Mea culpa.
