### ISSUE TITLE
hugo: Configurable ignore list (filename regular expressions)

### ISSUE THREAD

**Issue by ehammond** [spf13/hugo#1189]
Per http://discuss.gohugo.io/t/hugo-server-watch-should-ignore-emacs-lock-files/1265

Please add the ability to configure a list of regular expressions that specify filename patterns that `hugo server --watch` should ignore as triggers for rebuilding the site.

For example, I would like to add `^\.#` (Emacs lock file symlink prefix) to the list to prevent hugo rebuild and browser reload every time I start editing a file.

**Comment by ehammond** [comment]
Your speed scares me. But thank you.

**Comment by bep** [comment]
Note my latest commit - I renamed it to ignoreFiles.

**Comment by jethrokuan** [comment]
I'm not sure what I'm doing wrong here, but I still face the same issue on `0.16-DEV`.

I have `ignoreFiles = ["^\\.#"]` in my `config.toml`, and not only does livereload not work, refreshing the page does not reflect the changes in the markdown, because the site was not rebuilt.

The output of hugo serve:
```
❯ hugo serve                                                                                                    09:49:23 PM 
Started building site
0 of 1 draft rendered
0 future content
8 pages created
0 non-page files copied
0 paginator pages created
0 tags created
7 categories created
in 20 ms
Watching for changes in /home/jethro/Code/blog/{content,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Change detected, rebuilding site
2016-03-24 21:51 +0800
Source changed /home/jethro/Code/blog/content/posts/.#building-aagenda.md
^C⏎      
```

**Comment by andrewalexander** [comment]
I have the exact same problem as @jethrokuan. Just did a `go get -u -v github.com/spf13/hugo`, and I see the relevant lines in `fileserver.go` have been updated. I also added this to my config.toml: `watchIgnoreFiles = ["\\.#(\\w+)\\.(\\w+)"]` thinking that I could make it happen with my own regex. And yet, I experience the same no-reload and a notification that the content is changed, but it never actually rebuilds anything since the content wasn't actually updated yet. My `hugo server --watch` output is a bit different though:

```
hugo server --watch
Started building site
0 draft content
0 future content
1 pages created
0 non-page files copied
0 paginator pages created
2 tags created
2 categories created
in 24 ms
Watching for changes in /home/andrew/Projects/fancy_new_project/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Change detected, rebuilding site
2016-05-29 15:13 -0400
```

It doesn't say _which_ file changed, only that a change was detected. Not a true deal-breaker, but when I edit in Sublime, it's really nice to have that live-reload vs. having to kill the hugo process and restart every time while I edit in emacs.

**Comment by dtaht** [comment]
I too am hitting this problem. Trying both regexps above with hugo v.16, and without, 
hugo crashes with:

dave@nemesis:~/git/sites/blog-cerowrt$ hugo server
Started building site
ERROR: 2016/08/28 18:54:34 filesystem.go:108: Cannot read symbolic link '/home/dave/git/sites/blog-cerowrt/content/post/.#fq_codel_on_ath9k.md', error was: lstat /home/dave/git/sites/blog-cerowrt/content/post/dave@nemesis.23075:1472307504: no such file or directory
panic: reflect: call of reflect.Value.Int on string Value [recovered]
	panic: reflect: call of reflect.Value.Int on string Value

goroutine 85 [running]:
panic(0xb5eb20, 0xc8206fc0e0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
text/template.errRecover(0xc8208413f0)
