### ISSUE TITLE
Scheme Relative BaseURL should remove tld

### ISSUE THREAD

**Issue by Secretmapper** [spf13/hugo#1206]
Scheme relative BaseURL can be used by setting BaseURL in the config file as:

`baseurl = //mysite.tld/relative`

While using '//mysite.tld/relative' works for production, it does not work for development as localhost is still added. Hence hugo says:

> Web Server is available at 
> http://127.0.0.1:1313//mysite.tld/relative/

and accessing that link results in a 404.

Adding https:// fixes the problem, but then it has to be edited out again for production.  Ideally hugo should remove mysite.tld as it is the domain name itself, and the web server be available at:

> Web Server is available at 
> http://127.0.0.1:1313/relative/

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by ssylvan** [comment]
I could reproduce this on v0.16, but just downloaded v0.19 and it seems fixed.
