### ISSUE TITLE
"source" configuration setting doesn't seem to work

### ISSUE THREAD

**Issue by mfcollins3** [spf13/hugo#1223]
I'm using Hugo to generate the static HTML content of a website that will be served through a Go HTTP server hosted on Heroku. I moved the Hugo website source into a "web" subdirectory of my repository and I moved my config.toml file into the root of my repository. The goal is that I want to use a multi-build pack on Heroku to run the Go build pack to build my web server/web API and the Hugo build pack to build the static website files.

In my config.toml file, I defined the 'source = "web"' line based on the instructions on the configuration page, but this does not seem to have any effect. Setting the source on the command line works, but I'd like to set it in the configuration.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
