### ISSUE TITLE
Improve error handling in where template func

### ISSUE THREAD

**Issue by ashishthedev** [spf13/hugo#1233]
### Use Case:

There are about 200 pages in the website.
But some pages like "privacy", "about" and "terms and conditions" are appearing on the home page.
You dont want these pages on home page, so you declare a page specific param on these pages:
#### front matter:

+++
...
notOnHomePage = "true"
+++
#### and in index.html

```
...
{{range first 10 (where .Paginator.Pages ".Params.notOnHomePage" "!=" "true")}}
...
```

But now not even single post is shown on the homepage.
##### And no error is shown on site compilation. It is silently eating the error.

Original Discussion:
http://discuss.gohugo.io/t/how-to-filter-pages-on-homepage-based-on-page-params/1369

**Comment by benzwu** [comment]
Isn't this related to unset Params where we should compare it with `nil`. If such `where` can throw an error, we will see a lot of errors since we can have different params for different template/section content.

**Comment by bep** [comment]
It is related to the nil discussion. If we can provide better error message, then it will be an improvement. Lot of error messages isn't an improvement, then it is better to just leave it as is.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
