### ISSUE TITLE
Do not start server on missing theme or any other reason no content can be generated

### ISSUE THREAD

**Issue by lesv** [spf13/hugo#1234]
It may be easier to not start the server if there are no generated files.  (Ie. you must have at least one file in public/ (or it's equivalent) or the `hugo server` command with quit.

**Comment by scottcwilson** [comment]
This is fixed as of commit 
https://github.com/spf13/hugo/commit/354192d2b8b18f92966f77e156a9f09d0570ec98

**Comment by bep** [comment]
@scottcwilson I kept this open ... there is the "or any other reason no content can be generated ..." The most obvious are covered no, but there are some others. Not sure which.

**Comment by scottcwilson** [comment]
Ah ok.  Keep your eye out for them - if you report them here I will do my best to fix them.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
