### ISSUE TITLE
Use a single language other than english (config.toml)

### ISSUE THREAD

**Issue by lkppo** [spf13/hugo#1262]
Hello,

I wish to create a website in French only, and my firstname has an accent: Stéphane. Tutorial "Create a Multilingual Site" is not very usefull in this case.

I made a test with Hyde and Tachyons themes and if I put the variable title = "Stéphane..." in config.toml, the output of "é" is garbage.

If I encode it manually (&eacute;), the string is escaped (&amp;eacute;).

And if I encode config.toml in UTF-8, hugo dies with a nasty error:

ERROR: 2015/07/10 Error parsing config: Near line 0 (last key parsed ''): Bare keys cannot contain '\ufeff'.

I used windows amd64 version:

Hugo Static Site Generator v0.14 BuildDate: 2015-05-26T01:29:16+02:00

Can I fix this myself without putting up a multilingual website?

Regards,

**Comment by noirotm** [comment]
The `'\ufeff'` character is a BOM ([byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)) which is sometimes added by text editors at the beginning of the file.
It is unnecessary for UTF-8 because the format is endianness-independant.

If you are using a text editor such as Notepad++, you can see that in the 'Encodding' menu, there are two entries, `Encode as UTF-8`, and `Encode as UTF-8 (without BOM)`.
Encode your file using the later, and it should work fine.

**Comment by ls6** [comment]
I have the same problem and a little more information :)

I have this error with `hugo_0.14_darwin_amd64` however *no error* with `hugo_0.12_darwin_amd64`. Both on OSX 10.10.5 Yosemite

In my case one of the authors has a non-ASCII character in his name (ł) and adding this:
`[params.authors.łukasz]`
to the config.toml file results in:
` Error parsing config: Near line 9 (last key parsed 'taxonomies'): Bare keys cannot contain 'ł'.`

**Comment by noirotm** [comment]
@ls6 According to the TOML spec, you can use quoted keys instead of bare keys, like this:

    [params.authors."łukasz"]

**Comment by ls6** [comment]
It does work, thank you!
I didn't investigate in that direction... the previous version working must have thrown me off that trail.
