### ISSUE TITLE
Add more documentation about variable scopes vs Scratch

### ISSUE THREAD

**Issue by ghostsquad** [spf13/hugo#1275]
http://discuss.gohugo.io/t/unsure-how-to-set-variable-value-after-declaring/1443

here's the code I'm trying to get to work:

```
{{ $maxCategories := 0 }}
{{ range $name, $taxonony := .Site.Taxonomies.categories }}
   {{ $pageCt := len $taxonomy.Pages }}
   {{ if gt $pageCt $maxCategories }}
      {{ $maxCategories := $pageCt }}
   {{ end }}
{{ end }}
```

Seems "scratch" is possibly the way to do this, but I wouldn't have figured that out without help.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by bep** [comment]
This issue is old and stale, and no one has shown enough interest in it to make it happen. I will close this now, and by that, I'm not saying that this "isn't worth adding to Hugo", I'm just saying that anyone that really wants this, will have to create a new tracking issue for any future Pull Request that solves this issue.
