### ISSUE TITLE
Incorrect .RSSLink on terms pages

### ISSUE THREAD

**Issue by dimo414** [spf13/hugo#1302]
On terms pages (e.g. `http://example.com/tags/`) the `.RSSLink` variable is set to an `index.xml` path in that directory that doesn't exist.  So for `/tags/` `.RSSLink` returns `http://example.com/tags/index.xml`.

Personally, I'm ok with it either being unset or having the associated RSS page generated, whichever's easier.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
