### ISSUE TITLE
config.toml isn't read by default

### ISSUE THREAD

**Issue by drewwells** [spf13/hugo#1363]
Creating a new site and starting it `hugo server -t slim --buildDrafts` gives errors unable to find config.

Error:
```
hugo server -t slim --buildDrafts
ERROR: 2015/08/18 Unable to locate Config file. Perhaps you need to create a new site. Run `hugo help new` for details
ERROR: 2015/08/18 No 'baseurl' set in configuration or as a flag. Features like page menus will not work without one.
```

Adding this to the server call fixes the issue. `--config=config.toml`

**Comment by drewwells** [comment]
Reproduced on dac9c0d

**Comment by anthonyfok** [comment]
Same problem here, though `hugo` at dac9c0d was working just fine several days ago.

It turns out that the Viper's way of searching config file handling was changed two days ago:

* spf13/viper#73: Current directory used for config if no other specified directories exist.

Thankfully, the author of the patch has included a note telling us how to get the old behaviour back: https://github.com/spf13/viper/issues/73#issuecomment-126970794

> To get the pre-fix functionality back in your application, add the following call the proper viper callee > after adding all other search paths to it:
>
>     viper.AddConfigPath(".")

This fix works for me.  Will commit a fix soon.  :-)

**Comment by drewwells** [comment]
Fixed, thanks!

**Comment by akbarsha03** [comment]
After I create the site I forgot to navigate to the newly created directory on my command prompt which caused the issue
