### ISSUE TITLE
Autogenerate man pages for Hugo

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1369]
See

https://github.com/spf13/cobra/commit/e4993076d845b7127c760e2e57a4984c166c6c05

**Comment by anthonyfok** [comment]
Hi @ bep,

Thank you for bringing Cobra's new man page generation capability to my attention.  It is especially helpful because man pages are almost a requirement for Debian packaging.

I have added a quick-and-dirty command for man page generation in PR #1602.
Please let me know if there is anything that needs to be changed before it is fit for merging.
Many thanks!

**Comment by bep** [comment]
Look fine, buuut ... looking at the command list now, we should maybe refactor all the gen* commands into subcommands. What about:

`hugo gen doc`
`hugo gen autocomplete`
`hugo gen man`

??? @spf13

**Comment by spf13** [comment]
I think that's a much better idea. We should let the kubernetes team know
or at least get them to weigh in as these are part of cobra.

**Comment by bep** [comment]
See #1603 (I fail to see how that issue affects Kubernetes).

**Comment by anthonyfok** [comment]
Thank you @ bep for merging this PR.

And I would like to chime in to say: Yes, great idea on refactoring these "gen*" commands to the umbrella of one new "gen" subcommand.  :+1:
