### ISSUE TITLE
Documentation translation to pt-BR

### ISSUE THREAD

**Issue by calheira** [spf13/hugo#1373]
Hi! 
I want to translate the documentation into Brazilian Portuguese. 
How do I do that?

**Comment by digitalcraftsman** [comment]
In the community we've already discussed ([forum thread](http://discuss.gohugo.io/t/best-practices-for-i18n/1276)) how to internationalize websites in Hugo and created a [tutorial](http://gohugo.io/tutorials/create-a-multilingual-site/) for it.

The easiest way would be to create a subfolder that just contains the translated markdown files. But you would still have elements like the menu in English because the links a defined in the config file.

 Therefore we would need to create seperate site as described in the links above. And as you can see in the [templates](https://github.com/spf13/hugo/blob/master/docs/layouts/partials/menu.html#L32,L34), some strings are even hardcoded (but could also be moved to the configs).

But in general it would be interesting to know if the docs will be multilingual in the future.

**Comment by bep** [comment]
Contributions are welcome. I see one problem with multilanguagual documentation: We make updates/corrections to the doc all the time. Having language versions known to few means they will not get updated, and it is better to have correct info in English than wrong and outdated in your own.

@spf13 is the boss, and probably has something to say on this.

**Comment by digitalcraftsman** [comment]
@calheira I appreciate your interest for translating the docs. I know that not all people are fluet in English and would prefer translated docs but, as @bep mentions, the biggest problem is to keep the docs up to date. That's why I mostly prefer English resources, even if it's not my native language.

This doesn't mean that you shouldn't try it.

**Comment by spf13** [comment]
I'll fully support any translation efforts provided that we have a structure in place to keep them up to date. I know we have many japanese users who would also benefit from native language docs.

**Comment by calheira** [comment]
Got it.
How about doing as in [translated Express.js documentation] (http://expressjs.com/es/)?
They put a warning:
"This document might be outdated relative to the documentation in English. For the latest updates, please refer the documentation in English."

**Comment by digitalcraftsman** [comment]
Having translations for the docs would be great, especially with the i18n feature. But this issue looks rather stall and should be closed if there is no interest anymore.
