### ISSUE TITLE
use uppercased categories 

### ISSUE THREAD

**Issue by whzecomjm** [spf13/hugo#1407]
I use some uppercased categories , but then hugo will generate downcased Urls, which cannot be viewed.

e.g. I use a category `math.CA`, then the url will be 

```
    http://example.com/categories/math.ca/
```

which is invalid to view.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
