### ISSUE TITLE
Sitemap creation in public folder using localhost as url when running "hugo server"

### ISSUE THREAD

**Issue by dnosker** [spf13/hugo#1455]
When running command line "hugo" all is fine and the .Permalink in the hugo default template is creating the correct urls in the sitemap using the baseurl set in the config file.

However, if running "hugo server" the sitemap is generating instead this:
<loc>http://localhost:1313/about/</loc>

The problem is that IF the last command ran is "hugo server", and then the sitemap in the public folder is transferred to a remote webhost, the sitemap will have invalid links.

Suggesting this be changed to always use the baseurl set in the config for sitemap generation even when running "hugo server" on a local machine.

**Comment by anthonyfok** [comment]
Hi @dnosker,

Thank you for your suggestion.

However, the behaviour you are seeing is **by design**.  The http://localhost:1313/ baseURL is necessary for your web browser to find the files served by `hugo server`.  If you look closely, it is not only `sitemap.xml`, but ALL generated HTML are likely to contain `href`s pointing to "http://localhost:1313/", so something is bound to be broken (missing CSS, missing images, etc.), making it unfit for upload to the production server anyway.

Also, end users often run `hugo server --watch`, which injects LiveReload.js to the web page for instant update to ease web development.  This feature is great for the local computer, but not for production.

So yes, it is imperative that a final "hugo" run be made to generate a correct website for upload to the production web server.

Alternatively, with the appropriate command-line flags, "hugo server" ***can*** be used as ***the*** web server on your production server.  See https://gohugo.io/overview/usage/#alternatively-serve-your-web-site-with-hugo:dc32fe45042973266ca60588597e0b66 for more information.

Cheers,
Anthony

**Comment by dnosker** [comment]
Thanks for the help... I was using "hugo" without the same --VARS on the end. Once I set them the same all is well with this.
