### ISSUE TITLE
commands "Hugo Server" generating content where "Hugo" is not

### ISSUE THREAD

**Issue by dnosker** [spf13/hugo#1456]
When having a sub directory in the content directory such as:
```
- content
  -- post
```
When using "hugo server" the public directory will have generated the subdirectory "post" and all files for that directory.

However, when using just plain "hugo" the above post directory and those files are NOT generated.

**Comment by anthonyfok** [comment]
Hi @dnosker,

Sorry, I cannot reproduce this.  Both `hugo` and `hugo server` work just fine here on my computer.
Could you please give more details?

Meanwhile, please make sure you are using the same flags for both `hugo` and `hugo server`, especially:

 * The `--buildDrafts` or the `-D` flag if your contents are still draft; otherwise, no draft content gets rendered.
 * The `--theme` or the `-t` flag to specify a theme, unless you wrote your own layout templates; otherwise, all rendered content files would be empty.

Please also check the permission of your `public/` directory.  For example, I have experimented with `hugo server` running on `--port 80`, which requires root access with `sudo`, and would generate all content files to be owned by root.  But then I forgot to reset the permission with `chown`, and my next `hugo` run would fail.

Thanks!

**Comment by dnosker** [comment]
Seems that most my problems were not adding the same flags when running "hugo" as when running "hugo server --theme"

Perhaps a little more clarity on the docs about this would be in order?

Thanks again!
