### ISSUE TITLE
Hugo inserts a paragraph tag inside of blockquote elements during markdown conversion

### ISSUE THREAD

**Issue by rhewitt22** [spf13/hugo#1480]
Hugo automatically inserts `<p>` tags within a `<blockquote>` element.  Paragraphs generally have default margins, which can cause vertical rhythm problems.

It's an easy fix with css, but I see the paragraph tag as unnecessary.

![screen shot 2015-10-09 at 9 03 30 am](https://cloud.githubusercontent.com/assets/3673374/10394352/af365998-6e64-11e5-9869-fbd3d5c2c8a0.png)
![screen shot 2015-10-09 at 9 03 49 am](https://cloud.githubusercontent.com/assets/3673374/10394353/b0c8da92-6e64-11e5-9382-a09ff372c57c.png)

**Comment by bep** [comment]
Assuming this is default md (Blackfriday markdown), could open a issue at

https://github.com/russross/blackfriday

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by rhewitt22** [comment]
There's a simple SCSS workaround.

```scss
figcaption {
  p {
    margin: 0;
  }
}
```
