### ISSUE TITLE
Add support for Go-native implementation of (Emacs) "Org-mode" markup

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1483]
See http://discuss.gohugo.io/t/org-mode-support/810

About Org-mode:
- Official website: http://orgmode.org/
- Wikipedia entry about Org-mode: http://en.wikipedia.org/wiki/Org-mode

There appear to be no usable Go-native implementation of Org-mode as of October 2015, but hopefully it will come in due time.

**Comment by novoid** [comment]
Hi!

Can someone explain me how you implement Org-mode support? I am not go savvy but I don't see any Org-mode syntax parser included. Do you use any external library to parse and convert Org-mode? 

Thanks!

**Comment by novoid** [comment]
I have a question for this specific commit. This commit has a built-in discussion/question functionality of GitHub and I don't want to create just another account for the external discussion portal.

The Hugo Documentation does not state how Org-mode syntax is converted. The linked source code fragment does not help either because there is no Org-mode extension mentioned.

**Comment by zet4** [comment]
Well if you read the source code in the commit you'd find [helpers/content.go](https://github.com/spf13/hugo/commit/86e8dd62f0b1c8adf14e9369b089d209317aaf2d#diff-023c37df801bf3645b989b3277cba72e) which shows that [github.com/chaseadamsio/goorgeous](https://github.com/chaseadamsio/goorgeous) is used for parsing the content.

**Comment by novoid** [comment]
There seems to be a misunderstanding what "native Emacs Org-mode" means (mentioned on https://www.reddit.com/r/emacs/comments/5wibiv/hugo_v019_with_native_emacs_orgmode_content/). I thought that you're using the original Elisp parser whereas there is a Go-parser instead. My mistake.

Thanks for clarification.
