### ISSUE TITLE
Need file/location of errors from Pygments

### ISSUE THREAD

**Issue by nathany** [spf13/hugo#1497]
I'm getting a bizarre error from Pygments when running Hugo on my site.

```
ERROR: 2015/10/15 
*** Error while highlighting:
TypeError: cannot use a string pattern on a bytes-like object
   (file "/usr/local/lib/python3.5/site-packages/pygments/modeline.py", line 22, in get_filetype_from_line)
```

If the BlockCode/Highlight function reported the file and line number for the code snippet being processed, it would be a lot easier to find out what's going on.

**Comment by thatsmydoing** [comment]
This also happens with me when using `pygmentsCodeFences = true`. If I don't specify the language type, I get this error so I think it might have something to do with how the code is passed for language auto-detection

**Comment by nathany** [comment]
thanks for the tip @thatsmydoing

**Comment by PhilipDaniels** [comment]
This error has just started happening for me, I don't understand why, since it was working earlier in the day :-( @thatsmydoing your post helped, I changed from a code fence to `{{< highlight python >}}` and the error went away. Looks like there is a bug somewhere in the parser related to code fences.

**Comment by dmerejkowsky** [comment]
Been there too ... 

Several things:

1/ you can patch your pygments installation to fix the `cannot use a string pattern on a bytes-like object` but it will break stuff. The patch is here:
https://bitbucket.org/birkenfeld/pygments-main/pull-requests/614/fix-error-in-python3/diff

2/ As @thatsmydoing said, it only happens when pygments tries to auto-detect the lexer, and an easy fix is to use ``````text```

3/ There's something fishy going on. I don't know what hugo is doing : I'm guessing it's passing things through a file descriptor, but with the patch I wrote for 1/, you get an error when using a simple shell redirection:

```
$ echo "foo" | /usr/bin/pygmentize 

*** Error while highlighting:
AttributeError: 'str' object has no attribute 'decode'
   (file "/usr/lib/python3.5/site-packages/pygments/modeline.py", line 24, in get_filetype_from_line)
*** If this is a bug you want to report, please rerun with -v.
```

**Comment by wridgers** [comment]
I just came across this issue. Updating to the latest version of Hugo resolve it.
