### ISSUE TITLE
Generator tag not being injected

### ISSUE THREAD

**Issue by deanc** [spf13/hugo#1504]
I have a template like so:

```
<!DOCTYPE html>
<html>
	{{ partial "head.html" . }}
	<body>
*SNIP*
	</body>
</html>
```

Inside `head.html` I have the following tag:
`<meta name="generator" content="{{ .Hugo.Generator }}" />`

Hugo version:
`Hugo Static Site Generator v0.14 BuildDate: 2015-06-16T23:41:12+03:00`

I'm building using this command: `hugo -D -d public_prod/`

Output is always:
`<meta name="generator" content=""/>`

**Comment by superzazu** [comment]
+1, I'm having the same problem too.

**Comment by spf13** [comment]
I can't reproduce this. Can you provide more information / confirm it is still an issue?

**Comment by bep** [comment]
I can't reproduce it either. Please reopen if still an issue.

**Comment by gradymke** [comment]
I'm actually seeing the same behavior in 0.15. I've gotten around it for now by doing the following:
```
<meta name="generator" content="Hugo {{ .Hugo.Version }}">
```
If I use .Hugo.Generator, it always goes in blank. I build the site simply by issuing the hugo command. Is there perhaps a configuration parameter that is off since it can be reproduced by some and not others? My version of Hugo is installed using homebrew on the Mac, so perhaps there is a build irregularity with that version?

For the record, it knows that there should be a value in there since if I change the line to substitute .Hugo.generator with a small "g", the compilation fails.

**Comment by smittie** [comment]
.Hugo.Generator does not inject anything into the resulting html. Here is what .Hugo shows:

&amp;hugolib.HugoInfo{Version:&#34;0.15&#34;, Generator:&#34;&lt;meta name=\&#34;generator\&#34; content=\&#34;Hugo 0.15\&#34; /&gt;&#34;, CommitHash:&#34;&#34;, BuildDate:&#34;&#34;}

It is trying to inject the entire meta line but nothing actually ends up in the html file.

Definitely still an issue.

**Comment by gradymke** [comment]
I can confirm that it works now. Thanks Smittie. Thanks for the troubleshooting tip as well.

**Comment by moorereason** [comment]
@smittie, what exactly is lacking in [the documentation](https://gohugo.io/templates/variables/#hugo-variables)?

**Comment by gradymke** [comment]
Speaking as a user and not a contributor (and a beginner at that), the code snippet from above made all the difference. The intent of what it was providing helped. The fact that it was going to generate the entirety of the meta tag versus just the content piece was lost on me. I expected it to work like .Hugo.Version. So a brief example of usage would have been helpful in my case.

**Comment by smittie** [comment]
@moorereason, let me start off by saying that I like Hugo, or at least I want to. I like the simplicity. However, getting it working and bringing it to the point where it can actually replace Wordpress in publishing my blog has been challenging. This is in large part because I have to figure out how to implement various commands through investigation and trial and error.

For reference, my Hugo implementation is [here](http://smittie.com/hugo/)

.Hugo.Generator is a perfect illustration. This should be very simple to document. Code like this `<exampleGoesHere>` produces html like this `<resultGoesHere>`. I looked up this bug because I could not figure out how to get .Hugo.Generator working from the documentation. At least three other people had the same problem.

I had similar problems figuring out how to get Hugo to inject the language code. In this case there are two pieces of information that are important. Where in the site configuration to set the langague code (eg en-US) and what Hugo command should inject the expected result. I got it working but not as a result of reading the documentation.

I am currently working with the Taxonomy commands to learn what is possible. As a general rule, none of the example code provided in the documentation works in my setup. I cannot simply copy the example snippet and see it work on what I have. I haven't yet figured out why.

I think a shell template that has the basic features explained in the documentation implemented and working would go a long way to helping people get Hugo up and running.

Lastly, good documentation is hard. It is not my intent to rag on anyone or be 'that guy'. I'm interested in being part of the solution within the limited time I have to donate.

   ...Smittie

**Comment by smittie** [comment]
With regard to the documentation for this specific command, .Hugo.Generator, this is the only command I have encountered that generates a complete, enclosed tag. Therefore, the " e.g. <meta name="generator" content="Hugo 0.13" />" did not make it clear to me that the results of this command would be significantly different than the other commands. In hindsight, I understand the writer's intent. It was not clear at the onset. 

   ...Smittie

**Comment by digitalcraftsman** [comment]
The output of the tag is [documented](https://gohugo.io/themes/creation#generator-meta-tag) but not in the expected place where all template variables are listed. In general, it just a shortcut for `<meta name="generator" content="{{ .Hugo.Version }}" />`.

But I agree that we should add an example or at least a note.

**Comment by smittie** [comment]
I'm not sure what to make of that. I reviewed the documentation. I reviewed it again when I couldn't get the command to work. I discovered this bug in my effort to find an answer. In the end, I used debugging techniques to figure out what I could not discover in the documentation.

**Comment by digitalcraftsman** [comment]
@smittie you also stated:

> As a general rule, none of the example code provided in the documentation works in my setup. I cannot simply copy the example snippet and see it work on what I have. I haven't yet figured out why.

What else did you left confused while using examples from the documentation? Feedback is always welcome.

**Comment by digitalcraftsman** [comment]
@smittie I added a more precise description for `.Hugo.Generator` (See ac938d9da70b531bb1c540326cac6a77e8888c43). Hopefully this helps to avoid such obstacles in future.

**Comment by smittie** [comment]
@digitalcraftsman Anything beyond the very basic implementation as seen in the bulk of the themes available is difficult to understand and, at least in my case, impossible to implement. Taxonomies, nothing works. Menu, nothing works. By nothing works I mean that when I try to use the code shown in the documentation, the resulting html is empty with no errors. I have no idea why. I have read through the documentation three or five times now. There are key pieces to how things work that either I am not getting or they are missing.

The directory structure shown on the [overview source-directory](https://gohugo.io/overview/source-directory/) page was an "ah hah" moment. Seeing what a fully populated layouts directory might look like gave me some key bits that I did not pick up in the documentation.

I really think that including a fully implemented directory structure, with all of the template components would really help in understanding how Hugo expects the directory to be. Incorporating some of the explanations from the documentation as comments in the source files would make it a lot easier to understand how things work.

As I continue my journey to understand how Hugo works I will probably build such a directory. If I do not get frustrated and give up first, I will be happy to refine it and submit it as a theme/template. Might be a while though. Figuring Hugo out through debugging is slow and tedious.

   ...Smittie

**Comment by bep** [comment]
@smittie Please take questions/discussions at http://discuss.gohugo.io/
