### ISSUE TITLE
Paketet tillhandahåller inte ett giltigt Installed-Size-kontrollfält. Se Debian Policy 5.6.20.

### ISSUE THREAD

**Issue by Molnfront** [spf13/hugo#1550]
I got this warning when installing hugo 0.14 debian on my Ubuntu 14.04 Mate.

Just to let you know. Continuing with installation now.

**Comment by eric-burel** [comment]
Same with Ubuntu 15.04, it signals that the "Package is of bad quality" (approximate translation from french). However it seems to install correctly.

**Comment by anthonyfok** [comment]
See Issues #1325 and #1946.

Debian and Ubuntu now both carry the official Hugo .deb packages in their respective FTP repositories (since January 2016).  They can be installed by Debian/Ubuntu users using `apt-get install hugo`.

Also, starting with v0.16, we now provide .deb files that are byte-for-byte identical to that from the Debian repositories, see https://github.com/spf13/hugo/releases/tag/v0.16.

Closing this issue.
