### ISSUE TITLE
Support target path in gen man

### ISSUE THREAD

**Issue by joneskoo** [spf13/hugo#1627]
As far as I can understand gen man source, it does not support specifying target directory for man pages. Add support for man page target directory. While at it, why not mkdir target directory if it doesn't exist.

https://github.com/spf13/hugo/blob/master/commands/genman.go#L19

From https://github.com/Homebrew/homebrew/pull/46364#issuecomment-159943405

**Comment by anthonyfok** [comment]
Hi @joneskoo,

Thank you very much for noticing that!  And you are you are right indeed!

I thought I did add a configurable destination man page output directory in my pull request spf13/hugo#1602, but it turns out that I really didn't! No wonder nothing shows up with hugo gen man --help! (Oops!)

Thank you for working around that in the Homebrew recipe(?)/script. I will get that fix in soon to go in for v0.16.

Cheers,
Anthony

**Comment by joneskoo** [comment]
This is excellent news, @anthonyfok. I thought it looked like it was supposed to have that option. No big deal.

I'm not sure if man pages are typically collected into man/1/ structure at build time or if that's install script's task; from grepping homebrew formulae I don't think there's any one truth with this. At least brew supports both models.

**Comment by anthonyfok** [comment]
I think you are right, @joneskoo.  There does not seem to be a universally uniform way of handling man page installation.  Applications with `configure` and `make` tend to automatically install them at the right locations, but other applications... maybe, maybe not.

I think I might use something like this for Debian packaging:

    hugo gen man --dir=debian/tmp/hugo/usr/share/man/man1/

Or maybe I will just let `hugo gen man` create the man pages in the local build directory, and let `dh_installman` (debhelper script) to install to the appropriate directory (usually debian/tmp/hugo/usr/share/man/man1/) before compressing it into a .deb?  I don't know, I will decide later.  :-)

Anyhow, the fix is in.  Let me know if there is any problem.  :-)

Thanks,
Anthony
