### ISSUE TITLE
`brew install hugo` installs v0.14 instead of v0.15

### ISSUE THREAD

**Issue by stuartweir** [spf13/hugo#1633]
Hey there, I went to update to the newest version of Hugo, and I encountered a problem I believe in getting the new version of hugo on my macbook pro. I tried `brew install hugo` as the description of this issue states, and the exact information I get is:

`Warning: hugo-0.14 already installed, it's just not linked`

`hugo version` produces: `Hugo Static Site Generator v0.14-DEV BuildDate: 2015-05-07T00:00:54+02:00`

after uninstalling via brew and reinstalling, as well as quitting Terminal.app and reopening it, I still receive v0.14.

Has anyone else had these issues, and is the other possible solution just downloading the zip? if so, which zip is it? (I'm always bad at remembering which is for Mac haha)

**Comment by anthonyfok** [comment]
As of yesterday, Homebrew should install Hugo v0.15 by default thanks to the speedy contribution by @joneskoo, see https://github.com/Homebrew/homebrew/pull/46364.  Make sure you run `brew update` before you run `brew install hugo`.  If that still gets you Hugo v0.14, perhaps Homebrew's mirrors haven't finished propagated the update yet.

As for the release zip file: Darwin is the name of the operating system which OS X is based on, and since Mac OS X nowadays are 64-bit running on Intel platform, but the x86-64 instruction set is actually created by AMD (Intel's rival), it is often referred to as amd64.

With that background in mind, the binary that you want is [hugo_0.15_darwin_amd64.zip](https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_darwin_amd64.zip) at https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_darwin_amd64.zip

Let me know if it works for you or not.  :smile:

Cheers,
Anthony

**Comment by stuartweir** [comment]
Hey Anthony, Thanks so much for this awesome response! I used the `brew update` and then `brew install hugo` method and it worked :) I really appreciate your help!

-Stu

**Comment by anthonyfok** [comment]
You are very welcome, Stu!  Glad that it worked out for you.  :-)

Cheers,
Anthony

**Comment by appernetic** [comment]
Had this problem today. 

I run: 
brew update && brew install hugo
Migrating Homebrew to v0.9.9
Error: hugo-0.14 already installed

My OSX: 10.9.5

**Comment by moorereason** [comment]
@appernetic, https://github.com/Homebrew/homebrew-core#troubleshooting
