### ISSUE TITLE
Misc case issues for URLs

### ISSUE THREAD

**Issue by joneskoo** [spf13/hugo#1641]
I think there may be a regression for the URLs of uppercase tags.

In https://github.com/spf13/hugo/issues/491 urlize was changed to lowercase URLs. In https://github.com/spf13/hugo/issues/557 I think this may have been reverted?

Now when I added tag links to my post list page:

```
<a href="/tags/{{ . | urlize }}">#{{ . }}</a>
```

The links were broken as URLs come out as mixed case (contain uppercase letters). As a workaround, I can do this and it works.

```
<a href="/tags/{{ . | urlize | lower }}">#{{ . | lower }}</a>
```

I don't think most themes use `| lower`.

cc/ @bep @spf13 who participated in both issues.

**Comment by jeffreycentex** [comment]
It's not just tags that are broken.  I am migrating a blog over from Jekyll that has the url: specified with uppercase characters.  The main index page references the URL the proper way (with uppercase characters), but is generating the files with lower case letters.  Thus my URL's break...

**Comment by gitgrimbo** [comment]
I think I am seeing a similar issue.

I have a folder on disk like the following (part1=lowercase, PART2=uppercase):

content/posts/**part1/PART2**

This folder has an `index.md` that references images in the same folder using a relative link, e.g. `![](999.jpg)`

http://localhost:1313/**part1/PART2/** fails to load.
http://localhost:1313/**part1/part2/** loads ok, but is not the right case compared to what is on disk.

The relative URL to the image for the page that loads resolves to:

http://localhost:1313/**part1/part2**/999.jpg

This will not load in the browser running the hugo server.  I assume because it's the wrong case and hugo is using a different resource-serving mechanism that is case-sensitive.

http://localhost:1313/**part1/PART2**/999.jpg loads ok.

I would like hugo to leave the case alone when handling URLs.

**Comment by moorereason** [comment]
Try setting the following option in your site config:

```toml
disablePathToLower = true
```

**Comment by gitgrimbo** [comment]
`disablePathToLower = true` does not work for me.  The URLs remain lowercase.

**Comment by spf13** [comment]
@gitgrimbo What OS & file system are you using? Do you this site source publicly available so we can investigate further?

**Comment by gitgrimbo** [comment]
WIndows 7 and NTFS.

I lower-cased all my files/folders and flattened the content folder tree after my issues and have since been ok.

And I have a hunch that I also changed all the names of my `md` files to `index.md`, and put them in a folder of the same name, and that helped.  Especially with the relative paths to images.

E.g. from

`/content/article1.md`
`/content/article2.md`

to

`/content/article1/index.md`
`/content/article2/index.md`

The **TL;DR** is probably that I used the wrong mixture of `uglyurls` and relative paths - I did a couple of tests and the results are below.

-----

### Test 1

With this test I can't replicate my issue.  The test is:

`/config.toml`

    uglyurls = false
    disablePathToLower = true

`/content/test1/index.md`

    {
        "title": "test1",
        "description": "",
        "tags": [ "test1" ],
        "date": "2016-05-26"
    }

    ![](./TEST2/HUGO-UP.png)

    ![](./TEST2/hugo-low.png)

`/content/test1/TEST2/index.md`

    {
        "title": "TEST2",
        "description": "",
        "tags": [ "TEST2" ],
        "date": "2016-05-26"
    }

    ![](./HUGO-UP.png)

    ![](./hugo-low.png)

`/content/test1/TEST2/hogo-low.png` - A test png.

`/content/test1/TEST2/HUGO-UP.png` - A test png.

Both the above pages work, linking to the images correctly.

### Test 2

This test uses file names that are not `index.md`.

E.g.

`/content/test1/test1.md`

This produces the following article link from my post list:

- http://localhost:1313/test1/test1/

Browsing to this page **fails** to show the images.  The HTML source is:

    <p><img src="./TEST2/HUGO-UP.png" alt="" /></p>

    <p><img src="./TEST2/hugo-low.png" alt="" /></p>

which is correct, but which results in the following absolute URL:

- http://localhost:1313/test1/test1/TEST2/HUGO-UP.png

which is incorrect  (there is an extra `test1` URL segment).

### Test 3

Using `uglyurls = true`, **Test 2** works, with the post URL being:

- http://localhost:1313/test1/test1.html

and thus the relative paths to the images are correct.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by xofyarg** [comment]
Hi @bep, I can probably provide a test case which is relevant:

**System**
OSX 10.11.6 with Extended filesystem, case insensitive.

**$ hugo version**
```
Hugo Static Site Generator v0.19 darwin/amd64 BuildDate: 2017-03-06T10:44:09Z
```

**$ cat config.yaml**
```
baseurl: "http://127.0.0.1:1313"
languagecode: en-us
title: a test title

theme: test
disablePathToLower: true

MetaDataFormat: yaml
```

**$ cat themes/test/layouts/_default/list.html**
```
list:
{{ range .Data.Pages }}
{{ .RelPermalink }}
{{ .Content }}
{{ end }}
```
**$ find content**
```
content
content/TestFile.md
content/Type
content/Type/TestDir
content/Type/TestDir/index.md
```

**$ hugo && cat public/index.html**
```
list:

/TestFile/
<p>a test file post</p>


/type/testdir/
<p>a test dir post</p>
```

As we could see, the `.RelPermalink` is rendered without case information on path `/Type/TestDir/`.
