### ISSUE TITLE
Related Posts in Single Layout

### ISSUE THREAD

**Issue by tuxy** [spf13/hugo#1677]
Is it possible to include five most recent by date related posts inside ``/layouts/_default/single/html`` ? We have ``.Prev`` and ``.Next`` but that not enough :)

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discuss.gohugo.io/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tuxy** [comment]
@bep okay will do.

**Comment by igramnet** [comment]
Hello!

It is very necessary to derive similar posts according to the principle described in the topic.
https://discuss.gohugo.io/t/get-first-three-posts-in-a-tag-in-a-section/3917

How to do it or introduce it into the new version of Hugo?
