### ISSUE TITLE
Hugo Docs Text Color

### ISSUE THREAD

**Issue by tuxy** [spf13/hugo#1678]
Can you please make sidebar menu text color darker ? I can barely see anything in documentation ^_^ Maybe font is too thin, but its very annoying having to zoom 5x+ LOL

**Comment by moorereason** [comment]
Same goes for the pink links and stuff in the main content areas.  Contrast ratio is poor.

See [Contrast Checker](http://webaim.org/resources/contrastchecker/) and [Contrast Ratio](http://leaverou.github.io/contrast-ratio/) tools.  We, as in "everyone," should shoot for WCAG 2.0 AA compliant color contrast ratios.

**Comment by spf13** [comment]
Please make a PR or help with a new site design. I'd love it to be better for all our users. The current site was great for a small project but Hugo has outgrown it and we need a new one.

**Comment by tuxy** [comment]
actually I like how docs are structured, just needs better font/color :-)

**Comment by anthonyfok** [comment]
I jumped the gun and made a direct commit .  I darkened the sidebar menu grey text to increase the contrast ratio to about 4.5:1, making at least the grey text WCAG 2.0 Level AA compliant.  I did not touch the pink links though, so more needs to be done to be fully Level AA compliant.  Pull Requests welcome.  (Note: The changes are not immediately visible because CloudFlare (?) caches the CSS files...)

(Helpful tools that I used: http://wave.webaim.org/report#/http://gohugo.io/overview/usage/ and http://drpeterjones.com/colorcalc/)

Oh, by the way, @spf13, the current Hugo documentation is still built with an outdated Hugo 0.15-DEV, and some of the Blackfriday fixes regarding nested (?) fenced code block (?) isn't there.  Could you please update Hugo there?  Many thanks!

**Comment by tuxy** [comment]
I still see old text color. Nothing has been resolved =((

**Comment by anthonyfok** [comment]
> I still see old text color. Nothing has been resolved =((

Please try again.  The change should have taken effect 23 hours ago.  It is very likely that you need to **Reload (override cache)**.  For example, in Firefox, instead of pressing just <kbd>F5</kbd> or <kbd>Ctrl</kbd>+<kbd>R</kbd>, you will need to press <kbd>Ctrl</kbd>+<kbd>F5</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>.  (from https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly)

To bypass cache while reloading on other browsers, see https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache

**Comment by anthonyfok** [comment]
> I still see old text color. Nothing has been resolved =((

Hi @tuxy, please try again.  The change should have taken effect 23 hours ago, and it was tested and it worked.

It is very likely that you need to **Reload (override cache)**.  For example, in Firefox, instead of pressing just <kbd>F5</kbd> or <kbd>Ctrl</kbd>+<kbd>R</kbd>, you will need to press <kbd>Ctrl</kbd>+<kbd>F5</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>.  (from https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly)

To bypass cache while reloading on other browsers, see https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache

Hope this helps!

**Comment by tuxy** [comment]
Oh yeah, much better now :-) Thank You!

**Comment by anthonyfok** [comment]
I'll close this issue now.  If there are further concerns, please feel free to reopen it and leave comments.  Thank you all!
