### ISSUE TITLE
Document change in asciidoc in 0.15

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#1685]
See [this thread](https://discuss.gohugo.io/t/asciidoc-toc-stripped-in-0-15) and [this commit](https://github.com/spf13/hugo/commit/b23b546a30df792ad2c8f0cf3ec1be30c53ba34d).  The change in functionality should be highlighted in the 0.15 Release Notes.

**Comment by anthonyfok** [comment]
Yes, it should be documented, not as a new feature, but as a known issue, with the following notes:

 1. It affects only AsciiDoc, which normally renders the Table of Contents with JavaScript, but disables it all with `--no-header-footer`.
 2. Asciidoctor always render the Table of Contents (when the `:toc:` attribute is set) regardless of the `--no-header-footer` setting.

The workaround is to to simply install Asciidoctor, and make sure the `asciidoctor` executable is found in the PATH.  When both AsciiDoc and Asciidoctor are installed, Hugo always prefers Asciidoctor.  (Yeah, I know, favouritism... :wink:)

**Comment by anthonyfok** [comment]
One more note: Thanks to Joram for letting me know, Asciidoctor only starts preserving the TOC with `--no-header-footer` a month and a half ago starting with 1.5.3 released on 2015-10-31, see asciidoctor/asciidoctor#1443 and #1687.  :-)

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
