### ISSUE TITLE
Documentation: Code Highlighting 

### ISSUE THREAD

**Issue by GregorioMartinez** [spf13/hugo#1708]
Highlightjs is incorrectly highlighting code examples on the documentation site.
Example: https://gohugo.io/overview/usage/

Some instances of this is due to highlightjs making an incorrect automatic selection.
Others are due to `<code class="nohighlight">` being used when it should be `<code class="no-highlight>`

**Comment by anthonyfok** [comment]
Thanks for catching this problem!  Yes, we do need to go through the documentation and remove highlighting wherever it is unneeded.

Note, however, that using `nohighlight` is correct according to:

 1. README.md found on https://github.com/isagalaev/highlight.js
 2. https://highlightjs.org/usage/

The real problem here is that I was reading the latest highlight.js documentation while the copy of highlight.js used for building gohugo.io is old.

The upstream change from `no-highlight` to `nohighlight` happened in July 2014 with isagalaev/highlight.js@e4a3971 due to isagalaev/highlight.js#429.  And yes, both `no-highlight` and `nohighlight` still work.

I will upgrade our copy of highlight.js (and other JavaScript and CSS files) first and will come back to this issue later.  :-)

**Comment by anthonyfok** [comment]
Note-to-self: Consider the use of

```js
hljs.configure({languages: []})
```

to disable auto detection of language, see isagalaev/highlight.js#415.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
