### ISSUE TITLE
Accessing Site Variables in Shortcodes

### ISSUE THREAD

**Issue by philipithomas** [spf13/hugo#1723]
For a single page, I'm trying to load data from a json file in `data/` and print it as an html list. 

I'm trying to do this using a shortcode because I do not want to create a template for a single-use page - I just want to generate an html list. 

I can't access `.Site.Data` from within the shortcode. What is the proper way to do this?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discuss.gohugo.io/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
