### ISSUE TITLE
the tag format advice

### ISSUE THREAD

**Issue by hiproz** [spf13/hugo#1761]
for the yaml  format front matter:
![image](https://cloud.githubusercontent.com/assets/4705752/12193569/88794ca4-b624-11e5-89b1-44927e1deff9.png)

i confirm the  spec:http://www.yaml.org/spec/1.2/spec.html 
i think : 
xx:
  - xx
  - xx
is a more appropriate format and  the parser will  more simple and efficient than the [xx,xx] format parser.

and more:
the php spyc lib https://github.com/mustangostang/spyc is support the former style. it is a pop php lib

**Comment by bep** [comment]
In the referenced link you state the opposite. This is valid Yaml.

**Comment by hiproz** [comment]
sorry for the more i want to know that the tags and categories are same as a  list. why they use the different format?

**Comment by anthonyfok** [comment]
To show that both forms are valid, and Hugo support both forms through goyaml.v2, so that the end user has the full freedom to choose whatever form he/she likes?

**Comment by anthonyfok** [comment]
让用户知道 Hugo 通过 goyaml.v2 的强力支持，两种方式都可以使用？给予用户随意选择的自由？ :wink:

**Comment by hiproz** [comment]
yes, i think so

**Comment by hiproz** [comment]
is there any other‘s opinion？

**Comment by anthonyfok** [comment]
The [YAML Ain’t Markup Language (YAML™) Version 1.2](http://www.yaml.org/spec/1.2/spec.html) supports both "block collections" and "flow styles" equally and does not say whether one or the other is more correct.  (YAML 1.2 两种都支持，而且并没有说哪种模式更好或更坏).  From [Section 2.1](http://www.yaml.org/spec/1.2/spec.html#id2759963):

> YAML’s block collections use indentation for scope and begin each entry on its own line. Block sequences indicate each entry with a dash and space ( “- ”). Mappings use a colon and space (“: ”) to mark each key: value pair. Comments begin with an octothorpe (also called a “hash”, “sharp”, “pound”, or “number sign” - “#”).
>
> YAML also has flow styles, using explicit indicators rather than indentation to denote scope. The flow sequence is written as a comma separated list within square brackets. In a similar manner, the flow mapping uses curly braces.

But even the **Spyc**, the YAML loader/dumper PHP that you used as an example, support **both** "block style" and "flow style" (inline sequence or inline arrays)!  连你所举的例子 **Spyc** 也同样支持这种 `[ 'apple', "orange", banana ]` 的格式！ Please look at their example spyc.yaml file:

* Lines 82-89: https://github.com/mustangostang/spyc/blob/master/spyc.yaml#L82-L89

    ```yaml
    # Inline sequences
    - [One, Two, Three, Four]
    
    # Nested Inline Sequences
    - [One, [Two, And, Three], Four, Five]
    
    # Nested Nested Inline Sequences
    - [This, [Is, Getting, [Ridiculous, Guys]], Seriously, [Show, Mercy]]
    ```

* Lines 214-215: https://github.com/mustangostang/spyc/blob/master/spyc.yaml#L214-L215

    ```yaml
    invoice: ["Something", "", '', "Something else"]
    quotes: ['Something', "Nothing", 'Anything', "Thing"]
    ```

So, what are you really trying to say?  The evidence that you presented does not really support your opinion that "block structure" style is better than "flow (inline) sequence" style.  所以，还是那句：你究竟想表达什么？因为，如我们上面所分析的，您所举的例子并不支持您的论点啊？

**Comment by hiproz** [comment]
sorry，我的意思可能表达不是很准确：
1. 我没说不支持，我只是说从我的个人观点：“is a more appropriate format ”更合适，不是说现有的不支持，所以是“advice”。
2. 其实这个问题真正出发点是：tags和categories都是列表数据，可以用同一种格式，为什么分别用不同的表达形式？

**Comment by anthonyfok** [comment]
> sorry, perhaps I did not express what I intended [to say] very accurately:
>
> 1. I did not say [Spyc] does not support [the flow (inline) sequence style]; I was just voicing my personal point of view: [i.e., to say that it] “is a more appropriate format“—i.e., more suitable, not to say it is currently unsupported, so it was [just] an "advice".
>
> 2. Actually, the real raison d'être of this issue is this: tags and categories are both list[/array] data, and could use the [exact] same format, but why are different forms used instead?

I did a bit of digging in Git history, and found these:

1. When Hugo's creator @spf13's first committed Hugo to GitHub on 2013-07-04, he chose to use the "flow sequence" inline style, in JSON, see that initial [docs/content/doc/front-matter.md](https://github.com/spf13/hugo/blob/6e16449e5fca5df192de04430af26a46ea9ceb2d/docs/content/doc/front-matter.md):

    ```json
    {
        "Title": "spf13-vim 3.0 release and new website",
        "Description": "spf13-vim is a cross platform distribution of vim plugins and resources for Vim.",
        "Tags": [ ".vimrc", "plugins", "spf13-vim", "vim" ],
        "Pubdate": "2012-04-06",
        "Categories": [ "Development", "VIM" ],
        "Slug": "spf13-vim-3-0-release-and-new-website"
    }
    ```

2. Two day later, on 2013-07-06, @tychoish changed Hugo to support YAML instead of JSON, and made [the following change](https://github.com/spf13/hugo/blob/431fa0e2d75ca8ddd145bd5db20e50a160772577/docs/content/doc/front-matter.md) in documentation:

    ```yaml
    ---
    Title: "spf13-vim 3.0 release and new website"
    Description: "spf13-vim is a cross platform distribution of vim plugins and resources for Vim."
    Tags: [ ".vimrc", "plugins", "spf13-vim", "vim" ]
    Pubdate: "2012-04-06"
    Categories:
      - "Development"
      - "VIM"
    Slug: "spf13-vim-3-0-release-and-new-website"
    ...
    ```

    And that is the basic form that has stayed until this day.

My take:

1. I think it is best to respect the decisions of the original authors and keep the forms they have chosen.  @tychoish decided to change the examples to use both "block" and "flow/inline" forms, and @spf13 respected that and kept it unchanged for over two years.  As newcomers, I think we should respect @spf13's decision to respect @tychoish's decision too.

2. Using the same form for both "tags" and "categories" may be more consistent and "easier", but it also robs from the new user the chance to see that both forms can be used.  It also robs them of the chance to really think and learn.

3. If you think it will really trip up new users, perhaps we can add a note saying that the "block" form and the "flow" form are equivalent.  Pull request is welcome.

4. Don't we have better things to do than to argue such frivolous details?  :wink:
