### ISSUE TITLE
remove linebreak after IMG

### ISSUE THREAD

**Issue by GuangchuangYu** [spf13/hugo#1767]
is it possible to remove linebreak after IMG? 

See my blog page as an example, <http://guangchuangyu.github.io/douban/>

Thanks!

**Comment by GuangchuangYu** [comment]
One solution is to use table, and I did.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discuss.gohugo.io/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
