### ISSUE TITLE
.Now.AddDate using front matter Param: expected int; got int64

### ISSUE THREAD

**Issue by kostecke** [spf13/hugo#1780]
I'm attempting to generate an adaptive index of monthly calendar listing pages from predefined pages in a series. The link titles are determined at build time based on an offset value in the front matter of each page:

    <dl>
    {{ $name := "calendar" }}
    {{ $series := index .Site.Taxonomies.series $name }}
    {{ range $series.Pages }}
        {{ $title := .Now.AddDate 0 .Params.offset 0 | dateFormat "January 2006" }}
        <dt><a href="{{ .Permalink }}">{{ $title }}</a></dt>
    {{ end }}
    </dl>

This fails to build:

    ERROR: 2016/01/15 Error while rendering section calendar: template:
    section/calendar.html:19:41: executing "section/calendar.html" at <.Params.offset>:
    wrong type for value; expected int; got int64`

Incidentally,`{{ .Now.AddDate 0 1 0 | dateFormat "January 2006" }}` in my template produces the expected result (i.e. "next month" "this year").

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discuss.gohugo.io/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
