### ISSUE TITLE
categories index RSS doesn't match content

### ISSUE THREAD

**Issue by xaprb** [spf13/hugo#179]
The content of my categories listings doesn't match the content of the XML indexes.

http://www.xaprb.com/categories/databases/
http://www.xaprb.com/categories/databases/index.xml

The index.xml contains the content of all articles, not just those from the category.

You can see my templates on github.com/xaprb/xaprb.com. Under layouts/indexes/ you'll see I have category.xml and category.html. The .xml file seems to be ignored, and the ../rss.xml is used instead. But if I copy ../rss.xml into layouts/indexes/ it is still ignored. I can't figure out how to get a category RSS template to override the global RSS template. On http://hugo.spf13.com/layout/variables there isn't any documentation for .Data.Pages which is what I think I need to access in such an index layout.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
