### ISSUE TITLE
Two functions in content.go are doing the same thing

### ISSUE THREAD

**Issue by Skarlso** [spf13/hugo#1808]
Hi guys. 

While I was writing tests for content.go, I found that there are two functions which are doing the same thing but are named differently, and I'm guessing, they should have been doing what they were named for. 

```
//MmarkRender renders markdowns.
func MmarkRender(ctx *RenderingContext) []byte {
	return mmark.Parse(ctx.Content, 
		GetMmarkHtmlRenderer(0, ctx),
		GetMmarkExtensions(ctx)).Bytes()
}

//MmarkRenderWithTOC renders markdowns with TOC.
func MmarkRenderWithTOC(ctx *RenderingContext) []byte {
	return mmark.Parse(ctx.Content,
		GetMmarkHtmlRenderer(0, ctx),
		GetMmarkExtensions(ctx)).Bytes()
}
```

These two. There are others which are doing the same thing as these, but using blackfriday.

What should be done with them? 

Cheers,
Gergely.

**Comment by moorereason** [comment]
I don't see a reason to keep `MmarkRenderWithTOC` since mmark doesn't support a TOC.  It's only called in one place, so adding TOC support later would be easy if mmark ever goes that direction.  I'd remove the function and replace the call to it with a call to `MmarkRender(ctx)`.

We should also consider making `MmarkRender` private to match `markdownRender`.

**Comment by Skarlso** [comment]
Sure thing. Since I'm already working on this area, I can do that if all in favour?!

**Comment by bep** [comment]
Sure, remove the duplicate.
