### ISSUE TITLE
Statements create white spaces

### ISSUE THREAD

**Issue by Javivi** [spf13/hugo#1820]
Statements create a whole empty line at formatting time instead of being ignored if they don't add any content to the website.

![1](https://cloud.githubusercontent.com/assets/1174585/12846412/c1465074-cc0c-11e5-9921-9337e123b6f0.png)
![2](https://cloud.githubusercontent.com/assets/1174585/12846413/c1623ae6-cc0c-11e5-81f4-7f78d40931f3.png)

**Comment by digitalcraftsman** [comment]
Hello @Javivi,

this is caused by the template engine of Go that is used in this theme. The upcoming release of Go 1.6 has a new notation that allows you to avoid this problem by trimming the whitespace automatically. See golang/go#9969.

For a demo take a look at [this](https://www.youtube.com/watch?v=ElwS7FdcNYk) YouTube video (starts at min. 19).

I think the next version of Hugo will be build with Go 1.6 (including the new template features). If you want to use this ealier you have the option to compile Hugo yourself after with the final release of Go 1.6.

**Comment by Javivi** [comment]
Thank you for the heads up.

Marked as closed
