### ISSUE TITLE
Improve (or remove?) deb package on https://github.com/spf13/hugo/releases

### ISSUE THREAD

**Issue by dontspamm** [spf13/hugo#1946]
The package doesn't provide a valid Installed-Size control field. See Debian Policy 5.6.20.

if you dint test the .deb file it give this error

**Comment by bep** [comment]
What package?

**Comment by dontspamm** [comment]
https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb

**Comment by anthonyfok** [comment]
(Thanks for the heads up, @ bep!)

> > The package is of bad quality
>
> > The package doesn't provide a valid Installed-Size control field. See Debian Policy 5.6.20.
> 
> if you dint test the .deb file it give this error

Hi @dontspamm, Thank you for reporting this issue.

I believe this is the error that you saw:

![Screenshot of "The package is of bad quality" dialog on Ubuntu](https://cloud.githubusercontent.com/assets/4147560/3547154/03510044-0892-11e4-811d-2db0fbfec055.png)

(from https://github.com/atom/atom/issues/2183)

This Ubuntu-specific error is completely harmless and is only shown by Ubuntu Software Center (using aptdaemon) and not by other tools like `dpkg -i` or `gdebi`.

That said, an improved .deb package is now available.

### Recommended solution

Try this first:

    sudo apt-get update && sudo apt-get install hugo`

which should work if you are tracking Debian "testing" or "unstable", or if you are already running Ubuntu's xenial, i.e. the upcoming Ubuntu 16.04 to be released in April 2016.

If not, please visit http://packages.ubuntu.com/xenial/hugo and download one of the packages for your architecture.  The sole dependency is libc6 (>= 2.4), so it should work with all versions of Ubuntu since 2008.

### Background

As far as I know, the .deb packages (at https://github.com/spf13/hugo/releases) were _automatically_ generated using '''goxc''' (https://github.com/laher/goxc, a build tool for Go, with a focus on cross-compiling, packaging and deployment).  They were useful as a stopgap measure for Debian and Ubuntu users when an official Debian package for Hugo was not yet available...

But now (since January 2016), Hugo is officially included in Debian and Ubuntu!  See:

* https://packages.debian.org/hugo
* http://packages.ubuntu.com/hugo

### Discussion with Hugo maintainers for future Hugo release

1. Should we keep providing <b>goxc</b>-generated .deb on our Release / download page?
2. Should I try to fix goxc or its underlying "debber" to improve its Debian package generation?

### Sidenotes

* The error message can be seen with the command-line `aptdcon -i hugo_0.15_amd64.deb` where `aptdcon` is a test command-line interface for the Python library `aptdaemon` which Ubuntu Software Center uses as backend.
* AptDaemon is unmaintained upstream, is intended to be removed from Debian (See [Debian Bug#818011](https://bugs.debian.org/818011)), and even Ubuntu is in the process of migrating away from AptDaemon to PackageKit.

**Comment by bep** [comment]
>sudo apt-get update && sudo apt-get install hugo

I haven't thought real hard about this until now, but it is really, really great that Hugo is available via `apt-get` in Ubuntu/Debian. Is this unique for Hugo among the statics?

**Comment by anthonyfok** [comment]
> I haven't thought real hard about this until now, but it is really, really great that Hugo is available via apt-get in Ubuntu/Debian.

Thanks for your encouragement!  Yes, it is the equivalent of `brew update && brew install hugo` which should hopefully make installation and deployment easier for end users.

> Is this unique for Hugo among the statics?

Sorry, my brain is kind of slow today.  What does "statics" mean?  Electrostatic?  Static as in "at rest" or "stationary"?  (/me went Google search for "among the statics" but still didn't get it.)

(10 minutes later...)  Oh!  Did you mean "static site generators"?  If so, no, Hugo is not unique: several other static site generators have been packaged for Debian:

* Website Meta Language (WML): http://packages.debian.org/sid/wml
* Jekyll: http://packages.debian.org/sid/jekyll
* Pelican: http://packages.debian.org/sid/pelican
* Nanoc: http://packages.debian.org/sid/nanoc

And several others such as blogofile, hyde, nikola, chronicle, etc.

**Comment by dontspamm** [comment]
> please visit http://packages.ubuntu.com/xenial/hugo 

that solved the issues
