### ISSUE TITLE
Modified shortcode not reloaded in server mode

### ISSUE THREAD

**Issue by hacdias** [spf13/hugo#1971]
This is in my fundamentos.markdown:

```
{{% moreabout title="Nomenclatura" %}}
Convencionalmente, o nome das constantes é escrito com letras maiúsculas para haver uma melhor distinção no código-fonte. Esta convenção não é obrigatória e não irá causar quaisquer erros durante a execução de um programa. Seguir esta convenção apenas torna mais clara a distinção entre variáveis e constantes dentro do código-fonte facilitando tanto a si, como programador, como a outros programadores que vejam o código do seu programa.
{{% /moreabout %}}
```

And this is moreabout.html shortcodes:

```
<div class="block curiosity">
  <h2>{{ .Get "title" }}</h2>
  {{ .Inner }}
</div>
```

And I'm getting this error:

```
ERROR: 2016/03/13 14:00:10 shortcode.go:266: Shortcode 'moreabout' in page 'fundamentos.markdown' has no .Inner, yet a closing tag was provided
ERROR: 2016/03/13 14:00:10 shortcode.go:266: Shortcode 'moreabout' in page 'fundamentos.markdown' has no .Inner, yet a closing tag was provided
```

What's wrong here?

Sorry if I shouldn't be asking this here.

**Comment by hacdias** [comment]
Strange. I just stopped Hugo and restarted it and it works now.

**Comment by moorereason** [comment]
Did you edit the shortcode while hugo server was running? This sounds like hugo wasn't reloading the shortcode after a change.

**Comment by hacdias** [comment]
Yes, that was it.

**Comment by moorereason** [comment]
So, this is a real bug then.

**Comment by hacdias** [comment]
I'm using Windows.

**Comment by bep** [comment]
I have had this curious experience lately that I have to start the server 2 times for the reload to just magically start working ... But that doesn't make sense ...

**Comment by bep** [comment]
@spf13 I would appreciate it if you could chime and and tell me what your thinking behind this was:

https://github.com/spf13/hugo/blob/master/hugolib/site.go#L478

This seems to think that we only need to render the page content only if the content itself changes.

**Comment by spf13** [comment]
@bep 

The logic around this section as I intended it should be as follows.

There are 3 possible conditions that will trigger a re-rendering of the entire site:
1. a template change
2. a data file change
3. a content file change 

Each step has prep work that only applies to that specific change before the rendering can take place on https://github.com/spf13/hugo/blob/master/hugolib/site.go#L571.

The template change will prepare the templates https://github.com/spf13/hugo/blob/master/hugolib/site.go#L464 

The data change will reload the data files 
https://github.com/spf13/hugo/blob/master/hugolib/site.go#L471

The biggest task is to load/unload/replace the specific content files that changed
This could involve removing a file https://github.com/spf13/hugo/blob/master/hugolib/site.go#L518 / https://github.com/spf13/hugo/blob/master/hugolib/site.go#L529
or rereading one https://github.com/spf13/hugo/blob/master/hugolib/site.go#L534
Then the code is intended to run the conversion on that source file of processing the metadata and populating it in the page structure and converting the markup into html. 

Once that has happened it will then render the entire site https://github.com/spf13/hugo/blob/master/hugolib/site.go#L571 with the updated content, metadata, data or templates as prepared above. 

I suspect that this error may stem from shortcode processing happening during the markup conversion process, instead of after like all of the other templates. I haven't checked and don't remember clearly, but I bet that's what's happening here. 

I did quite a bit of testing with templates and in changing them it did produce the expected results. I don't think I did testing of shortcode modifications though.

Does that make sense? If this is the case, the fix is to check if a changed template is a shortcode and if it is then perform the conversion steps prior to the render steps.

**Comment by bep** [comment]
>Does that make sense? If this is the case, the fix is to check if a changed template is a shortcode and if it is then perform the conversion steps prior to the render steps. 

I have a fix for this (see PR somewhere), but I may have something smarter.

**Comment by spf13** [comment]
I saw the PR and read through it. I think it's doing work that doesn't need to be done, but I haven't dug into it enough to confirm that suspicion. I'm not clear why we need the extra Raw field yet. I'm curious what alternative you are thinking of.

**Comment by bep** [comment]
> I'm not clear why we need the extra Raw field yet. I'm curious what alternative you are thinking of. 

The `contentRaw` field gets modified, so the shortcode is "lost" -- so if I just do a plain Convert, I end up with a page with shortcode placeholders.

The alternative to my PR would be to do a "stripped-down convert" that just re-renders the shortcodes (skips the extraction part). That is obviously smarter ...

**Comment by bep** [comment]
@spf13 My calendar is a little busy these days. Maybe you would like to take a stab at a fix?
