### ISSUE TITLE
Allow configuring the content generation tool command

### ISSUE THREAD

**Issue by essen** [spf13/hugo#1982]
I am looking into using Hugo with Asciidoc. I run into issues with the `--safe` option. I am aware the recommendation is to switch to Asciidoctor if there's issues (https://github.com/spf13/hugo/pull/826/files). But I want to use _Asciidoc_, which I also use for book writing and documentation. I do not want to use _Asciidoctor_.

Right now I solved my problem by going into the Asciidoc source and making the safe() function return false. I'm not sure why `--safe` is used, but regardless, it would be great if the command used could be configured. This would solve my problem and allow people to put additional options. In general a way to define mappings for file-extension -> program -> command would be a great addition.

**Comment by ingorichter** [comment]
+1
That would be a great improvement. I like the idea of having a mapping from extension to command. Is there any interest, except for us, to get this working? I'd like to contribute a solution, since I spent way too much time figuring out what was wrong with my setup. `asciidoctor` was installed and `asciidoc` threw an error at me.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
