### ISSUE TITLE
Update cache of website

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2045]
The website of Hugo uses Cloudflare to cache the assets. It's known that the cache will not be updated automatically if changes are made in stylesheets. A manually reset is necessary.

Currently, we use style-tags as an ugly workaround. Affected are:

- Firefox menu fix #2036
- [The Algolia search form](https://github.com/digitalcraftsman/hugo/blob/8890885a705699e7541cfd42f150b37c0a7a72a0/docs/layouts/partials/search.html#L1-L59)
- The How to contribute to Hugo tutorial #2044 
- The updated quickstart #1888 

@spf13: Please leave a note if you find time to update the cache. I would like to move the (temporary) CSS snippets in the content files.

**Comment by carlmjohnson** [comment]
I have started using https://github.com/carlmjohnson/scattered as an asset hasher for my personal Hugo blog. (Basically, I just run it and pass the hash to Hugo as an environmental variable that gets injected into the template.) Would there interest in having something like that integrated into Hugo? It would probably need to be a new built-in function to retrieve the name of the hashed asset.

**Comment by moorereason** [comment]
@carlmjohnson,
There's an existing feature request for cache busting already open: https://github.com/spf13/hugo/issues/621.

**Comment by carlmjohnson** [comment]
Thanks for pointing me at the right issue.

**Comment by spf13** [comment]
@digitalcraftsman 
I've refreshed the cache on cloudflare. 
I believe that the problem here was actually a corrupt git repo on the server which was preventing automatic deploys of the website from happening (origin, not edge problem).

@carlmjohnson That would be a great feature addition for Hugo. 
Ideally the implementation wouldn't require any template changes or support to work, but simply a config value or flag. 

The hugo transform functionality is likely to be part of a good solution here. https://github.com/spf13/hugo/tree/master/transform

See how the absurl transformer is written https://github.com/spf13/hugo/blob/master/transform/absurlreplacer.go

**Comment by digitalcraftsman** [comment]
I moved the CSS code from above into `style.css`. See ebefa47691d6419c1923d71946439c870c38aa14 and 48fce6110d965eac29a20ea57c4824e4a579ac17.
