### ISSUE TITLE
Allow Tor users to easy access gohugo.io

### ISSUE THREAD

**Issue by anadahz** [spf13/hugo#2158]
Please consider whitelisting Tor in Cloudflare settings of gohugo.io website so that Tor users could be able to access it without entering CAPTCHA.

**Comment by bep** [comment]
I get this CAPTCHA thin myself when using  my VPN ... which upgrades this issue to a bug.

@spf13 ... I guess if you want help supporting your product, you should try to do something about this.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
