### ISSUE TITLE
Investigate tmp file regression

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2168]
See https://github.com/spf13/hugo/commit/b5030782ae5e6cda3aa7a7dd9fb8ffa4f2d16a32

Also see last comment in https://github.com/spf13/hugo/issues/2021

I added the Byword temp files exclude, but I have used Byword for a long time, so this is something that has happened in Hugo 0.16.

**Comment by bep** [comment]
I have checked: I started using Byword last summer (to replace TextMate which had a livereload issue on OS X that is now fixed); we relased 0.15 in November, so I'm pretty sure this is a regression.

**Comment by bep** [comment]
I could maybe narrow it further, but this commit is working: ed3015c35014089deb3b9dae03d0997c04f0834c

**Comment by bep** [comment]
This commit fails: c438f45629a42fe1a38ea1ff665c6016bb5e8aa1

So it looks like one of your commits on Jan 26, 2016.

**Comment by spf13** [comment]
@bep I'm glad you discovered this as it uncovered a major bug in Hugo. I've been able to identify and reproduce the issue. The issue extends far beyond Byword. 

The problem is in the way Hugo now handles events. If a create and then rename event of the same file are triggered in the same notification event Hugo will hang trying to read the created file that is no longer present. The quick fix would be to enumerate and ignore all of the different temp files used but that’s not addressing the real issue. I'm working on a fix for it right now.

**Comment by bep** [comment]
> The quick fix would be to enumerate and ignore all of the different temp files used but that’s not addressing the real issue. 

That seems like an impossible task -- there are plenty of editors out there ...
