### ISSUE TITLE
Static sync to memory fails with Norwegian "å"

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2203]
* Image with Norwegian character "å", aka "ål.jpg" fails to sync in `hugo server`
* --renderToDisk works fine, as do regular hugo builds.
* Curious enough, files with "ø" (another special Norwegian character) works fine ...

**Comment by ks888** [comment]
I think it is normalization problem.

https://blog.golang.org/normalization

As well as `é`, there are several ways to represent `å`. In NFC, `å` is `\xc3\xa5`. In NFD, it is `\x61\xcc\x8a`.

NFC is used in most cases, but in Mac OS's HFS+ file system, a file name is automatically normalized to NFD. Even if we save a file name in NFC, we need to use NFD to open the file.

In this issue's case, Hugo server is able to serve `ål.jpg` file, but we need to use NFD to access it. Since `å` character in markdown/html file are represented in NFC, we are unable to access `ål.jpg`file.

I think this issue can be fixed by normalizing a file name to NFC when files are added to Hugo's filesystem, so that we can use NFC to access files in any cases.

**Comment by bep** [comment]
@ks888 thanks for this. It would be nice, though, if this fix could be applied to Afero (the VFS in use).  I will look into this a little bit later.

/cc @spf13

**Comment by ks888** [comment]
I understand afero as the abstraction layer of various filesystems, and I wonder if normalizing a file name is out of scope.
But, in practice, it sounds very useful if afero normalizes a file name in NFD to NFC.
