### ISSUE TITLE
Shortcodes broken in pygments code blocks

### ISSUE THREAD

**Issue by lucperkins** [spf13/hugo#2223]
I very often use shortcodes to embed things like version numbers in regular docs. This works just fine 100% of the time in normal, but only works sometimes in code blocks. To give an example, I keep the version of `foo` in my `config.yaml`:

```yaml
params:
  versions:
    foo: 2.0
```

My `fooVersion` shortcode looks like this:

```
{{.Page.Site.Params.versions.foo}}
```

When I try to use it in a `bash` code block like this:

```
curl -O https://foo.com/releases/foo/{{% fooVersion %}}/foo-{{% fooVersion %}}.sh
```

It will give me this:

```
curl -O https://foo.com/releases/foo/{#{#HUGOSHORTCODE-1#}#}/foo-2.0.0.sh
```

Notice that it fails when surrounded by forward slashes but works fine when it isn't.

FYI, I have the following configs set:

```yaml
pygmentsuseclasses: false
pygmentscodefences: true
```

I'm going to investigate solutions for this but wanted to register the issue anyway.

**Comment by bep** [comment]
I suspect this was fixed in https://github.com/spf13/hugo/commit/34f40044d7144dddcd613d60df8e24985158dd8c

**Comment by lucperkins** [comment]
@bep That's excellent news. Thank you for all of your hard work.

**Comment by moorereason** [comment]
@bep, I can reproduce with the latest master.

**Comment by bep** [comment]
Yes, I read it wrong. This is a valid bug, I guess an "ordering issue".

**Comment by ks888** [comment]
It seems a shortcode placeholder (like `{-{-HUGOSHORTCODE-1-}-}`) is highlighted by Pygments like the code below, and Hugo fails to replace the placeholder.

```
<span style="color: #f92672">{</span>-<span style="color: #f92672">{</span>-HUGOSHORTCODE-1-<span style="color: #f92672">}</span>-<span style="color: #f92672">}</span>
```

I want to work on this issue. My idea is to change replaceShortcodeTokens() at shortcode.go so that the placeholder can be replaced even if it is highlighted like the code above. Maybe small parsing logic is necessary. Do you think this approach is good?

Another idea is to use better placeholder. `__HUGOSHORTCODE-1__` or something?
