### ISSUE TITLE
Installation of latest release on ubuntu 

### ISSUE THREAD

**Issue by Onuonga** [spf13/hugo#2243]
On issuing: 
 `dpkg -i hugo.<version>`

Installation now gives. 
``` hugo:i386 : Depends: libc6:i386 (>= 2.3.6-6~) but it is not going to be installed
 libc6-dev : Depends: libc6 (= 2.19-0ubuntu6.9) but 2.19-0ubuntu6.7 is to be installed
             Depends: libc-dev-bin (= 2.19-0ubuntu6.9)
 libc6-dev-i386 : Depends: libc6-dev (= 2.19-0ubuntu6.7) but 2.19-0ubuntu6.9 is to be installed
 libc6-dev-x32 : Depends: libc6-dev (= 2.19-0ubuntu6.7) but 2.19-0ubuntu6.9 is to be installed  ```

Further digging shows that: 
``` dpkg: dependency problems prevent configuration of hugo:
 hugo depends on libc6 (>= 2.3.6-6~). ``` 

This therefore means that the package can not be installed in a clean way.

**Comment by anthonyfok** [comment]
Hi @Onuonga,

From the error message you posted, it seems that you were trying to install the i386 (32-bit) binary on your amd64 (a.k.a. x86_86) (64-bit) Ubuntu 14.04 LTS (trusty).  That would not work unless you also install the 32-bit i386 version of libc6 and dependencies.

And no, I am sure we don't want to use the 32-bit Hugo binary when the 64-bit Hugo binary is better for your system.  :wink:

Please do the following instead:

1. Download https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16-1_amd64.deb
2. Run `sudo dpkg --purge hugo`  (because we don't want the 32-bit i386 package lingering around)
3. Run `sudo apt-get -f install` (to fix any inconsistencies, if any)
4. Finally, run `sudo dpkg -i hugo_0.16-1_amd64.deb`

And that would be it!  Please reply back and let us know if it solves the problem for you.

Cheers,
Anthony

**Comment by Onuonga** [comment]
Solved for sure!!! Thank you
