### ISSUE TITLE
customize the template for .TableOfContents

### ISSUE THREAD

**Issue by ktmud** [spf13/hugo#225]
I want to make it work with Bootstrap's [scrollspy](http://getbootstrap.com/javascript/#scrollspy), but the html structure seems to be hardcoded.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by sagikazarmark** [comment]
I would like to bring this up again, because it would be a nice feature. Currently the TOC generator outputs quite an ugly structure which is hard to use together with existing TOC styling and scrollspy plugins (like the ones in Twitter Bootstrap and Materialize CSS).

**Comment by Heydon** [comment]
+1 for greater template control.

In addition, *all* of my table of contents renders inside a single `<li>`. This is not correct, semantically — essentially it is to say that the table of contents is a list of one item?

**Comment by neeklamy** [comment]
@Heydon, the table of contents placed inside a top level `li` is by design, you can see the test code for this in [page_test.go#L807](gohugoio/hugo/blob/873a6f18851bcda79d562ff6c02e1109e8e31a88/hugolib/page_test.go#L807). I’m at a loss as to why, I’ve been trying to figure out the same thing.

I’ve asked about this over at the [\[Resolved\] .TableOfContents variables displays an extra bullet point –Hugo Discussions](https://discourse.gohugo.io/t/resolved-tableofcontents-variables-displays-an-extra-bullet-point/2303).

**Comment by Heydon** [comment]
@neeklamy Thanks for the follow-up. I imagine it's simply a quirk of the logic to build the nested list. But it should be amended.

**Comment by kizu** [comment]
For those who'd want to have a quick and dirty solution for this:

```
{{ .TableOfContents | replaceRE "<nav([^>]*)>\\s*<ul>\\s*<li>([\\s\\S]+)</li>\\s*</ul>\\s*</nav>" "<nav$1>$2</nav>" | safeHTML }}
```

This would remove the initial wrapping `ul>li`. We can also use `replaceRE` to change things inside further if needed.

But yes, it would be preferrable to have a separate redefinable go template for this. I think on the Hugo side it could be done by parsing the result of blackfriday and converting it into a data structure that then could be used as Hugo users would like with a separate template?

**Comment by karel-3d** [comment]
Shouldn't this be now possible, when Hugo is using Goldmark and renders TOC on its own?
