### ISSUE TITLE
docs: Fix Windows PATH issues

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2280]
See https://discuss.gohugo.io/t/windows-terminal-not-working/3676

**The PATH entry should be the folder where Hugo lives, not the binary.**

**Comment by anthonyfok** [comment]
Hi @ bep, thank you for the heads up.

Almost ready to make a commit, but then saw the current paragraphs for Windows 7 and 8.x, and after comparing with https://java.com/en/download/help/path.xml, I hesitated.  But maybe I will just fix the current error in the Windows 10 section and deal with other text later.

Will be pushing when I am back home.

**Comment by bep** [comment]
I don't get it? What is wrong with my bug report re Win 7 and 8?

**Comment by anthonyfok** [comment]
Oh, nothing wrong with your bug report at all: It is not directly related, but it is in the vicinity.  What I had trouble with was this following paragraph that was first submitted by @JoeArizona back in February 2016:

> #### For Windows 7 and 8.x users
> 
> Windows 7 and 8.1 do not include the easy path editor included in Windows 10, so non-technical users on those platforms are advised to install a free third-party path editor like [Windows Environment Variables Editor](http://eveditor.com/) or [Path Editor](https://patheditor2.codeplex.com/).

What I think is that there are probably easier ways to edit the user `PATH` or system `PATH` without using any third-party path editor.  I guess it is not too difficult to append `;C:\Hugo\bin` to `PATH` even on Windows 7 and 8 inside the "Advanced system settings" dialogs or otherwise.  Then there is also the case where the Advanced system settings may not work for non-Administrative users, and also Windows Vista and XP, see e.g. http://superuser.com/questions/165909/ and https://support.microsoft.com/en-gb/kb/931715

What I was also thinking was that it may be easier to:

1. Create a short YouTube video or animated GIF to actually show the user how.
2. Create an installer which automates PATH setting à la go1.6.3.windows-amd64.msi (wait, did it just come out?  I thought it was still 1.6.2 only a few days ago!)

But yeah, both of these are a lot of work on our part, and these are definitely out of scope for this bug report.  (Just me dreaming out loud.)

So yeah, don't worry about it, and I will be pushing shortly when I get home, fixing this issue and #2285 specifically and not anything else.

**Comment by JoeArizona** [comment]
Yo, sorry about that. The .exe file should not have been in the path.

Just in case there's any ambiguity about this statement: "The PATH entry should be the folder where Hugo lives, not the binary."

While the "binary" file should not be in the path, the bin folder should definitely be in the path if they put the hugo.exe file there. Windows command line won't work if the path is C:/Hugo and hugo.exe is in C:/Hugo/bin. bep probably knows this – I just didn't want people to mix up binary and bin.

As for Windows 7 and 8 instructions, a video could work, but don't underestimate how much people can screw up their systems trying to change the PATH variable with the Windows interface. _It's one field._ It's like the field for your first name on a web form, just one field. And it goes on forever, this giant string of smushed up paths separated by semicolons. It's easy to highlight the whole string and delete it with an errant keystroke. In fact, I think it's all highlighted by default when you open it, so one keystroke and it's all gone. The Java doc is missing a step, and novice users will stumble with those instructions. It might actually be easier to use the command line.

**Comment by anthonyfok** [comment]
The fix is committed and now live at https://gohugo.io/tutorials/installing-on-windows/#for-windows-10-users

@JoeArizona Thank you for your insights.  You have a good point there.  Definitely don't want the end-user inadvertently messing up their original PATH variable.

I wonder if we should add code to `hugo.exe` itself for manipulating the system or user PATH environment variable, for Windows only, in a Hugo subcommand, e.g. `hugo set-windows-PATH`.  Good idea?  Bad idea?

**Comment by EYITAY** [comment]
> Oh, nothing wrong with your bug report at all: It is not directly related, but it is in the vicinity. What I had trouble with was this following paragraph that was first submitted by @JoeArizona back in February 2016:
> 
> > #### For Windows 7 and 8.x users
> > Windows 7 and 8.1 do not include the easy path editor included in Windows 10, so non-technical users on those platforms are advised to install a free third-party path editor like [Windows Environment Variables Editor](http://eveditor.com/) or [Path Editor](https://patheditor2.codeplex.com/).
> 
> What I think is that there are probably easier ways to edit the user `PATH` or system `PATH` without using any third-party path editor. I guess it is not too difficult to append `;C:\Hugo\bin` to `PATH` even on Windows 7 and 8 inside the "Advanced system settings" dialogs or otherwise. Then there is also the case where the Advanced system settings may not work for non-Administrative users, and also Windows Vista and XP, see e.g. http://superuser.com/questions/165909/ and https://support.microsoft.com/en-gb/kb/931715
> 
> What I was also thinking was that it may be easier to:
> 
> 1. Create a short YouTube video or animated GIF to actually show the user how.
> 2. Create an installer which automates PATH setting à la go1.6.3.windows-amd64.msi (wait, did it just come out?  I thought it was still 1.6.2 only a few days ago!)
> 
> But yeah, both of these are a lot of work on our part, and these are definitely out of scope for this bug report. (Just me dreaming out loud.)
> 
> So yeah, don't worry about it, and I will be pushing shortly when I get home, fixing this issue and #2285 specifically and not anything else.

Many thanks to @anthonyfok
