### ISSUE TITLE
Hugo Exporter linked in docs does not work

### ISSUE THREAD

**Issue by COLABORATI** [spf13/hugo#2367]
The wordpress-exporter plugin that is mentioned on the [tools](http://gohugo.io/tools/) page does not work. Also that plugin seems to  be simply a rebranding of the [original work](https://github.com/benbalter/wordpress-to-jekyll-exporter) of Ben Balter - which is broken, too, and author does not seem to maintain that any more. So atm there is no working WP exporter for Hugo, please adjust your Tools page in the docs, thank you!

**Comment by digitalcraftsman** [comment]
The plugin seems to be actively maintained. The latest commits have pushed in the last days.

**Comment by moorereason** [comment]
@COLABORATI,
As @digitalcraftsman noted, please file your complaints with the [upstream project](https://github.com/SchumacherFM/wordpress-to-hugo-exporter).

Because that project appears to be actively maintained, I'm closing this issue.  If a project has been abandoned, we may consider removing its listing in the tools section, but that doesn't appear to be the case here.
