### ISSUE TITLE
Update multilingual example

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2417]
The current [multilingual](https://github.com/spf13/hugo/tree/master/examples/multilingual) example used workarounds to create an internationalized website. But since Hugo has [native i18n](https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md) support (as part of Hugo v0.17) it would be consquently to update the example as well.

**Comment by aubort** [comment]
I'd be happy to contribute, if it can wait a week or two before being contributed.

**Comment by aubort** [comment]
I have started to work on this today and will update the code [here](https://github.com/aubort/hugo/tree/multilingual-example/examples/multilingual) as I make progress.

**Comment by aubort** [comment]
Just a quick update on this, I've updated the code and have a very basic version of multilingual site based on the previous example. 
I've updated the branch (https://github.com/aubort/hugo/tree/multilingual-example/examples/multilingual). 

Happy to hear your comments/feedback. I am not sure how complex this example should be, but I still want to add the multilingual menu because I think it is important.
