### ISSUE TITLE
Multilingual articles can't have the same aliases

### ISSUE THREAD

**Issue by mitchchn** [spf13/hugo#2452]
Add `aliases: foo` to the metadata of `bar.md` and `bar.es.md`.

Expected:

- `/foo` should redirect to `/bar`
- `/es/foo` should redirect to `/es/bar`

Actual:

- `/foo` redirects to `/es/bar` (???)
- `/es/foo` is a 404.

Removing the metadata from `bar.es.md` allows `/foo` to resolve to `/bar`, but the Spanish version is left stranded. The practical consequence is that there's no way to rename an article and create a redirect that works across multiple languages.

**Comment by bep** [comment]
Reading from the doc:

"Hugo makes no assumptions about aliases. They also don’t change based on your UglyURLs setting. You need to provide absolute path to your webroot and the complete filename or directory."

Will have to think a little how that applies to this.

**Comment by bep** [comment]
The problem is, I have no clue how to implement this ... as in: How do I know that `/foo` is `/es/foo` and not simply an alias created to match the old WordPress `/foo`?

As such, I think the behavior described by @mitchchn is correct/in line with how it is today: You cannot have duplicate aliases (or: the last one wins).

So, if you really want `/es/foo`, create *that* alias.

**Comment by digitalcraftsman** [comment]
> How do I know that /foo is /es/foo and not simply an alias created to match the old WordPress /foo?

This is a hard one. Introducing some sort of guessing could lead to unexpected behavior for some users.

**Comment by mitchchn** [comment]
> So, if you really want /es/foo, create that alias.

This is acceptable. I'll add a note to the documentation for aliases if it's alright.
