### ISSUE TITLE
Permalink path pages

### ISSUE THREAD

**Issue by johnsto** [spf13/hugo#248]
When defining permalinks like:

```
permalinks:
  posts: /:year/:month/:day/:title
```

This creates `/2014/04/03/my-post/index.html`, but does not create `/2014/04/03/index.html`, `/2014/04/index.html` or `/2014/index.html`. How do I get Hugo to write these? (to e.g. show all posts during April 2014)

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
