### ISSUE TITLE
Enable templating for content files?

### ISSUE THREAD

**Issue by kontsevoy** [spf13/hugo#2480]
I've spent all weekend learning Hugo and was surprised that content files are not treated as Go templates, only layouts are.

This seems like an arbitrary limitation... Why only layouts? Some of my content files are actually HTML (design-heavy landing pages) and I cannot do `{{ partial }}` in them like I can inside "layouts". But using Go templates would be awesome even with markdown.

Without templating, I cannot access any of the data from my content files. It seems that layouts/views are much more powerful than the content which feels backwards... 

Is there a reason for this? Seems like this limitation (apply templating only to views) ruins the elegance of the overall design (in fact, why not let users apply templating even to `static` assets, this would be super-useful for CSS and JS)

**Comment by rdwatters** [comment]
Out of curiosity, why would you want to muddy your content with templating logic? 

> This seems like an arbitrary limitation... 

Treating your content files like the model is SOP at this point for SSGs. Are there other static site generators that allow for adding heavy amounts of templating to the content file (ie, your requested feature)? Content should live independent of the generator since content should be exportable; ie, if you think of "separation of concerns" as a sound engineering principle.  

If nothing else, Hugo is more extensible in that it adds [shortcodes](http://gohugo.io/extras/shortcodes/) to your `.md` files, which is a powerful feature.

> Without templating, I cannot access any of the data from my content files. It seems that layouts/views are much more powerful than the content which feels backwards...

Isn't this the point? 

> Some of my content files are actually HTML (design-heavy landing pages).

Again, just curious on this, but why are you treating these design-heavy landing pages like content files (markdown with yaml) then? Is there a benefit you're finding to treating markdown files like static HTML pages? 

You might also want to look at [data](http://gohugo.io/extras/datafiles/) if you're new to Hugo. 

 > in fact, why not let users apply templating even to static assets, this would be super-useful for CSS and JS

What do you mean by this? Are you talking about build tools for CS preprocessors and JS?

**Comment by kontsevoy** [comment]
@rdwatters Sure, happy to elaborate.

I am moving http://teleconsole.com and http://gravitational.com/teleport from MkDocs to Hugo. They both fit Hugo model perfectly: unassuming md5 files happily rendered inside of a themed frame. So far so good.

But we're adding a bunch of HTML pages to Teleport: case studies, pricing pages, etc. They cannot be made with Markdown and I cannot find a way to integrate them with everything else. Right now they sit in `content/xxx.html` files and they feel completely isolated from everything else. I cannot use variables there, I cannot use partials (like "contact us form"), etc.

Prior to this migration we treated the website from docs as two separate projects, which resulted in tons of duplicated assets. Moving to Hugo is our attempt at having everything generated by a single tool, with a single library of partials.

I hope this doesn't feel too much "out there" and perhaps I'm missing a more idiomatic way of accomplishing this.

The old version of the site is currently live, here's how I'm mapping the existing pages before adding others:

| URL | File |
|----------------------------------|-----------------------|
| http://gravitational.com         | `/layouts/index.html`   | 
| http://gravitational.com/product | `/content/product.html` | 

So... `product.html` is completely dumb: I cannot use any of our partials in there, I cannot insert address/phone variables in it, etc. An alternative I am leaning towards would be to create an empty content file, then create a directory called `/layouts/products` and put `single.html` in there?

Re: other generators. Actually the intro page to Hugo covers this well. They're all tailored to narrow use cases (blogs and docs, mainly) whereas Hugo is trying to be a generic tool for websites of almost arbitrary structure. I think it's pretty close, but the MVC thing inherited from CMS world is getting in the way IMO. Making everything a template would make it much more flexible and elegant. There are already shortcodes that address pretty much the same pain, but in a less elegant way: I am now trying to symlink my partials to also be shortcodes.

**Comment by rdwatters** [comment]
This is starting to become more of a conversation for the [Hugo forum](https://discuss.gohugo.io/), so if you want to keep this going, please move this thread over there.

> So... product.html is completely dumb: I cannot use any of our partials in there, I cannot insert address/phone variables in it, etc.

Why can't you? You can keep your `product.md` at the root of `content/`. What I prefer to do so that I can change the permalinks in my `config.toml` is I have a directory called singles at `content/singles` that houses my about, contact, etc pages. Then in your front matter for each `.md` you create in `singles` just add a type and layout to the front matter:

```
---
title: My Page
type: singles
layout: product
---
```

Then create a `layout/singles/product.html` and add whatever partials you want that you're using elsewhere. Then you're only updating in one location. Also, shortcodes can do everything a partial can and slightly more. A shortcode can range through all site pages, pull select metadata from individual content pages, etc. It also takes positional or named params that your content creators can add on the fly.

> An alternative I am leaning towards would be to create an empty content file...

I don't think you'd ever want to create a completely empty content file, right? You'd want minimal front matter in the file to match your partials in `<head>` for SEO, etc. 

> Again, my templates do not have much "logic", mostly variables and partials as a neat and simple way to quickly create new web pages without much programming.

Nor should they. There is nothing simpler than creating a new content page, especially with Hugo's  [archetypes](http://gohugo.io/content/archetypes/). 

> No, I wanted to access variables and use partials in CSS/JS too. Yes, there are specialized tools out there, but for simple-ish use cases the improvement by making CSS/JS templatized will be huge

There are sooo many tools out there that will do this for you. I would check the forums for tips on how people are using Gulp, Grunt, yada, yada, yada. I don't know how "partials" would work with CSS at all. JS is a different case as well. I'm not sure Hugo is meant to overtake SASS, uglify, etc.

> I think it's pretty close, but the MVC thing inherited from CMS world is getting in the way IMO.

I fully respect everyone's opinion on GitHub and love that it's a friendly forum for collaboration, but MVC extends beyond just the "CMS world." :wink:

**Comment by kontsevoy** [comment]
@rdwatters your suggestion to use a custom type+layout frontmatter directives is that idiomatic way I was missing, thank you very much for this suggestion. Everything "clicks" much better now. You're awesome. I guess nobody would object to me closing this then? :)
