### ISSUE TITLE
Dev, localhost and CORS

### ISSUE THREAD

**Issue by gonzaloserrano** [spf13/hugo#2674]
Hi there,

I've just started with Hugo. I chose the cactus theme (http://themes.gohugo.io/theme/cactus/) and launched the server with `hugo server --config config.toml`.

When i open the URL in the browser i get a `Access to Font at 'http://localhost:1313/fonts/MonoSocialIconsFont-1.10.ttf' from origin 'http://localhost:1313' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:1313' is therefore not allowed access.`.

Any hits? Should hugo set those headers for me somehow or it's a theme thing?

Thanks.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by vojta001** [comment]
Just leaving [a link](https://discourse.gohugo.io/t/dev-localhost-and-cors/4499) here to the question in Hugo Discussion Forum to make it easier for others to find it.
