### ISSUE TITLE
Read More broken in release 0.17

### ISSUE THREAD

**Issue by rskumar** [spf13/hugo#2790]
.Summary template var should contain text before  tag, but in 0.17 release (tested on windows), it contains all txt in that paragraph.

0.16  works as expected.

**Comment by bep** [comment]
I believe this is a designed (this changed subtly in 0.17). Could you provide an example? GitHub repo?

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
