### ISSUE TITLE
0.18 Release Version doesn't render index.md

### ISSUE THREAD

**Issue by koba-ninkigumi** [spf13/hugo#2802]
After upgrading to 0.18dev, index.md is no longer output.
Is this a bug or specification?

https://github.com/koba-ninkigumi/hugo-sample

hugo 0.17
https://github.com/koba-ninkigumi/hugo-sample/blob/master/public-0.17/a/index.html

    <p>a/index</p>

hugo 0.18Dev
https://github.com/koba-ninkigumi/hugo-sample/blob/master/public-0.18Dev/a/index.html

    empty

**Comment by bep** [comment]
Thanks for your input. 

Your example site works great for me. What OS are you on?

**Comment by koba-ninkigumi** [comment]
macOS Sierra 10.12.2

Is this a bug?

**Comment by bep** [comment]
>Is this a bug?

As I said, this works fine for me on macOs Sierra -- so this is a *corner case*. But we'll look into it.

**Comment by koba-ninkigumi** [comment]
I wonder, It is not empty here.
https://github.com/koba-ninkigumi/hugo-sample/blob/master/public-0.18Dev/index/index.html

    <p>index</p>

Is there any hint?

**Comment by koba-ninkigumi** [comment]
@bep A corner case is your environment. Because, I also reproduce this issue, Docker & Wercker CI environment.

Look!
https://github.com/koba-ninkigumi/hugo-sample/blob/gh-pages/a/index.html
is emply

I use 0.18 released version.
https://github.com/ninkigumi/hugo-min-0.18/blob/master/Dockerfile
https://github.com/koba-ninkigumi/hugo-sample/blob/master/wercker.yml

**Comment by bep** [comment]
My main point about the "can't reproduce" label is that *I* cannot reproduce it. A docker file is a step in the right direction, thanks.

**Comment by bep** [comment]
OK, I see it now, you have a naming conflict.

You have a section `a` with `index.md`, so you get 

* the section page a in /a/section.html
* the page for a/index.md in /a/section.html

The last one wins, and sine we now in Hugo 0.18 render all the pages in parallel, the en result is not defined in this case (hence my tests show something different).

Hugo should maybe have warned you about this, but that would be expensive.

In a future versions we will enable you to turn off rendering kinds of pages, but in the meantime you have to rework your site a little. What you likely want is to rename /a/index.md to /a/index.html and provide a section template for it.

**Comment by koba-ninkigumi** [comment]
@bep Thank you for checking the cause!

The behavior is different from 0.17, is it a specification in 0.18? Really?

**Comment by bep** [comment]
>The behavior is different from 0.17, is it a specification in 0.18? Really?

Yes it is different in the ORDER the pages are generated, but the order have never been guaranteed, so the spec is the same in this area. You got lucky in 0.17, that's all.

**Comment by McPringle** [comment]
I have the same problem after I upgraded Hugo. Unfortunately I didn't recognised the **bug** (yes, it is a **bug** because the output changed) for a few days and some pages of my website were "broken" what resulted in a huge loss of my Google rankings – that's not funny. Well, I know Hugo is a zero version but it is a really bad behaviour to your users, especially if some of them really loose money with this bug. There was no warning about that issue.

Anyway, I'm still not amused but let's get productive: I downgraded to Huge 0.17 and that "repaired" my website for now. What can I do to be able to upgrade Hugo again? I need my `index.md` be rendered to `index.html` and I do not want it to be overwritten by automatically generated section files. What possibilities do I have?

```
+-- content
|   +-- documents
|   |   +-- bar.md
|   |   +-- foo.md
|   |   \-- index.md
|   +-- projects
|   |   +-- bar.md
|   |   +-- foo.md
|   |   \-- index.md
|   \-- videos
|       +-- bar.md
|       +-- foo.md
|       \-- index.md
```

@bep, do you have an advice?

**Comment by moorereason** [comment]
@McPringle,
Thanks for reporting this (you too, @koba-ninkigumi).  

Due to us standardizing the rendering order, you'll now need to name your `index.md` as `_index.md`.  Can you confirm that doing so solves your issue?

Once we confirm the new convention, we can update the 0.18 Release Notes to include a notice about this change in behavior.

**Comment by McPringle** [comment]
Hi @moorereason 

Thank you very much for your response. I upgraded to Hugo v0.18 and renamed the `index.md` files to `_index.md` but it does not solve my problem. The automatically generated section files still win and overwrite my manually generated index files.

```
$ hugo version
Hugo Static Site Generator v0.18 BuildDate: 2016-12-19T15:38:10+01:00
```

**Comment by bep** [comment]
@McPringle run `hugo -v` and see if that makes it any clearer.

And please not that this is an open source project, i.e. people work for free.

**Comment by McPringle** [comment]
My directory layout and file names now look like this:
```
+-- content
|   +-- documents
|       +-- _index.md
|   |   +-- bar.md
|   |   \-- foo.md
|   +-- projects
|       +-- _index.md
|   |   +-- bar.md
|   |   \-- foo.md
|   \-- videos
|       +-- _index.md
|       +-- bar.md
|       \-- foo.md
```

I run `hugo -v` with the following output:

```
INFO: 2016/12/26 17:53:20 hugo.go:349: Using config file: /Users/pXXXXX/dev/XXXXX/config.toml
INFO: 2016/12/26 17:53:20 hugo.go:497: using a UnionFS for static directory comprised of:
INFO: 2016/12/26 17:53:20 hugo.go:498: Base: /Users/pXXXXX/dev/XXXXX/themes/anybodyhome/static
INFO: 2016/12/26 17:53:20 hugo.go:499: Overlay: /Users/pXXXXX/dev/XXXXX/static/
INFO: 2016/12/26 17:53:20 hugo.go:532: syncing static files to /Users/pXXXXX/dev/XXXXX/public/
Started building sites ...
WARN: 2016/12/26 17:53:22 template_i18n.go:63: No translation bundle found for default language "en"
INFO: 2016/12/26 17:53:22 site.go:1482: found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
WARN: 2016/12/26 17:53:22 template_i18n.go:45: Translation func for language en not found, use default.
WARN: 2016/12/26 17:53:22 template_i18n.go:45: Translation func for language en not found, use default.
INFO: 2016/12/26 17:53:22 htmlredirect.go:114: Alias "/page/1" translated to "page/1/index.html"
Built site for language en:
0 draft content
0 future content
0 expired content
217 regular pages created
339 other pages created
0 non-page files copied
16 paginator pages created
21 tags created
3 categories created
total in 2089 ms
```

The automatically generated section files win. My Hugo version:
`Hugo Static Site Generator v0.18 BuildDate: 2016-12-19T15:38:10+01:00`

Even if Hugo is an open source project, you should think about your users at every release. If you have a change, that might break the output, you should at least mention it in the release notes. You want your users to trust your work, to trust your software and your users rely on your work. Not everyone works for free on open source software. You have users who need to earn money and who use your open source software e.g. for the websites. Not documenting such changes in the release notes can lead to your users loosing their money and their confidence in your software.

Okay, this was my fault because I use Hugo in a zero-version in a production environment and I did not check every generated page. At the next update we'll go and generate the pages using both versions (old and new) of Hugo and run a diff to look for changes to avoid getting in such a trouble again.

@bep, please excuse me if you took my previous comment personally. You wrote `the spec is the same in this area. You got lucky in 0.17, that's all` to @koba-ninkigumi. Maybe that's correct by I have (still) problems with this. How many people out there have had luck with Hugo 0.17 and damage their website with their update to Hugo 0.18 **without recognising it**? My intention is to sensibilize you and every other committer about what a change can lead to and that a change, which from your side of view should not have any side effects can lead your users into trouble…

For now our build servers run with Hugo 0.17 again and all websites are freshly generated and uploaded, so we are safe and can enjoy the evening…

**Comment by bep** [comment]
As I said, this issue is closed. We do keep support / troubleshooting / questions etc. in one place, i.e. at https://discuss.gohugo.io/
