### ISSUE TITLE
Dead Chimera link

### ISSUE THREAD

**Issue by didenko** [spf13/hugo#2803]
The https://github.com/spf13/hugo/blob/v0.17/docs/content/tutorials/github-pages-blog.md tutorial refers to the [Chimer Arts & Maker Space](https://github.com/chimera/chimeraarts.org) website, which is a dead link. Also, the organization name is Chimer**a** and I do not see it mentioned among the showcase references, unlike stated in the tutorial.

**Comment by anthonyfok** [comment]
Thanks for the heads up!  Apparently, www.chimeraarts.org moved to Squarespace.com some months ago, and since the HTML source makes no mention of Hugo (e.g. in a meta generator tag), it was removed from the showcase in early November 2016, see commit c9be931ebec10f016c729d3ec7b4eed25c0bbc72.

So yes, the documentation will need some modification to deal with this change.  Hmm...

**Comment by magikstm** [comment]
This issue was solved by commit 3818d69. I think it can be closed.

**Comment by didenko** [comment]
Indeed, thank you!
