### ISSUE TITLE
docs: Confusing picture in "Introduction to Hugo"

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2873]
Within the documentation on "Getting Started/Introduction," section "How fast is Hugo?" contains a [link](https://github.com/spf13/hugo/blame/a60ec06383d85c4c28d149d0a1d7da5611ed6fb8/docs/content/overview/introduction.md#L89) to a certain Youtube video. Naturally, before being started, the video displays a picture.

In this picture, the large-font text displays the following equation: "5000 posts / (2 * 365) = 6.8 years". (In a much smaller font, we see the words: "Hugo benchmark – 5000 posts in seconds".)

Upon seeing this picture in this context—especially after seeing the words "5000 posts"—my (and therefore other new users') initial expectation would be to see some calculation of Hugo's speed in rendering something like 5000 blog posts.

Well, 6.8 years doesn't seem to advertise that Hugo is very fast. Now, I'm sure it means something—yet this picture seems confusing without viewing the Youtube video, which most people won't do (I suppose).

**Comment by rdwatters** [comment]
@digitalcraftsman The photo @MarkDBlackwell  is talking about is actually a thumbnail for the YouTube video by Dan Hersam. Since it's not on our channel, we don't have control over setting the default image. The issue re: the size of the title text is also out of our control, since it's YouTube's styling. We can eventually create our own shortcode that takes in a custom thumbnail parameter--I have one ready--but that should be a separate issue/feature. We also draw more attention to Hugo's incredible speed in the new docs. 

For these reasons, I'm closing this...
