### ISSUE TITLE
windows:  COM0 and LPT0 are also invalid on Windows 7?

### ISSUE THREAD

**Issue by magikstm** [spf13/hugo#2883]
I just tried creating files named COM0 as well as LPT0 on my machine and they both give the error "The specified device name is invalid" (the same as the others).

See: htmlredirect.go
Line: 73 (reservedNames := []string{"CON", "PRN", "AUX", "NUL", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9"})

Tested on Windows 7 Home Premium x64 SP1 (English).

I could try on Windows XP and Windows 10 if needed.

**Comment by moorereason** [comment]
According to [this doc](https://msdn.microsoft.com/en-us/library/aa365247%28v=VS.85%29.aspx?f=255&MSPPError=-2147217396#namespaces), the Windows reservation is relative to a "namespace."  To open the `COM0` device, you open the paths `\\.\COM0` or `COM0`.  However, it's okay to open `content/post/COM0`.

Microsoft [recommends](https://msdn.microsoft.com/en-us/library/aa365247%28v=VS.85%29.aspx?f=255&MSPPError=-2147217396) that you don't create files that match their namespace reservations, but we may be able to so long as we open the file relative to a path.

[Original commit](https://github.com/spf13/hugo/commit/e71bef79e504f8a016652380ad4c0ca89a2b8898) was by @anthonyfok.  Comments, Anthony?

**Comment by moorereason** [comment]
I was not thinking clearly when I saw your PR yesterday.  I see what you're saying now.

My point was to question if the reserved names list was necessary.  Are you saying that you couldn't create a file named `COM0` with Hugo?

**Comment by anthonyfok** [comment]
Hello!  Sorry for my tardiness in reply.

It would appear that Microsoft, at times, differ in their code and their documentation.  COM0 and LPT0 are also considered invalid in their code, at least as of Windows 7, but their documentation does not yet cover those two cases.

And if you (@moorereason) hadn't reminded me, I would have totally forgotten that I committed this code in the first place.  I think one of the Hugo users suggested this to me, and then since the Microsoft documentation says so, I went ahead and did it, but quickly forgot about it.  :-)

@magikstm, thank you for catching COM0 and LPT0 that I missed.

There may be some other cases that I missed, as in while e.g. COM1 is reserved, so is COM1.txt and the likes, and I doubt that my original code checks for such reserved names with added file extensions.

> My point was to question if the reserved names list was necessary.
> Are you saying that you couldn't create a file named `COM0` with Hugo?

I guess Hugo might be able to create such a file name under Windows, depending on the version or the shell?, but since Microsoft specifically tells us to avoid these reserved names, it would be good programming practice to avoid them, to avoid creating unforeseen troubles for the end users.

**Comment by anthonyfok** [comment]
An interesting tidbit for reference:
* [What’s the deal with those reserved filenames like NUL and CON?](https://blogs.msdn.microsoft.com/oldnewthing/20031022-00/?p=42073) (on MSDN)

**Comment by magikstm** [comment]
> There may be some other cases that I missed, as in while e.g. COM1 is reserved, so is COM1.txt and the likes, and I doubt that my original code checks for such reserved names with added file extensions.

I can't create a file named "COM0.md", "COM1.md" or any other of the reserved name on my system. My system isn't the cleanest as I do use it for development, but I believe I've not changed that behavior.

How do you handle Windows-specific tests? I believe there are no Windows server in the CI build. Are tests for this platform run "as needed"?

I did some interesting tests trying to copy files from WinSCP (from a Linux Centos 7 server) to my Windows 7 machine:
1) Copied a file named "COM0" -> It was copied as "COM0"
2) Copied a file named "COM0.md" -> It was copied as "COM0.md"
3) Copied a file named "COM1" -> It was copied as "COM1%00"
4) Copied a file named "COM1.md" -> It was copied as "COM1%00.md"

> it would be good programming practice to avoid them, to avoid creating unforeseen troubles for the end users.

I agree.
