### ISSUE TITLE
Snap binary doesn't work with os/exec?

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2914]
See https://discuss.gohugo.io/t/solved-pygmentize-not-working-on-ubuntu-16-04/5063/2

/cc @anthonyfok @elopio

**Comment by elopio** [comment]
Hello. o/

The basic idea of the snap is to isolate your application, so by default you won't be able to call a binary that's not packaged in your snap.

There are ways to declare that the snap needs to go out of its confinement; but in this case, I think hugo can be kept safe and totally isolated by providing pygmentize inside the snap. What do you think @bep?

**Comment by bep** [comment]
@elopio Pygments is currently 1 out of 2 externals Hugo calls via `os/exec`... Hugo's release/build process is already pretty fragmented; I was sold the Snap via a PR as something carefree.

That obviously isn't the case.

I have no knowledge about how to manage snaps and include binaries etc., and it is pretty far down on my TODO list of the things I want to spend my spare time doing. 

@anthonyfok how do the binary that you get when doing `apt-get install hugo` in Debian and Ubuntu work in this area?

**Comment by bep** [comment]
As to the fix:

1) We need Pygments to be included somehow. Having it inside the snap would be cool. 
2) We need to provide a better error message for situations like this. As in: Asciidoc and RST is not supported via snap.

**Comment by elopio** [comment]
@bep, well, it's low maintenance. But first you need to get all your dependencies in there. Or use the classic confinement, if you don't care about the security provided by isolation.
It's simple, let me make a PR to show you.

About asciidoc, I'm not sure how you use it. Can you please explain a little more what do you want to achieve there?

**Comment by bep** [comment]
I'll let @anthonyfok handle this. If he doesn't have time, we will have to remove Snap as a way of distribution. There are plenty of alternatives to get a Hugo binary on Linux.

**Comment by elopio** [comment]
oh, yes, there are plenty of ways. But this one is cool, with all the fancy security, channels and autoupdates ^_^

I would be sorry to see you removing the snap. But really, we are striving to get out of your way and make it as light-weight as possible. If we fail to do that, I would understand you removing it.

Just take a look at the proposed fix. The upside to bundling all your dependencies is that you will stop getting this type of questions, forever. With a simple `snap install hugo` your users will get hugo+pygmentize. If you distribute just the hugo binary, your users will still have to install pygmentize, and might have problems with pip, apt, the virtualenv, or might end up with an incompatible version.

Of course, snaps are awesome for me, that's why I'm working on this. However, I appreciate a lot any kind of feedback you give us to make it better.

**Comment by anthonyfok** [comment]
> @anthonyfok how do the binary that you get when doing apt-get install hugo in Debian and Ubuntu work in this area?

`apt-get install hugo` gets the `.deb` packaging, which is not Snap, hence no special confinement whatsoever, so it can free access `pigmentize`, `asciidoc(tor)` etc. with no limitation whatsoever.

The `snap` version of Hugo is installed with `snap install hugo` and differs quite a bit.

For the meantime, I am tempted to edit `snapcraft.yaml` and simply add the necessary option to remove its confinement altogether (current it can only access `/home`) until a better solution (more time-consuming) is found.

One thing I do wonder: Does `pygmentize` really have to be packaged in the same snap as Hugo?  Can't pygmentize, asciidoctor, etc. be packaged as separate snaps, and have Hugo calls pygmentize, asciidoctor etc. from within those Snaps instead?

**Comment by elopio** [comment]
@anthonyfok with strict confinement and no plugs to go out of it, yes, every snap needs to bundle all their dependencies.
We use interfaces connected with the declared plugs to access services provided by other snaps. If there is a snap that provides the pygmentize service, you could connect to it. But this all needs to be declared so the user knows when and why your application goes out of confinement. Otherwise we end up with the same security risks and API incompatibilities that force debian to have maintainers and complex packages.

**Comment by anthonyfok** [comment]
> Does pygmentize really have to be packaged in the same snap as Hugo? Can't pygmentize, asciidoctor, etc. be packaged as separate snaps, and have Hugo call pygmentize, asciidoctor etc. from within those Snaps instead?

Oh, found my answer at http://askubuntu.com/questions/787149/how-do-snap-packages-handle-shared-dependencies:

> I don't think that snaps check what dependencies are already installed. It just includes all of its dependencies and runtime (which is partly why the LibreOffice snap is 287 MB and the flatpak is about 200MB).
>
> Snaps include pretty much everything the software needs to run. I don't think anything gets shared between snaps.
>
> When a snap updates however, it will only download the dependencies that are new, and not the entire snap.

Time to learn more about snapcraft and experiment?  :-)

**Comment by anthonyfok** [comment]
> @anthonyfok with strict confinement and no plugs to go out of it, yes, every snap needs to bundle all their dependencies.
> We use interfaces connected with the declared plugs to access services provided by other snaps. If there is a snap that provides the pygmentize service, you could connect to it. But this all needs to be declared so the user knows when and why your application goes out of confinement. Otherwise we end up with the same security risks and API incompatibilities that force debian to have maintainers and complex packages.

Interesting...  Thank you @elopio!
