### ISSUE TITLE
Add StartBootstrap Vitality theme

### ISSUE THREAD

**Issue by lafisrap** [spf13/hugo#2948]
https://github.com/hugo-startbootstrap-themes/hugo-vitality-theme

Hugo Vitality would be the first premium theme of StartBootstrap. The original has to be downloaded and installed from [StartBootstrap](//wrapbootstrap.com/theme/vitality-multipurpose-one-page-theme-WB02K3KK3) in two simple steps.

**Comment by bep** [comment]
I notice this is a paid theme -- which we'll have to discuss how to handle. To my understanding, all the current themes are more or less "clone and use".

One comment, though, your exampleSite contains n different toml files with a prefix, and I understand the motivation -- but it would be nice if you could make a copy of one of them into config.toml for the autogenerated demo site.

/cc @digitalcraftsman

**Comment by lafisrap** [comment]
Yes, I thought about the problem that it would be the first paid theme. It's just a nice and powerful theme and $10 are not really a high barrier (for people in the west).

I added the config.toml.

**Comment by bep** [comment]
>$10 are not really a high barrier (for people in the west).

No, the price seems fair, but we have to think about how to mark them so we can filter them etc., and consider if this is an issue for the demo side of it (we're not spending $10 on every paid theme that comes along, to put it like that).

**Comment by lafisrap** [comment]
I would pay the $10 for your demo site ;-) Maybe that would a possible regulation also for other contributors.

**Comment by digitalcraftsman** [comment]
> we have to think about how to mark them so we can filter them etc., and consider if this is an issue for the demo side of it

Marking a theme as non-free shouldn't be a problem by adding a banner. Currently, users can somewhat filter by tags. This could be extended by an JS-based filter plugin but depends on how you want to let users filter the themes.

In general, I would be awesome to see more paid themes. Other SSGs built a small ecosystem around themselves and by paying a small amount of money makes it likely that we'll see more high-quality themes.

Does anyone already thought about how we should host this theme with a demo-site (except the 10$ fee)? 

At the moment users have to make the full source code of the theme publicly available in order to generate a theme demo. This way we would redistribute the theme which is likely to be permitted by the bootstrap theme's license.

**Comment by lafisrap** [comment]
> In general, I would be awesome to see more paid themes.

I think that would be cool to have such an ecosystem for hugo. It could increase theme quality.

> Does anyone already thought about how we should host this theme with a demo-site (except the 10$ fee)?

StartBootstrap offers an extended licence for their premium themes. For Vitality that would be $500. Maybe they would agree if an hugo marktplace sells Hugo version of it for $10 and they get the money for the first 50 sells (as they happen). And from then the income could be shared between author and project. Technically it could just be a shop website with Paypal payment.

I would really like to port more of their non-adminstrative premium themes for such a place. ;-)

**Comment by Jos512** [comment]
> Does anyone already thought about how we should host this theme with a demo-site (except the 10$ fee)?
> At the moment users have to make the full source code of the theme publicly available in order to generate a theme demo.

It would depend on how popular the commercial themes get (that is, how many get made), but for the time being it seems the responsibility of the theme author to provide a full copy to the person managing themes.gohugo.io so that this theme can be placed in the correct directory and rendered when the Hugo theme site build.

I don't think it would be a good idea to look into ways to automate that or have the author submit their own commercial theme through an online application, given the time investment of those tools.

> StartBootstrap offers an extended licence for their premium themes. For Vitality that would be $500. Maybe they would agree if an hugo marktplace sells Hugo version of it for $10 and they get the money for the first 50 sells (as they happen).

Why overcomplicate things? Just host the theme on themes.gohugo.io so people can take a test drive, and add a link back to wrapbootstrap.com. A Hugo marketplace seems an additional burden with also a lot of additional legal and financial risks. I don't think Hugo should meddle with that.

I'm not against Hugo earning money with this. From one standpoint that seems only fair since themes.gohugo.io provides a service (promotion, advertising, demoing) to the author of a commercial theme. But there are easier ways to earn money with that: ask the theme author a fee when putting up the theme or [become an affiliate for wrapbootstrap.com](https://wrapbootstrap.com/affiliates).

Creating a Hugo marketplace seems like re-inventing the wheel. (If you haven't guessed by now, my personal bias is a strong believe in focus. 😄 )

**Comment by lafisrap** [comment]
> Creating a Hugo marketplace seems like re-inventing the wheel. (If you haven't guessed by now, my personal bias is a strong believe in focus. :smile: )

Keep it simple stupid. I understand that. From my side it was just an idea to maybe get a higher quality with such a market place. Sometimes you can save a lot of time by spending $10 or $20. I watched me do it ...

Here are two links to demos of the flavours of the theme, currently hostet on my server ... I could send them as a package to you. I have two licenses for them.

[Agency](//c2064.org/v/agency)
[Video](//c2064.org/v/video)

**Comment by bep** [comment]
I didn't notice this before, but this issue belongs at

https://github.com/spf13/hugoThemes
