### ISSUE TITLE
Pagination of multilingual pages is slightly broken

### ISSUE THREAD

**Issue by aroig** [spf13/hugo#2972]
If I add a paginator on a section page which is translated to several languages, two problems appear:

1. The cross-language links obtained from `.Translations` from a page in the pagination sequence different from the first, point always to the first page of the translation.
2. The `.Translations` variable for non-first pages includes the first page of the current language.

I think 2 may be a consequence of 1. It looks like 1 is going to be annoying to fix, since pagination happens very late in the rendering process. I guess a good way to fix it would be to make pagination pages into proper pages, etc, etc.

**Comment by bep** [comment]
Please don't use "broken" unless you have a well defined "correct solution".

There may be work to be done with pagination vs multilingual (had to stop somewhere), but I'm not sure this is one of them.

I see 3 alternatives:

1. Return an empty `.Translations` for pages > 1 because we have no good way of guessing translation.
2. Link to the same page, so "/home/en/32" => "/home/no/32"
3. Always link to page 1 (current status)

2 would very rarely be correct (as it would need 1:1 translation for all languages, with equal sorting, taxonomy definition etc.), and it isn't cost effective to try to implement some logic around it. 

**So then it is 1 or 3?**

**Comment by aroig** [comment]
> Please don't use "broken" unless you have a well defined "correct solution".

I was thinking of 2 above, but as you point out this can't be a general solution because of missing pages. In that case, I agree that current behavior is ok.

In a blog-like site, one may want to fall back to a different language instead of skipping a missing translated page. In such mode, then 2 would make sense.

The second problem I reported is fixed by #2976.
