### ISSUE TITLE
Exceptions to canonicalized URLs?

### ISSUE THREAD

**Issue by campadrenalin** [spf13/hugo#298]
I want the vast majority of my URLs to be canonicalized - but there are a few that need to stay untouched by canonicalization. And most of these "exception" links are in markdown files. Is there anything I can do to exempt them from having .Site.BaseUrl prepended?

_(specific detail)_

My blog is not going to live on its own subdomain, but /blog/. This can be accessed from _multiple subdomains_, which are available on different networks. So it's important to be able to make links from the blog, to "/foo.html". But within the blog, it's great to be able to rely on canonicalization, and just use "/css/main.css" and such, especially when using "hugo server -w" for rapid feedback (which hosts everything on "/" regardless of baseurl).

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
