### ISSUE TITLE
Site rebuild procedure is not the same as site build

### ISSUE THREAD

**Issue by rodrigopv** [spf13/hugo#3000]
Hi,

I've started using Hugo and I wanted to create a static page for the homepage, so I created the file content/index.md and it worked fine.

Later I noticed that when I modify a file (data/Menu.toml, a file not related to homepage or theme) while running hugo server, it will detect the file change and rebuild the site. After rebuilding, the index.md is no longer being rendered on homepage, and the old blog style page from theme appears again.

When I quit and start hugo server again, index.md is being rendered without issues on homepage.

It seems like a erratic behaviour as I have to start hugo again for each change to avoid this bug.

`$ hugo version`
`Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-29T14:12:41-03:00`

**Comment by jeffreycentex** [comment]
Yes, I have seen this behavior..

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
