### ISSUE TITLE
_index.md only sets front matter, not content

### ISSUE THREAD

**Issue by Shadow53** [spf13/hugo#3008]
There is a particular folder on my website whose landing page I am trying to overwrite with an _index.md file. It didn't work and I've tried a handful of different configurations to get it to work. Here's what I found:

- No file: default (blank) content-type landing page with typename+"s" as the title.
- _index.md: title is changed to the one specified in the front-matter of the file, but none of the content is displayed.
- index.md: same as no file.
- _index.md AND index.md (with same contents in each): correctly generates page with the right front matter and content (or whatever is in the index.md file, ignoring _index.md).

I'm assuming this behavior is not by design, since the docs say that you only need an _index.md file.

I should note that I have also successfully used a method of having a folder and a file outside the folder with the same name but ".md" appended to the end for generating the "index.html" file for that folder. That did not work in this particular case either, as it had the same behavior as not having any file.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
