### ISSUE TITLE
partialCache cache not flushed between reloads

### ISSUE THREAD

**Issue by 824f1ba4** [spf13/hugo#3016]
Discussion started at: [discuss.gohugo.io/t/no-cached-partials-with-server-command-or-watch-flag/](https://discuss.gohugo.io/t/no-cached-partials-with-server-command-or-watch-flag/5380)

When using the 'server' command or the 'watch' flag, the cache of the [partialCached template function](https://gohugo.io/templates/partials/#cached-partials) does not get flushed.

**Details**
Hugo version: Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30T11:02:43+01:00
OS: Fedora 25 64-bit

**Comment by bep** [comment]
You may want to test the current master for this. I suspect it is fixed.

If not, I will check and close this as part of https://github.com/spf13/hugo/pull/3010

**Comment by Jos512** [comment]
I like this feature/bug by the way, since a large part of my themes don't need to be rebuild with every website change (things like article count, random fetch of related articles, etcetera). 

I believed that the partialCached not being flushed was a feature, since the documentation says that partialCached is not rendered every time. I read that as cached across different rebuilds too.

> "(...) for complex templates that don’t need to be rerendered upon every invocation."

**Comment by bep** [comment]
No, it is clearly a bug. The main moivation of `partialCached` is that if you, say, do some heavy computation in a partial, and that partial is used in 1000 pages, then that computation should only be done 1 time **per build**.

**Comment by Jos512** [comment]
Ah okay. Thanks for the clarification, then I've misunderstood and partially misused `partialCached` in my themes.
