### ISSUE TITLE
.Paginator.RegularPages

### ISSUE THREAD

**Issue by tjallingt** [spf13/hugo#3017]
Seeing as 0.18.0 added many new kinds of pages it would be nice if there was an easy way to paginate old way.

https://github.com/spf13/hugo/issues/2775 already added this feature `.Site` so I'd imagine it would be pretty easy to add to `.Paginator` as well.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by tjallingt** [comment]
https://discuss.gohugo.io/t/add-paginator-regularpages/5391

There you go...
I'm pretty sure this is an enhancement (which you admit belongs in an issue) but whatever.

**Comment by divyats6550** [comment]
Hi...I have an issue....I have a front matter field for expiryDate. I want pagination listing all the expired content posts..Is it possible?

My requirement is , I have two tabs for upcoming events and past events. so for showing the past events, I set the expiryDate.

Can somebody help please.....
