### ISSUE TITLE
Normal page not selectable in menu

### ISSUE THREAD

**Issue by belak** [spf13/hugo#3027]
Using the following portion of a menu and a page called about.md, this page will never be selected in the menu (IsMenuCurrent/HasMenuCurrent always return false). It looks like IsMenuCurrent always returns false for pages (if p.IsPage()) and I'm not sure why. It looks like it might be a leftover from some transition from Node to Page, but I don't have much context for this codebase.

```
  [[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by belak** [comment]
I do feel like this is an actual bug. Here's what I did to run into this:

* Create a new hugo project
* Download a theme (in my case after-dark)
* Create an "About Me" page
* Add a manual link to the about page on the menu (using the instructions from the docs)

What I expected to happen:

When I visited the "About Me" page, I expected that link in the menu to be selected (as the theme copies some of the rendering code from the "Menus" page of the docs almost directly).

What actually happened:

That link wasn't selected.

Here's a sample config:

```
languageCode = "en-us"
title = "My New Hugo Site"
baseURL = "http://example.org/"
SectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
```

Here's a sample `content/about.md`

```
+++
title = "About Me"
draft = true
date = "2017-02-11T02:28:14-08:00"

+++
```

after-dark can be cloned from https://github.com/comfusion/after-dark/

Hugo was run using `hugo serve -D -t after-dark`

I'd be happy to answer any additional questions.

**Comment by bep** [comment]
Please post this at the forum. I'm pretty sure you got it wrong somewhere in there, but I don't do questions/troubleshooting on GitHub.

**Comment by cfjedimaster** [comment]
I've spent about 2 hours on this and it looks like it is still an issue. I did file a forum post, but as @belak mentions above, this seems like a bug in the source:

https://github.com/gohugoio/hugo/blob/master/hugolib/page.go

I'm seeing what he sees:

```
if p.IsPage() {
		return false
}
```

Is that intentional? Or did we both get it wrong? ;)
