### ISSUE TITLE
Small nit: Quickstart guide uses a command not available on Git Bash Windows (MINGW64)

### ISSUE THREAD

**Issue by igufi** [spf13/hugo#3041]
I'm just going through the tutorial and noticed that the command "tree -a" is not available with Git Bash (the command is used on steps 2 and 3).

**Comment by thevukaslt** [comment]
You may use 'tree .' as an alternative to 'tree -a' limiting listing only for the current directory.

**Comment by igufi** [comment]
Thank you for the tip - my bug report was more about the fact that the tutorial doesn't work 1:1 for the Windows user (assuming he/she is using Git Bash, as instructed at the beginning of the guide). 

$ tree .
bash: tree: command not found

It's a tiny, editorial issue.

**Comment by thevukaslt** [comment]
I have to apologize, I am the user of Windows Command Line and was writing intentionally for cmd users. So, as seen this doesn't work with Git Bash environment.

**Comment by rdwatters** [comment]
@igufi I noticed this when I was working on the new docs concept (https://hugodocs.info). I've made this a little more generic since it assumes that end users across the board are using `tree`, which is clearly not the case. I've pared down the QS a lot, but sooner rather than later I'd like to redo it:

https://hugodocs.info/getting-started/quick-start/
