### ISSUE TITLE
hyphenation support

### ISSUE THREAD

**Issue by gour** [spf13/hugo#307]
Some Python static site generators (Acrylamid, Nikola,...) have support for hyphenating posts which can look really nicely - see e.g. http://blog.posativ.org/2014/gentoo/. The Acrylamid docs is here: http://posativ.org/acrylamid/filters.html?highlight=hyphen#hyphenate and e.g Nikola is using http://pyphen.org/.

I'm not aware what is the situation in Golang, but probably there is some decent hyphenation support as well.

Sincerely,
Gour

**Comment by gour** [comment]
@natefinch I'd rather have it slow (ala Pygments), than no feature. ;)

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by silberzwiebel** [comment]
This is a feature request and I still think it is relevant and valuable. As an example, please see how [missing hyphenation makes the title of my blog post look rather ugly](https://kartoffelsalat.ddns.net/post/keine-verkehrswende-muenster/). (Please let me know, if I'm just missing the correct option somewhere, and sorry for the noise then.)

**Comment by iiegn** [comment]
i second the idea that *hyphenation support* is **still a relevant and valuable feature request**. especially narrow(-ish) columns on small screens would benefit.

The main problem seems to be that there doesn't exist up-to-date offline soft hyphen `&shy` generation support (for go) - in particular, no [currently maintained](https://github.com/sthorne/go-hunspell) hunspell bindings exist.

but (for people arriving here and looking for a possible solution), browsers have caught up: have a look into the [`hyphens`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens) and the [`overflow-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) CSS properties.
