### ISSUE TITLE
Failed to create index.html and 404.html

### ISSUE THREAD

**Issue by JamesGDEv** [spf13/hugo#3105]
Hi There, 

I have recently just stumbled across your project. I love the idea and decided that I would give it a ago. I am a noob but you have to start somewhere right?, Anyway, apologies if this is a nooby question. 

I am following your get started guide: https://gohugo.io/tutorials/creating-a-new-theme/

it says that when I run hugo server it should create 4 blank files. 404.html, index.html, index.xml and sitemap.xml

however, It is only creating index.xml and the sitemap.xml. 

Any ideas why it is not producing the other two files? Can I just create them myself manually? 

This is a complete new install and I have followed the guide to this point.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by JamesGDEv** [comment]
Surely this is a bug? Hugo is not generating the files that it should.
