### ISSUE TITLE
Unable to locate template for shortcode 'br' in page 

### ISSUE THREAD

**Issue by xenoterracide** [spf13/hugo#3111]
I doubt this is a bug, other than perhaps being hard to troubleshoot given the message, and in the much outdated blogger import script

    ERROR 2017/02/28 14:45:39 Unable to locate template for shortcode 'br' in page creating-new-projects-with-dzil-new-and-templates

https://github.com/xenoterracide/blog/blob/b8b9f0209f244cb4290b42df228131d2296fb3fb/content/post/creating-new-projects-with-dzil-new-and-templates.md

Perhaps you could illuminate me as to which `br` is causing the issue, how to fix, and make the error message better?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by xenoterracide** [comment]
sorry that you don't feel like the lack of line:column which all other errors had is a bug

**Comment by moorereason** [comment]
@xenoterracide, the problem is at 10:2062.  You have `{{<br />`.  Hugo uses the `{{< ... >}}` syntax for shortcodes.  Please continue this discussion in the forms.

**Comment by bep** [comment]
>sorry that you don't feel like the lack of line:column which all other errors had is a bug

That info isn't there because it isn't easilly available when the error is produced.
