### ISSUE TITLE
Menus weight and other oddity

### ISSUE THREAD

**Issue by Fastidious** [spf13/hugo#3119]
Have something changed from `0.18.1` to latest that will cause menus weight to stop working? I had to revert to `0.18.1` because of that. I was also getting a `WARNING: Page's Now is deprecated and will be removed in a future release. Use now (the template func).` (using `after-dark` theme).

Thanks!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
