### ISSUE TITLE
Make the govendor more visible in the contrib docs

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3153]

**Comment by bep** [comment]
I think a /cc to @moorereason might be more appropriate. He rewamped the make file to handle govendor and should add some bold sentences in the "building Hugo" section.

**Comment by digitalcraftsman** [comment]
I cc'ed Ryan because it should also be included in the reworked docs.

**Comment by moorereason** [comment]
Yes, contrib guide needs to be rewritten.  I'll work on that.

The rule is generally that `go get` is useless since it ignores vendoring.  You must use `govendor get` or `git clone`+`make `.

Since we support two minor Go releases, this story will get less complicated with the next two Go releases:

* With Go 1.9, we can drop Go 1.7 and no longer have to talk about GOPATH.
* With Go 1.10 we can drop Go 1.8 and hopefully have [dep](https://github.com/golang/dep) in the standard Go tool chain in Go 1.9.  Bye bye, govendor.

**Comment by moorereason** [comment]
Actually, all of this would be simpler if we committed the vendored packages.  @bep, what do you think about doing that?  `go get` would work as expected in that case.

**Comment by bep** [comment]
> @bep, what do you think about doing that? 

A big and mighty NO.

**Comment by moorereason** [comment]
For the record, the `dep` tool is [planned](https://github.com/golang/dep/wiki/Roadmap) for inclusion in Go 1.10, so the timeline I mentioned above would be pushed out one additional Go release.

**Comment by bep** [comment]
I would say that, if `dep` makes life much easier for us, we could adjust the "two Go version" promise for that particular case. I would think that even if we went with `dep` in Go 1.10, it should still be technically possible to build with Go 1.9 with some workarounds.
