### ISSUE TITLE
config not found and pictures not showing in hugo server

### ISSUE THREAD

**Issue by harri00413** [spf13/hugo#3173]
Hi, I'm starting out with Hugo and am running into some issues. When I set up my first trial site the picture I put in is missing, when running it with hugo server.
 Looking at the output I see "Using config file: ", i.e. empty, no config file is used. 

Have attached some files.

Hope someone can help.
Cheers,
Frank
![picturemissing](https://cloud.githubusercontent.com/assets/16068681/23835693/367e0efe-076c-11e7-8043-44d73b4435cd.jpg)
[Background Hugo showing picture problem.txt](https://github.com/spf13/hugo/files/836891/Background.Hugo.showing.picture.problem.txt)

[config.toml.txt](https://github.com/spf13/hugo/files/836893/config.toml.txt)

[post.md.txt](https://github.com/spf13/hugo/files/836896/post.md.txt)

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by harri00413** [comment]
you're right, sorry for barking up the wrong tree..
