### ISSUE TITLE
Possibility to do a next / prev based on the content type?

### ISSUE THREAD

**Issue by mpas** [spf13/hugo#319]
When trying to implement Prev / Next for a specific content type i run into a problem when i have another content type like for exampe pages.

```
        {{if .Next}}
        <li><a class="previous" href="{{.Next.Permalink}}">← {{.Next.Title}} </a></li>
      {{end}}
      {{if .Prev}}
        <li><a class="next" href="{{.Prev.Permalink}}">{{.Prev.Title}} →</a></li>
      {{end}}
```

This results in the fact that 'post' and ' page' contenttypes are mixed. Is there a way to limit the Prev / Next to a specific contenttype?

I would like to have only Prev / Next for the contenttype 'post'

**Comment by chibicode** [comment]
:+1: I'd appreciate this feature. @yacoob doesn't that approach fail if `.Prev` isn't of the `post` type?

**Comment by bep** [comment]
In 0.13 there is .NextInSection, .PrevInSection.

**Comment by chibicode** [comment]
@bep totally missed that...thank you!

**Comment by chibicode** [comment]
It doesn't seem to work unless you're on a section page though. It's returning me nothing on a single post page.

**Comment by bep** [comment]
It work for what it says it does.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
