### ISSUE TITLE
Hugo put unknown character right after body tag

### ISSUE THREAD

**Issue by dehghani-mehdi** [spf13/hugo#3197]
Hello,

I'm using latest version of Hugo, as you can see in below screenshot, there is unknown character right after `<body>` tag.
![01](https://cloud.githubusercontent.com/assets/9152330/24079154/ce87e042-0c96-11e7-9377-8ae876b3071a.png)

Notice that you should edit html in browser console to see that, (in Firefox simply right-click on `body` tag and select `Edit As HTML`, _almost same for Chrome_).

BTW, I have no idea why Hugo inject `meta tags` & `css links` inside `body` instead of `head`. maybe this is the reason of above problem, I don't know.

__Update__

I have this:

    <!DOCTYPE html>
    <html lang="en">
        {{ partial "head.html" . }}
    <body>

And `head.hmtl` contains some meta tags and css links. now If I remove ` {{ partial "head.html" . }}` from `index.html`, problem will solved. also I tired to remove all content of `head.html`, but `<head></head>`, it doesn't help.

For now I moved `head.html` content to `index.html` and it works, looking fwd to fixed version of Hugo.

Thank you.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by dehghani-mehdi** [comment]
Putting extra character by Hugo is not a bug?!

**Comment by bep** [comment]
>Putting extra character by Hugo is not a bug?!

Your automatic assumption is that Hugo put that character there. I think we would agree that if someone other than Hugo put that character there, it would not be a bug. Start a thread on the discussion forum as I told you to do, and we might solve this mystery.

**Comment by dehghani-mehdi** [comment]
This is the first time that I heard that about bug. it doesn't matter, I can moved head content to every main html file, but I won't use Hugo for my next project because of this poor support.

Good luck!
