### ISSUE TITLE
Theme Request: eBook

### ISSUE THREAD

**Issue by ardalis** [spf13/hugo#3233]
I'd like to create a static site to support an eBook. None of the existing themes I've seen seem well-suited to this. Here is an example of such a site:
http://www.easylaravelbook.com/

The theme should include a home page that can feature the book and its TOC and testimonials, a menu with links to landing pages on the site to buy the book or learn about the author. It should be pretty simple, overall.

Can someone point me to a theme that would work well for this purpose, or perhaps work with me to help produce one?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by ardalis** [comment]
Ah, sorry, thanks. A quick search reveals that I'd previously asked this on the forum (with no response). Here's the link as requested: https://discuss.gohugo.io/t/recommendations-for-ebook-theme/5400
