### ISSUE TITLE
"Hosting on Github Pages" tutorial seems to have a typo

### ISSUE THREAD

**Issue by BruceEckel** [spf13/hugo#3238]
> This requires to change the Hugo publish directory in the site config (e.g. config.toml):
> publishDir: "docs"
 
If you put this into your `config.toml` file and try to build your site, it produces an error. I think the last line should be:

> publishDir = "docs"

**Comment by rdwatters** [comment]
@BruceEckel Good eye. Closing this because it is fixed in the upcoming docs site:

https://hugodocs.info/hosting-and-deployment/hosting-on-github/

BTW, for any other feedback-only pieces on the docs, I'd certainly appreciate suggestions via the forums: 

https://discuss.gohugo.io/t/new-docs-site-need-feedback/5765

Or feel free to submit an issue (or, better, a PR) on the docs temporary repo while the team works on making this the new docs site:

https://github.com/rdwatters/hugo-docs-concept/
