### ISSUE TITLE
Change to Github Pages

### ISSUE THREAD

**Issue by thomcrowe** [spf13/hugo#3249]
Github Pages now requires you to put your site on the `master` branch, so you can't push to a `gh-pages` branch like in the quickstart guide.

**Comment by rdwatters** [comment]
You *can* still push to a `gh-pages` branch, but you might be talking about a GH Pages for Users and Organizations:

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

FWIW, @thomcrowe,  you'll also see that I've removed the GH pages/deployment step of the Quick Start in the new docs. This is only the first step, since I need to (eventually) redo the entire Quick Start for multiple reasons: 

https://hugodocs.info/getting-started/quick-start/

I've also updated the respective page within the new "Hosting and Deployment" section to make this clearer for users:

https://hugodocs.info/hosting-and-deployment/hosting-on-github/

**Comment by rdwatters** [comment]
For the above reasons, think we can close this @bep ?
