### ISSUE TITLE
Template functions in content

### ISSUE THREAD

**Issue by metachris** [spf13/hugo#3293]
Hello,

I couldn't find anything in the issues or website regarding using template functions in post/page content. Is this possible? 

Cheers,
Chris

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by mlncn** [comment]
Because this question is not covered in the documentation, and indeed is something that Hugo does not do, i think it should have been treated like a feature request (albeit one that probably would have been marked "won't fix").  Here is a good treatment of the question ("Is it possible to use template parameters in the content of a post with Hugo") with alternatives / workarounds on Stack Overflow:

https://stackoverflow.com/questions/42023687/how-to-use-template-parameters-in-page-content-in-hugo

**Comment by bep** [comment]
>Because this question is not covered in the documentation, and indeed is something that Hugo does not do, i think it should have been treated like a feature request 

We do support it, and it is covered in the documentation. Use the forum for further questions, please.

**Comment by ctron** [comment]
> > Because this question is not covered in the documentation, and indeed is something that Hugo does not do, i think it should have been treated like a feature request
> 
> We do support it, and it is covered in the documentation. Use the forum for further questions, please.

Maybe a pointer to the correct spot in the documentation would be helpful then.
