### ISSUE TITLE
Hugo builts XML instead HTML

### ISSUE THREAD

**Issue by sredXNY** [spf13/hugo#3343]
Hi, I have a wordpress project that I am trying to pass to Hugo using the **wordpress-to-hugo** plugin, the plugin generated me a .zip file with this estructure:

- -22.2
- -categories
- -contact form
- -front page
- -listing-details
- -post
- -sample-page
- -search-page
- -search-results
- -wp-content
- -config.yaml (file)

As far as I know, Hugo needs the _content_ folder to generate the views, so I moved all the folders to a folder called content, inside the same directory, so I have somehting like:

- content
- config.yaml

I executed Hugo and I get: 
http://prntscr.com/ewhjg7

Now Hugo generated a public folder with a bunch of contents, but all of them are *.xml files and not *.html. I started the server using `hugo server -w -D` but then in the browser I see nothing, I opened localhost:1313 but it doesn't show anything. What am I missing?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
