### ISSUE TITLE
Log WARNING only on unknown /data files

### ISSUE THREAD

**Issue by jurb** [spf13/hugo#3361]
After updating from 0.17.x to 0.20.2, I get the error `: Data not supported for extension '' read data from Icon` when trying to run `hugo` or `hugo server`. This is strange, since I don't use any data feature that I know of, don't know what I'm to make of the `Icon` part, and my production company web site built fine under 0.17.x.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jurb** [comment]
@bep Thanks for answering so quick. I did ask my question in the forum, and got a reply that I have probably something in the `data` dir that doesn't end in .json, .csv, etc.

Now, I *do* think this is a bug, since the culprit is the hidden MacOS file `Icon`, which is automatically generated by finder. Previous versions of hugo ignored this file, but now it doesn't anymore.

**Comment by bep** [comment]
w

**Comment by Sangdol** [comment]
Thanks for reporting, @jurb! Thanks for fixing, @bep!
