### ISSUE TITLE
0.20.2: showing blank page when visting /section/ even if there's an index.md in that directory

### ISSUE THREAD

**Issue by qzio** [spf13/hugo#3373]
#### Note: I Tried to search before creating this issue but could not find a relevant issue reported. Please close as duplicate if I'm mistaken.

On 0.20.2 when there is an `index.md` file or similar in a `section/` directory, and serving hugo using `hugo server` and visiting `/section/` a blank page is shown instead of the content.

This can be reproduced using ie https://themes.gohugo.io/material-docs/ 's exampleSite.

I've reverted to 0.20.1 for now, where this works as documented.

**Comment by qzio** [comment]
during some more testing, I discovered that this is not easily re-producable...

**Comment by qzio** [comment]
Ok, it doesn't work with 0.20 or 0.20.1 either, but works in 0.19

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
