### ISSUE TITLE
Filename change in Hugo 0.20.3 binaries

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3385]
They are now prefixed with "v" ... and I did not notice it.

See https://github.com/goreleaser/goreleaser/issues/210

**Comment by tombennet** [comment]
Attempting to deploy 0.20.5 with Netlify throws an error due to the renamed binary, even with a cleared build cache - is this related to #3385? Apologies if not. Log below.

8:50:51 PM: Installing Hugo 0.20.5
8:50:53 PM: Cleaning up docker container
8:48:09 PM: Error running command: Build script returned non-zero exit code: 1
8:50:54 PM: Error running command: Build script returned non-zero exit code: 1
8:50:54 PM: Finished processing build request
8:50:53 PM: Error during Hugo 0.20.5 install: error renaming /opt/build/cache/.binrc/binaries/spf13/hugo/v0.20.5/binrc-302612769/hugo_0.20.5_linux_amd64/hugo_0.20.5_linux_amd64 to /opt/build/cache/.binrc/binaries/spf13/hugo/v0.20.5/hugo: rename /opt/build/cache/.binrc/binaries/spf13/hugo/v0.20.5/binrc-302612769/hugo_0.20.5_linux_amd64/hugo_0.20.5_linux_amd64 /opt/build/cache/.binrc/binaries/spf13/hugo/v0.20.5/hugo: no such file or directory

**Comment by bep** [comment]
@tombennet I have notified Netlify about the change, but they haven't got to updating their scripts. I kind of did not think about this side effect, but we had to do this to get away from the unmaintained `goxc` as a build system. And it is much cleaner this way.

So from Hugo >= 0.20.3, the binary inside the archive is just named `hugo` (or `hugo.exe` on Windows.) 

/cc @biilmann

**Comment by tombennet** [comment]
Ok cool, makes sense. Thanks @bep @biilmann
