### ISSUE TITLE
Add Drupal import

### ISSUE THREAD

**Issue by rajibmp** [spf13/hugo#339]
I saw the section in Documentation which says about migrating from Jekyll, but I am more curious about importing my old blog from Drupal. I have xml file for all the things I need, I can change it to YAML, JSON, whatnot if necessary, but is there any easy way to import these files without losing structure.

**Comment by rickb777** [comment]
On a related topic, I wrote a Drupal export tool. https://bitbucket.org/rickb777/drupal2hugo

**Comment by rajibmp** [comment]
@rickb777  :+1:  it'd be great if you could also write bit more documentation part how to use it.

**Comment by anthonyfok** [comment]
Status update:

@digitalcraftsman has kindly compiled a list of Hugo migration tools, and documented them at http://gohugo.io/tools/. See his Pull Request #1423 for more information.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
