### ISSUE TITLE
Feature request: Module for user reviews

### ISSUE THREAD

**Issue by arikroc** [spf13/hugo#3461]
So that a page could have

isReviewable: true
overallRatingOutOf: 5
reviewQuestions: ['What did you like about the product?']

and then Hugo would add a form for collecting reviews with those questions, and a way to display them on the page.

i.e.

`<span itemprop="ratingValue">4</span>/<span itemprop="bestRating">5</span>`

I realize this is somewhat less practical without a database, but I'm curious what the maintainers think or if there's another project more suited to this

**Comment by rdwatters** [comment]
I think what you are asking for is reallt more in the realm of a dynamically generated site.


OR...what you're asking for is already doable with front matter and templating (assuming the author of the review is the author the content file)....

Hugo doesn't really collect information because it's a *static* site generator, but perhaps there is an embeddable JS service for this somewhere?

**Comment by arikroc** [comment]
Good point. I think you're right - an embeddable JS service is probably the best bet for this. (or a dynamic site, or manually doing it with static files/templates)
