### ISSUE TITLE
Can't put irc:// links in configuration menu

### ISSUE THREAD

**Issue by krig** [spf13/hugo#347]
Linking to irc channels in a menu option doesn't work (the link gets stripped).

Example (TOML):

[[menu.main]]
name = "IRC: #golang at freenode"
url = "irc://irc.freenode.net/#golang"

**Comment by anthonyfok** [comment]
Just a quick note that a solution has been found by the use of template.HTMLAttr and a new "safeHtmlAttr" action.  For example, when the relevant code has been added to Hugo, we may replace

    <a class="" href="{{ .Url }}">...</a>

with

    <a class="" {{ printf "href=%q" .Url | safeHtmlAttr }}>

and the irc:// link would work.

Still working on the documentation.  Will commit tonight or tomorrow.  :-)

**Comment by krig** [comment]
:+1:

**Comment by anthonyfok** [comment]
After reading the html/template docs more carefully and searching for similar functions, it turns out there is a template.URL that I kept missing, so we can do a `safeUrl` too like this:

    <a href="{{ .Url | safeUrl }}">...</a>

which is more compact than `<a {{ printf "href=%q" .Url | safeHtmlAttr }}>`, though I suppose someone will find use other uses for `safeHtmlAttr` sooner or later.  Will add `safeUrl` in another commit.

There are actually [template.JS](http://golang.org/pkg/html/template/#JS) and [template.JSStr](http://golang.org/pkg/html/template/#JSStr) too, which we may use for new `safeJs` and `safeJsStr` too in case anyone needs them.

**Comment by anthonyfok** [comment]
Hello @krig, @tatsushid:

After much consideration, I have decided to disable `safeHtmlAttr` template function that @tatsushid has kindly contributed, and have instead promoted the simpler `safeUrl` for use cases like the one described by @krig in this issue report.

What happened is that when I was trying to write the documentation for these new template functions, I struggled to think of any use cases of `safeHtmlAttr` aside from this one which is better served with `safeUrl`.  I have then decided to disable `safeHtmlAttr` for the time being, until it becomes indispensable for certain use cases.  Ditto for the yet unimplemented `safeJs` and `safeJsStr` whose functionality the underlying Go html/template has already provided.

(Yes, I am wary of potential security issues with `safeHtmlAttr`, `safeJs` and `safeJsStr`, especially when there is currently no demand for them, at least not yet.  May be in the future.)

Thank you for your understanding.

**Comment by anthonyfok** [comment]
And here is the documentation for `safeUrl` (new in the upcoming v0.13 release).  Thank you @krig for your wonderful example, which I have shamelessly borrowed.  :-)

----

### safeUrl
Declares the provided string as a "safe" URL or URL substring (see [RFC 3986][]).  A URL like `javascript:checkThatFormNotEditedBeforeLeavingPage()` from a trusted source should go in the page, but by default dynamic `javascript:` URLs are filtered out since they are a frequently exploited injection vector.

[RFC 3986]: http://tools.ietf.org/html/rfc3986

Without `safeUrl`, only the URI schemes `http:`, `https:` and `mailto:` are considered safe.  All other URI schemes, e.g.&nbsp;`irc:` and `javascript:`, get filtered and replaced with the `ZgotmplZ` unsafe
content indicator.

Example: Given a site-wide `config.toml` that contains this menu entry:

    [[menu.main]]
        name = "IRC: #golang at freenode"
        url = "irc://irc.freenode.net/#golang"

The following template:

    <ul class="sidebar-menu">
      {{ range .Site.Menus.main }}
      <li><a href="{{ .Url }}">{{ .Name }}</a></li>
      {{ end }}
    </ul>

would produce `<li><a href="#ZgotmplZ">IRC: #golang at freenode</a></li>` for the `irc://…` URL.

To fix this, add ` | safeUrl` after `.Url` on the 3rd line, like this:

      <li><a href="{{ .Url | safeUrl }}">{{ .Name }}</a></li>

With this change, we finally get `<li><a href="irc://irc.freenode.net/#golang">IRC: #golang at freenode</a></li>` as intended.

**Comment by dimo414** [comment]
@anthonyfok as a usecase for safeHTMLAttr, I'm trying to create a shortcode for links with additional attributes, e.g. `rel="nofollow"`, `target="blank"`, etc. and stumbled upon this bug (after learning about the obtuse [`zgotmplz`](http://stackoverflow.com/q/14765395/113632) message) which suggests calling `template.HTMLAttr`.

You could argue that instead I should create separate shortcodes for each of these use cases, which will be my solution for now, but it certainly would have been faster if `template.HTMLAttr` were available.

PS could you update the "Disabled" comment in template_funcs.go to reference this issue?  I had to dig through the blame history to find this.

**Comment by anthonyfok** [comment]
@dimo414 Sorry, I missed your message from 2015-07-26 and didn't see it until today when I saw PR #2234 by @webguerilla who kindly enabled `safeHTMLAttr` for us.  This has now been merged into `master` (v0.17-DEV).

(My apologies to @tatsushid for not letting `safeHTMLAttr` in sooner.  Looking back, I was too paranoid a year and a half ago.)
