### ISSUE TITLE
reStructured native code format

### ISSUE THREAD

**Issue by renich** [spf13/hugo#3562]
Hello,

reStructured is supported, but, if I try:
```
.. code:: bash

    echo "hello, world!"
```
It doesn't work. Still, this gets generated:

```
<pre class="code bash literal-block"><span class="name builtin">echo</span> <span class="literal string single">'Hello, world!'</span>
</pre>
```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
