### ISSUE TITLE
plugin idea

### ISSUE THREAD

**Issue by ghost** [spf13/hugo#369]
am getting the hang of hugo.

we have lots of binary format stuff. 3D models, images etc
i often setup so that these non web file types are converted into web friendly type.
for example sketchup model i convert to webgl and threejs
inkscape i convert to png often

i was wondering if anyone had any thoughts about a general way to allow hugo to be told when it finds a file extension type, to call a shell extension. It could all be done with configs, and other people just write shell extensions they need for the conversions have they see fit.

what you you think ??

**Comment by MiCHiLU** [comment]
How about Pingo? https://github.com/dullgiulio/pingo

**Comment by digitalcraftsman** [comment]
I've seen something similar called [Pie](https://github.com/natefinch/pie) written by @natefinch. Regardless which package could be used it seems that an RPC-based API could be an alternative to an restful API.

**Comment by tslater** [comment]
+1 for pingo or pie. I want to do some automatic image resizing and spriting. It would be great if I could do something through hugo.

**Comment by ringods** [comment]
Another plugin system with a proven track record:

https://github.com/hashicorp/go-plugin

This plugin system is used in a number of the Hashicorp tools: Packer, Vault, Terraform.

Credits to @mitchellh.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
