### ISSUE TITLE
Page.FileName is handled inconsistently

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#384]
AFAICT, when _running_ Hugo, Page is only ever given the base filename (foo.md).  In tests, Page is usually given a directory and filename (section/foo.md).  Some of the code seems to assume that filename only has the base name, not the full path, for example pageToPermalinkFilename, but some of the code expects the filename to have the full path, like Page.guessSection.  This causes problems... if you change testdataPermalinks to include a test that tests :filename, it'll fail, because it renders the filename as the full path, minus extension.

I could fix pageToPermalinkFilename to only use the base filename, but I wonder if it might be better to only store the base filename in Page.FileName instead, if there aren't any places in production where we actually put the full path there.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
