### ISSUE TITLE
permalinks :slug behaves unexpectedly

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#385]
In page metadata, the if the slug is set, it is the last part of the page's URL, otherwise the name of the file is used as the last part of the URL.

However, if you set a permalinks format for a section, :slug behaves differently.  It is either the slug, or the title.  There's no way to replicate the slug-or-filename behavior of the page metadata with permalinks.  That's really too bad, because I like the slug-or-filename behavior, and almost never want my title as the slug.

IMO, :slug behaves incorrectly.  I think it should mimic the behavior of the page metadata, where it is slug-or-filename.  However, I would imagine that one can't just change the behavior of :slug, otherwise we're all-of-a-sudden change some peoples' urls on them.

For now, I suggest a :slugorfile token that works the way the metadata slug works.

I'm not sure how Hugo handles deprecation/changing of features, but this is how I'd do it, if you eventually want to make :slug work like :slugorfile, and give everyone as much chance as possible to not have their stuff broken.

in v0.12, add :slugorfile, and add a token called :slugortitle, which works identically to the way :slug works now.  If someone is detected as using :slug, log a warning that :slug will change behavior in the next release, and they should change to using :slugortitle before upgrading, to maintain behavior.  
in v0.13, make :slug work like :slugorfile, and add a deprecation warning to :slugorfile that it should be changed to :slug, because it'll be removed in the next release.  
in v0.14 remove :slugorfile

I'm happy to submit a branch with :slugorfile and, if desired, the rest of the deprecation stuff... but I'd at least like to see a way to mimic the slug-or-filename behavior of the page metadata.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
