### ISSUE TITLE
Allow flag for natural table of content anchor texts

### ISSUE THREAD

**Issue by matsko** [spf13/hugo#387]
I'm in the process of switching my blog over to Hugo from Jekyll and one of features that my current website has is my own, custom table of contents. But now since I'm using Hugo, I can simply use the `{{ .TableOfContents }}` markdown template function. It works great, but I feel that the generated "#toc_X" anchor tags are not good for SEO (especially for articles that had different tags from before).

What would be really nice is to have the anchor URLs be generated as a lowercase, hyphenated version of the title text. Something like:

```
# Welcome to my new blog article
--> website.com/posts/page#welcome-to-my-new-blog-article
```

**Comment by bep** [comment]
@halostatue what is the status of this?

**Comment by halostatue** [comment]
Those were both merged in 2014. Beyond that, I don’t know. In theory, it should work.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
