### ISSUE TITLE
Exclude dirs list

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#416]
I would like to be able to tell Hugo not to generate list directories for some data, because it's not pages for general content, but just content for injecting elsewhere.  Ideally I could list whatever dir I want and if Hugo would otherwise generate something for that dir, don't.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
