### ISSUE TITLE
Allow to inhibit rss creation

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#437]
I'd like to be able to prevent creation of RSS files for specific taxonomies. Right now, the files are always there - even if I provide an empty template for it, I end up with an XML file containing just 

``` xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
```

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
