### ISSUE TITLE
HTML compression feature

### ISSUE THREAD

**Issue by tiby312** [spf13/hugo#456]
Would be cool if there were an option to compress the HTML and maybe CSS too to remove spaces and new lines, and maybe remove comments!

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
