### ISSUE TITLE
support for using reST

### ISSUE THREAD

**Issue by gour** [spf13/hugo#472]
Besides AsciiDoc, some people would like to have support for writing posts using reStructuredText...

**Comment by anthonyfok** [comment]
Actually, reST support has been around for a long time now: v0.10, v0.11 and v0.12 have them.  The documentation actually mentions an experimental support for reStructuredText, and while its usage is undocumented, it has worked quite well actually.

For example, try `hugo new post/hello.rst`, and then do this:

    $ hugo_0.12_linux_amd64 
    ERROR: 2015/01/21 exec: "rst2html.py": executable file not found in $PATH
    ...

It is trying to call `rst2html.py --leave-comments`, and would show the above error if it cannot find rst2html.py in the `$PATH`.  Once you have `rst2html.py` installed, it would likely render your reST pages correctly.

It is only quite recently (November 2014?) that reStructuredText support disappeared due to a refactoring-in-progress, but the underlying code has always been there.

I have just added some code (mostly copy and paste) in 19c52ab0b5a5a8f89d43dcc2e2a15e2f53170017 to re-enable reST support.  The latest version also looks for `rst2html` too: On Debian and Ubuntu systems at least, `rst2html` is installed in `/usr/bin/rst2html` without the `.py` extension, so I made that little change.

@gour and @solutionroute, could you please give either Hugo v0.12 or the latest v0.13-DEV (`go get -v`) a try, and see if it works for you?  Please give us feedback on this feature: What works, what doesn't, etc., so we can better document this and make improvements if possible so it is no longer "experimental".  :-)  Thanks!

**Comment by tatsushid** [comment]
FYI, there is a pure Go implementation of restructured text parser at https://github.com/demizer/go-rst. Now it's very alpha status but worth incorporating it into Hugo in the future.

**Comment by anthonyfok** [comment]
For historical interest, the initial code for reST support was first contributed by Sam Kleinman (@tychoish) in commit 431fa0e2d75ca8ddd145bd5db20e50a160772577 on 2013-07-06, and a few reST fixes on 2013-07-09 (so that is before v0.8!), though it is only in v0.10 and above that are working for me.

**Comment by anthonyfok** [comment]
@tatsushid wrote:
> FYI, there is a pure Go implementation of restructured text parser at https://github.com/demizer/go-rst. Now it's very alpha status but worth incorporating it into Hugo in the future.

Awesome!  Good to know!  :clap:

**Comment by gour** [comment]
@anthonyfok I did play a bit with reST support after installing rst2html5 on my machine.

Simple, small document worked, but when I was try with Pandoc' [README](http://pandoc.org/demo/README) I had to cut lot of stuff in order to be able to get any output.

However, even running rst2html on the same file was problematic. :-)

**Comment by anthonyfok** [comment]
Hi @gour, sorry for the late reply.  The current Hugo code uses exactly `rst2html` to render reST files, so whatever `rst2html` can or cannot render, Hugo can or cannot either.

Does `rst2html5` render Pandoc's [README](http://pandoc.org/demo/README) file correctly?  Are you suggesting that we look into using *rst2html5* and/or *Pandoc* to render reStructuredText documents instead?

**Comment by anthonyfok** [comment]
Wait a second, the Pandoc README file is not written in reST, but rather in Pandoc's own Markdown format!  :-/

**Comment by anthonyfok** [comment]
Well, since Hugo has been secretly supporting reST for a few releases now, and that secret is now in the open, the goal of this issue is accomplished.  An experimental yet usable implementation relying on `rst2html`.  Closing this issue.

A new issue #1436 has been open to track the future support for native Go implementation of reStructuredText (reST).  Any volunteers?  :wink:
