### ISSUE TITLE
Provide warnings instead of silently ignoring config file sections when --verbose flag is used

### ISSUE THREAD

**Issue by quoha** [spf13/hugo#589]
It would be helpful if the "--verbose" flag caused Hugo to provide a warning that custom data needs to be a child of the Params section in the configuration file.

Example: If I want to add a parameter "skin" that tracks a value, the following won't work:

```
[skin]
    show_generated_by = true
```

Instead, I have to add

```
[Params.skin]
    show_generated_by = true
```

It took me a few times through the documentation to figure out that .Site.Author is special, so Hugo will accept `[author]` and do nice things with it. All other custom values to be required to be children of Params.

The other option would be to automatically add the sections to .Params, but that could be confusing for simple typos.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
