### ISSUE TITLE
Feature: update-timestamp command

### ISSUE THREAD

**Issue by jeffreyrogers** [spf13/hugo#648]
I'm new to Hugo, but have really been enjoying how simple everything is. It seems to work much better with my development workflow than any other static site generator I've tried.

One feature I find myself wanting is the ability to update the timestamp on drafts. Often I'll start a new draft of something and won't finish it until much later, at which point the original timestamp is significantly out of date. Of course, I can edit them by hand, but I think a command like `hugo update-timestamp post/file-to-update.md` would be simpler/less error prone. Basically this command would just scan the metadata and replace the old date with a current one.

If this is something others feel would be worthwhile to have as well, then I can work on it. I haven't used Go before but it looks like it would be pretty easy to pick up and I think this change is relatively self-contained.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
