### ISSUE TITLE
Add support for shortcodes in html files

### ISSUE THREAD

**Issue by blg002** [spf13/hugo#674]
`{{% figure src="/assets/img/foo.png" %}}` is outputting `<div>HUGOSHORTCODE-1</div>` in a static content page (/content/about/index.html). However it seems to work fine in all my blog (archetype) posts?

```
$  hugo version
Hugo Static Site Generator v0.13-DEV buildDate: 2014-11-24T18:04:18-05:00
```

It worked fine in v0.12-DEV

**Comment by radomirml** [comment]
+1 for enabling shortcodes in html content files. I have a use case where internal Confluence documentation space is exported to a set of html files that I want to process as a part of a static site created using Hugo. Due to lack of shortcodes ("relref" specifically) links between documentation pages are broken. (I'm still new with Hugo so not sure if there's another way to do this.)

**Comment by bep** [comment]
@spf13 any fresh thoughts on this one?

**Comment by grex84** [comment]
+1 for enabling shortcodes in html content files. 

In my particular case I have created a drag and drop content builder which writes the generated html file to the content directory. Instead of generating the html for the object types (images, calendar, etc) inside the content file i would like that only their shortcodes are used and hugo will process them. 

If any object's html needs to be changed all i need to do is modify the shortcode html rather than regenerating all content files through the builder with the newly applied changes. 

Can anyone confirm that changing the file extension to .md would be enough to serve case?

Thanks

**Comment by bep** [comment]
@spf13 any fresh thoughts on this one?

**Comment by Dieterbe** [comment]
> An easy way to achieve this functionality today would be to name the file about.html.md. Then the markdown processor would hand it and since html is valid markdown it would just work.

unfortunately it's not quite this easy.  I'm transitioning from pyblosxom to hugo, and copying my posts into `content/post/<file>.<ext>`.  (with modified header to be in hugo format of course), if i use .md as extension, then it doesn't just treat html as html; it treats html as html and also interprets as markdown. meaning if you have something like `<br/>\n`, the `<br/>` will be applied because it's html but *also* the newline gets converted to `<br/>`. worse, 2 `<br/>\n` become empty paragraphs (`<p></p>`), this creates way too much whitespace

so anyway, big +1 to supporting shortcodes in html content, so i can store my posts as html (but have processing applied for syntax highlighting etc)

**Comment by bep** [comment]
OK, mr @spf13 says this is a good idea, so I'm adding shortcode support for HTML files ... Now.

**Comment by bep** [comment]
This is now added. Good if someone could take this for a spin ...

**Comment by Dieterbe** [comment]
works for me. all my html posts have syntax highlighting now :) thanks!

**Comment by heyarviind** [comment]
I am still confused, can you please explain how to use shortcodes in HTML file which is in the content folder.

I am using .html files in content folder instead if .md files in content folder

**Comment by andradei** [comment]
I'm trying to use a custom shortcode on my home page, defined in file `{my-project-dir}/layouts/index.html` without success.

```
parse failed: template: index.html:7: unexpected "<" in command
```

**Comment by computator** [comment]
The documentation for this is rather unclear as to if shortcodes are supported in anything besides markdown. I was glad to find this issue stating that yes, they in fact are.

In particular I was wanting to use `ref` and `relref` in html pages. I was unable to find any other method for dynamically setting the proper resolved urls for links in html templates or content pages. It wouldn't be that practical to have to redo all the links to a particular page if the url was changed in the target page's metadata.
