### ISSUE TITLE
Official docker image for Hugo

### ISSUE THREAD

**Issue by srid** [spf13/hugo#709]
Would you be open to me contributing a Dockerfile so as to automatically create official docker images (via hub.docker.com as a 'trusted' image) based on release tags of this repo?

I'm also thinking that perhaps the `hugo new site --with-docker` command can be made to include a `Dockerfile` that looks like:

```
FROM gohugo/hugo

ADD . /app
ENV HUGO_THEME hyde-x
RUN hugo -t ${HUGO_THEME}
```

where my Dockerfile would define the `gohugo/hugo` image. I would be basing it off something like https://github.com/srid/www.srid.name/blob/master/Dockerfile

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by bep** [comment]
This issue is old and stale, and no one has shown enough interest in it to make it happen. I will close this now, and by that, I'm not saying that this "isn't worth adding to Hugo", I'm just saying that anyone that really wants this, will have to create a new tracking issue for any future Pull Request that solves this issue.
