### ISSUE TITLE
https protocol used with localhost

### ISSUE THREAD

**Issue by nathany** [spf13/hugo#758]
As @andrelima [mentioned here](https://github.com/spf13/hugo/issues/544#issuecomment-58817004):

`{{ .Site.BaseUrl }}` results in `https://localhost:1313/` if the baseurl defined in config uses https.

In this case it probably makes sense to override the protocol to http along with the host.

A work around (in some cases) is just to use relative paths instead of `{{ .Site.BaseUrl }}`.

I just upgraded hugo to latest (fb1b795d59b3c6d5d74df3a69b4026574b6dd5fa) and this issue remains.

**Comment by dsimmons** [comment]
Ran into this locally literally 10 minutes ago :smile: 

FWIW, I too was on latest.

**Comment by nathany** [comment]
@dsimmons Happy new year, securing all the things. :smile:

**Comment by nathany** [comment]
The current behaviour was intentional based on the specs: https://github.com/spf13/hugo/commit/fb82f00f9d0341a976241c9c062304adb43b3794

But it was a fix for #544.

Petition for change? Or maybe I should figure out how to do a self-signed cert for localhost.

@spf13 Happy to help make some changes once I know what you would like to see.

**Comment by dsimmons** [comment]
@nathany, Happy New Year! :fireworks: :tada: :balloon: 

Yeah, I was a bit torn on this one as to what the appropriate fix should be. The self-signed cert approach was my first thought, but at a higher level, it feels kind of silly/unnecessary to have to do just for the sake of "not breaking" the development server.

I assume your use case is similar @nathany , but just to provide a little more detail for those that are trying to understand why I don't just use my SSL cert locally (or in other words, would need to self-sign):
- I'll be deploying to static hosting (S3, Github pages, etc...)
- By the nature of its simplicity and/or lack of sensitivity, I don't need a complicated end-to-end HTTPS setup with my own certs installed. Instead, I can use something like CloudFlare as a reverse-proxy + CDN and use their Universal SSL option.
- Finally, I've opted to use relative URLs everywhere so that, among other reasons, this shouldn't be a problem in theory.

**Comment by nathany** [comment]
I can write up a patch and see what happens.

Personally I don't see any reason to run the Hugo server securely during development. There's hardly any reason to run a static site securely in production. Perhaps the occasional mailing list signup, maybe a bit of PageRank, and to prevent ISP-injected garbage. Mostly I'd just like more of the web to be secure, so I'm trying to set a good example. :grinning: 

@dsimmons Interesting setup. I contemplated CloudFlare but didn't really want to change my DNS provider. I've been using S3 as an website origin (which doesn't support HTTPS) with CloudFront and a custom cert. I'm not entirely in love with the setup, mainly cache invalidation.

**Comment by spf13** [comment]
I agree with the recent comments. There's no reason to support https in hugo server. We absolutely should support it in baseUrl for link generation.

**Comment by nathany** [comment]
@spf13 cool. see #760
