### ISSUE TITLE
RSS feeds do not validate

### ISSUE THREAD

**Issue by snej** [spf13/hugo#789]
The RSS 2.0 feeds generated by Hugo do not validate. For example, look at [feedvalidator.org's report on the spf13.com blog](http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fspf13.com%2Fpost%2Findex.xml).

```
Sorry
This feed does not validate.

line 9, column 4: Undefined channel element: author [help]

    <author>Steve Francia</author>
    ^
line 18, column 27: Invalid email address: Steve Francia (15 occurrences) [help]

      <author>Steve Francia</author>
                           ^
line 165, column 44: pubDate must be an RFC-822 date-time: Tue, 01 Jul 2014 00:00:00 UTC (13 occurrences) [help]

      <pubDate>Tue, 01 Jul 2014 00:00:00 UTC</pubDate>
                                            ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

Your feed appears to be encoded as "utf-8", but your server is reporting "US-ASCII" [help]

line 110, column 0: description should not contain relative URL references: /templates/list (14 occurrences) [help]

</description>
line 1619, column 0: Non-html tag: figcaption (4 occurrences) [help]

        &lt;img src=&#34;/media/pingdom-old.png&#34; alt=&#34;Pingdom of for ...
```

I spent several years working on a feed reader at Apple, and malformed feeds were the bane of my existence. It's not hard to check that you're generating a valid feed; please do so, for the sake of the feed readers!

**Comment by anthonyfok** [comment]
Thank you for reporting this issue, @snej.

For those who are interested, here is what I have learned thus far.  According to the [RSS 2.0 Specification](http://www.rssboard.org/rss-specification):

 1. `<channel>` does not have an `<author>` element, but `<managingEditor>` and `<webMaster>` are available.
 2. `<managingEditor>`, `<webMaster>` and `<author>` all expect an email address followed by an optional full name in parentheses, e.g. `geo@herald.com (George Matesky)`
 3. `<pubDate>` etc. must strictly adhere to [RFC-822 Date and Time Specification](http://www.w3.org/Protocols/rfc822/#z28), which accepts `UT`, `GMT` or `Z` as valid and equivalent timezones, but not `UTC`.

`{{ .Date.Format "MST" }}` would generate `UTC` when no time is given in `date` in the front matter, e.g. `date = "2015-01-12"`.  Nowadays, however, `hugo new post/test.md` would automatically put in the current date/time with timezone, e.g. `date = "2015-01-12T14:33:38-07:00"`, so most users won't see this bug.  However, with `TZ=GMT hugo new post/test.md`, the resulting timestamp would be `date = "2015-01-12T14:33:38Z"`, which becomes `UTC` in the feed XML file.

I have modified the rss.xml template in `hugo/tpl/template_embedded.go` accordingly, committed as 700c2b8.  Now, the [W3 Feed Validation now comes out clean](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fanthonyfok.org%2Findex.xml) for the [RSS feed on my simplistic personal website](http://anthonyfok.org/index.xml).

However, the other errors aren't as trivial:
<blockquote>
<ul>
<li><p><span class="message">Your feed appears to be encoded as "utf-8", but your server is reporting "US-ASCII"</span> [<a title="more information about this error" href="docs/warning/EncodingMismatch.html">help</a>]</p></li>
<li><p><a href="http://validator.w3.org/feed/check.cgi?url=spf13.com#l31">line 31</a>, column 0: <span class="message">description should not contain iframe tag</span> (6 occurrences) [<a title="more information about this error" href="docs/warning/SecurityRisk.html">help</a>]</p></li>
<li><p><a href="http://validator.w3.org/feed/check.cgi?url=spf13.com#l207">line 207</a>, column 0: <span class="message">description should not contain relative URL references: <code>/templates/list</code></span> (4 occurrences) [<a title="more information about this error" href="docs/warning/ContainsRelRef.html">help</a>]</p><blockquote><pre>&lt;/description&gt;<br /></pre></blockquote></li>
<li><p><a href="http://validator.w3.org/feed/check.cgi?url=spf13.com#l2407">line 2407</a>, column 0: <span class="message">description should not contain script tag</span> (3 occurrences) [<a title="more information about this error" href="docs/warning/SecurityRisk.html">help</a>]</p></li>
</ul>
</blockquote>

It would seems that to get feeds of pages with extras like `<iframe>` and `<script>` to validate, tags like these will need to be filtered out, and all relative URL references will need to be converted to full URLs, a kind of sanitization run, so to speak.

I am too new to Go and to the Hugo team to tackle that.  Should something like this (probably an enhancement rather than a bugfix) be added to Hugo?  Please discuss.  :-)

**Comment by snej** [comment]
The UTF-8 vs ASCII issue is a well-known thorny one. It's an HTTP-level problem, so it's really outside the purview of a static site generator. The deploying site has to do something to set the correct Content-Type header when serving the file. It can be done with a `.htaccess` file if the server is Apache, but there's no general fix.

The limits on the `description` contents … those aren't really part of the RSS "spec" (such as it is, cough) either. It's not good for security reasons to put those in a data format that's going to be rendered by a feed reader, but in reality, any feed reader has to sanitize the article content itself because it can't trust the feed generator not to put in something dangerous. So it really won't make a difference whether you put those elements in or not; they'll get stripped by any well-written reader.

**Comment by snej** [comment]
FYI, the feed generated for my website by Hugo v0.12 has different [validation errors](http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fjens.mooseyard.com%2Findex.xml) that aren't listed above:

```
line 5, column 6: Unexpected uri attribute on generator element [help]

      <generator uri="https://hugo.spf13.com">Hugo</generator>
      ^
line 10, column 4: Undefined channel element: updated [help]

    <updated>Sun, 11 Jan 2015 21:25:58 PST</updated>
    ^
line 758, column 2: Missing channel element: description [help]

  </channel>
```

**Comment by anthonyfok** [comment]
> FYI, the feed generated for my website by Hugo v0.12 has different validation errors that aren't listed above

Yes, indeed, though there is currently no mechanism to fix bugs for old stable release, i.e. no v0.12.1 would be made to fix bugs, so we will have to look forward to v0.13, which will hopefully be released soon.

**Comment by anthonyfok** [comment]
> line 110, column 0: description should not contain relative URL references: /templates/list (14 occurrences)

It turns out other users have reported this specific problem in #725 and #728 too!  And already fixed by the reporter @popthestack in commit 7dacc99 22 days ago!  (Thank you @popthestack!)  So one more step towards perfect RSS feed output!  :-)

**Comment by snej** [comment]
:grinning: :+1:

**Comment by bjornerik** [comment]
There is some work involved getting these all valid.

On my site, it complains about script and iframe tags ...

**Comment by snej** [comment]
@bjornerik: As I mentioned above, the complaints about the [escaped] tags used in the HTML descriptions are pretty minor. Technically a feed's descriptions shouldn't contain "unsafe" HTML, but in the real world it happens and the feed readers can protect themselves against it in one way or another.

**Comment by anthonyfok** [comment]
@snej: Thanks for the note!

Though there is always room for improvement in our strive for perfection, so I think it is likely that we will keep this issue open, but leaving it as a milestone for some future release beyond v0.13, say, v0.50?  :-)

**Comment by k4rtik** [comment]
Unsure what remains to be done with RSS validation, most of the validation errors seem to have been fixed with various commits referenced in this issue.

Among my 4 primary feeds at techglider.in, I see a warning with just one as follows, but all 4 **do** validate on feedvalidator.org:
```
This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 178, column 0: description should not contain embed tag [help]

&lt;p&gt;&lt;embed type=&#34;application/x-shockwave-flash&#34; src=&#34;htt ...
```

As @snej mentions, these warnings should be ignorable from the perspective of hugo development.

**Comment by bst27** [comment]
I also had to replace the `{{.URL}}` with `{{.Url}}` in the feed

**Comment by bep** [comment]
@bst27 what do you mean by having to replace URL with Url? Url is depracated in 0.14, but shouldn't be relevant for 0.13... Unless you use 0.14 docs in 0.13?

**Comment by bst27** [comment]
I copied the given code from the [docs](https://gohugo.io/templates/rss/#the-embedded-rss-xml:eceb479b7b3b2077408a2878a29e1320) and saved it in an rss.xml file.

Hugo gives me:
```
ERROR: 2015/04/04 template: theme/rss.xml:11: function "safeHTML" not defined
ERROR: 2015/04/04 Error while rendering section articles rss: html/template: "theme/rss.xml" is an incomplete template
ERROR: 2015/04/04 Error while rendering homepage rss: html/template: "theme/rss.xml" is an incomplete template
```

After removing `safeHTML` Hugo gives me:
```
ERROR: 2015/04/04 Error while rendering section articles rss: template: theme/rss.xml:12:23: executing "theme/rss.xml" at <.URL>: URL is not a field of struct type *hugolib.Node
ERROR: 2015/04/04 Error while rendering homepage rss: template: theme/rss.xml:12:23: executing "theme/rss.xml" at <.URL>: URL is not a field of struct type *hugolib.Node
```

After changing `{{.URL}}` to `{{.Url}}` Hugo builds without error.

**Comment by bep** [comment]
Woopps.

Then some Hugo 0.14 syntax has slipped into the 0.13 docs, sorry for that.

**Comment by bep** [comment]
Is this still the case?

**Comment by bep** [comment]
What is the status on this?

**Comment by bst27** [comment]
I do not use Hugo at the moment so I cannot give you some feedback.

**Comment by dimo414** [comment]
According to both FEED Validator and the WC3 validator Hugo now generates valid RSS feeds.

* FEED Validator: [GoHugo](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fgohugo.io%2Findex.xml), [SPF13](http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fspf13.com%2Fpost%2Findex.xml)
* WC3 Validator: [GoHugo](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fgohugo.io%2Findex.xml), [SPF13](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fspf13.com%2Fpost%2Findex.xml)

Both services point out an encoding issue (UTF-8 vs. ASCII) but it sounds like the servers are misconfigured, not Hugo.
