### ISSUE TITLE
Syncing does not work properly on Windows

### ISSUE THREAD

**Issue by karland** [spf13/hugo#839]
I am testing `gulp.js` in conjunction with `hugo`. I have my source Files in `/src` and `gulp.js` is processing them and putting them at the correct places under `themes/mytheme/. Now I noticed the following with hugo v0.12:

1. `hugo` claims it is syncing my `themes/mytheme/static/css` with `public/css` but it leaves old .css-Files in the `public/css` even though the old source in `themes/mytheme/static/css`is gone. So it is not deleting and therefore really not "syncing".

2. When I am applying changes to the `index.html` `hugo server --watch` picks them up and livereload is displaying them beautifully. However, when I am applying changes to a .css-File, `hugo` outputs:
`Change detected, rebuilding site`
but actually does not. The updated .css-File is not synced into `public/css` and livereload is not displaying the changes. When I am stopping and restarting the server, the update takes place. So it seems that css-Files are only synced when the server is started.

**Comment by anthonyfok** [comment]
Hi @karland,

Thank you for your comments!

2. About Hugo not deleting old files in `public/`: I believe it is a design decision to "copy" and "not delete", to avoid destroying user's data inadvertently.  For example, some users have `hugo` installed on the web server to run automatically to deploy a website after a `git push`.  Some users may have decided to nest a "sub-website" in a subdirectory, or perhaps added some secret `.htpasswd` inside the `public/` directory but not in `static/` because the user does not want these sensitive information in a public repository on GitHub...

    Whatever the reason, automatically deleting something Hugo doesn't recognize is a very risky behaviour, and generally frowned upon by users.  I don't think any other static site generators have ventured down that path either.


2. I believe the CSS LiveReload issue was reported as #490 and subsequently fixed by @bjornerik in commit df489b4712dd59b097de0d2fb84cfac7a013f5cd in September 2014, several weeks after Hugo v0.12 was released.  I highly recommend that you try to build from the latest source of Hugo v0.13-DEV using `go get` as documented in README.md and in http://gohugo.io/overview/installing/.

**Comment by bjornerik** [comment]
The sync issue has been discussed in other issues.

About livereload, please reopen if still an issue with 0.13.

**Comment by karland** [comment]
@bjornerik I have compiled Hugo as suggested and I am now on 

    go version go1.4.1 windows/amd64
    Hugo Static Site Generator v0.13-DEV


Unfortunately, the issue persists. Basically what I am doing is changing the `background` color from the `body`-element from `red` to `blue` for testing purposes in `mystyle.css`. Hugo detects the change:

    Change detected, rebuilding site
    2015-01-27 23:53 +0100
    WARN: 2015/01/27 Unable to locate layout for 404 page: [404.html theme/404.html]
    0 of 1 draft rendered
    0 future content
    0 pages created
    0 paginator pages created
    0 tags created
    0 categories created
    in 20 ms

but neither is Hugo syncing the changed `mystyle.css`into `public/css` nor is livereload displaying the change. When I manually copy the changed `mystyle.css` into `public/css` livereload also does not notice the change. When I refresh manually, the browser updates properly. When I stop the server and restart it, it works fine up until the next change.

**Comment by jaden** [comment]
@karland I was seeing the same behavior and have submitted a pull request that fixes it on Windows. Once it's merged, could you test it as well to make sure it's working for you?

**Comment by bep** [comment]
@karland @jaden's patch is merged now.

**Comment by bep** [comment]
As per @karland' comment in #858
