### ISSUE TITLE
Clarify use of `hugo server` in Quick Start Guide (was "Does hugo work for normal hosting sites?")

### ISSUE THREAD

**Issue by suntong** [spf13/hugo#852]
Does hugo work for normal hosting sites, ie, those sites that offer static html, or dynamic php/mysql hosting? They normally will only give you (s)ftp access. hugo will not work for such home-page hosting sites right?

**Comment by spf13** [comment]
Hugo works especially well on these hosted platforms.

**Comment by suntong001** [comment]
Oh, thanks. In that case, please update either of the following articles, because I only have the impression that *"Hugo contains its own ... web server. Simply run hugo server and Hugo will ... run a server with your content"*.

Hugo Quickstart Guide  
http://gohugo.io/overview/quickstart/

Hugo Installation Guide
http://gohugo.io/overview/installing/

thanks

**Comment by anthonyfok** [comment]
Hello @suntong001!

But it does mention on the very first page of the documentation, i.e. http://gohugo.io/overview/introduction/: 

> Technically speaking, Hugo is a static site generator.

That said, our documentation does always have room for improvement, and welcome any contributions that would improve its clarity and remove obstacles for our newcomers.  Would you like to kindly make the necessary edits and submit a Pull Request?  万分感谢！ :pray:

Welcome aboard!

**Comment by bep** [comment]
More questions? http://discuss.gohugo.io/

**Comment by anthonyfok** [comment]
In light of @suntong001's suggestion, as well as questions like the following popping up on our discussion forum:

 * http://discuss.gohugo.io/t/hugo-website-deployment/388
 * http://discuss.gohugo.io/t/after-using-hugo-server-do-i-need-to-run-hugo-before-deploying/601
 * http://discuss.gohugo.io/t/how-to-upload-my-hugo-blog-from-localhost-to-my-server/709

that are more or less related to URLs with `http://localhost:1313/` not working on a public web server, perhaps some kind of clarification in our docs may help remedy the situation.

For example, perhaps adding phrases like "development server" like on http://jekyllrb.com/docs/usage/ would help.  While `hugo server` is certainly capable on a production server, I would say that 99% of Hugo users would prefer to use Apache, Nginx or Lighttpd to serve their static website.

**Comment by spf13** [comment]
I don't like the term "development server" as it connotes that it's not ready for production usage... as is the case with Jekyll. 

Hugo's server is more than powerful enough for production usage and I know of a lot of people using it as such... especially when using it with more powerful needs or when using it with Docker. 

I agree we need some clarification. People are just so used to wordpress and the like and are not familiar with our new approach to things where server isn't needed (it's just static files).

**Comment by anthonyfok** [comment]
Good point you have there, @spf13.  We should 

About a week ago, I actually answered a question at http://discuss.gohugo.io/t/hugo-website-deployment/388/11 about using `hugo server` as a production web server on port 80:

> `hugo server` runs an actual built-in web server, normally on port 1313, but you may set it to anything, even port 80.  With that, you don't even need to have Apache running, and just run:
>
>     $ sudo hugo server --watch --baseUrl=http://yoursite.org/ --port=80 --appendPort=false
>
> > Note:
> > 1. Run `hugo server -h` to see a description of all these options.
> > 2. `sudo` alert!  Need to be root to serve at port 80.
>
> Running `hugo server` this way, the links will point to "http://yoursite.org/" rather than to "http://localhost:1313/".  Yes, you must specify `--baseUrl` on the command-iine for this use case.  You might want to add `--disableLiveReload=true` too, as otherwise all your webpages will have the LiveReload JavaScript snippet attached, not only for you, but also for all visitors.

I do have a question myself: Did I give the right command?  It actually took me several minutes of reading `hugo server -h` as well as trial and error before I came up with that whole command line, and apparently, I need at least all three of `--baseUrl`, `--port` and `--appendPort` for `hugo server` to work properly as a "production web server".  It was not too trivial to arrive at that to get `hugo server` work like e.g. Nginx, especially its use was not spelled out in the official documentation.

I can't help to think: there must be an easier way to this, perhaps by adding a new option called e.g. `--production` which would use the `baseurl` setting from `config.toml`, and automatically set `--port 80 --appendPort=false` and perhaps `--disableLiveReload=true` too.  What do you think?

**Comment by spf13** [comment]
correct and I agree, we should make a shortcut to make this easier. 

Steve Francia
spf13.com
@spf13

**Comment by Jared-Prime** [comment]
@anthonyfok @spf13 just to clarify: Is the recommendation for the time being to simply specify port 80? Or is there an elegant way to have nginx do a `proxy_pass` to the application running on another port *and* avoid printing port numbers in rendered `href`s?

**Comment by Jared-Prime** [comment]
I think I answered my question by giving another try: `--appendPort=false` works for what I'm looking to do. Thanks!

**Comment by anthonyfok** [comment]
See also #937 
(Hope to find time to work on the documentation in a week or two.)

**Comment by djmattyg007** [comment]
> But it does mention on the very first page of the documentation, i.e. http://gohugo.io/overview/introduction/:

>> Technically speaking, Hugo is a static site generator.

This appears to be the google juice that helped me find hugo, but it was very frustrating to then try and work out how to use hugo as _just_ a static site generator, without the built-in webserver.

Surely I can't be the only one in this situation? I genuinely think the ability to use it as just a generator should be far more heavily emphasised in your documentation.

**Comment by mdhender** [comment]
Would it help to add some text that describes the difference between "hugo server" and plain old "hugo"? Many of the questions that I've seen on the forums boil down to overlooking the lightly-documented hugo-with-no-command command.
------
Web site generators render content into HTML files. Most, like Wordpress,
Ghost, and Drupal, are "dynamic site generators." That means the HTTP
server (which is the program running on your website that the user's
browser talks to) runs the generator to create a new HTML file
each and every time a user wants to view a page.

Creating the page dynamically like this means that the computer hosting
the HTTP server has to have enough memory and CPU to effectively run
the generator around the clock. If not, then the user has to wait
in a queue for the page to be generated.

Nobody wants uses to wait longer than needed, so the dynamic site
generators programmed their systems to cache the HTML files. When
a file is cached, a copy of it is temporarily stored on the computer.
It is much faster for the HTTP server to send that copy the next time
the page is requested than it is to generate it from scratch.

Hugo takes cacheing a step further. All HTML files are rendered on your
computer and then copied to the computer hosting the HTTP server.
Since the HTML files aren't generated dynamically, we say that Hugo
is a "static site generator."

Not running a web site generator on your HTTP server has many benefits.
The most noticeable is performance - HTTP servers are very good at
sending files. So good that you can effectively serve the same number
of pages with a fraction of the memory and CPU needed for a dynamic site.

Hugo has two components to help you build and test your web site. The
one that you'll probably use most often is the built-in HTTP server.
When you run `hugo server`, Hugo renders all of your content into
HTML files and then runs a HTTP server on your computer so that you
can view them.

The second component is used when you're ready to publish your web
site to your HTTP server. Running Hugo without any actions will
rebuild your entire web site using the `baseurl` setting from your
site's configuration file. That's required to have your page links
work properly with most hosting plans.

**Comment by spf13** [comment]
Please add this to the docs. It's fantastic. 

Steve Francia
spf13.com
@spf13

**Comment by mdhender** [comment]
Done. It pushes the section on "How fast" to below the fold. If that's important, then the whole overview should be reorganized with one section for serious hand-holding and the other for those that think they know the basic concepts of operations.

**Comment by moorereason** [comment]
A lot has changed and many things have been rewritten/clarified since the original post.  I think we're good now.
