### ISSUE TITLE
Where do I edit Hugo to fix the wrong output path on Windows?

### ISSUE THREAD

**Issue by ivanjuras** [spf13/hugo#853]
Poor front end dev here, so please be gentle :).

I'm loving Hugo so far, it seems to be just the right tool that I need for my static sites.

However, I'm pretty tired of having to write -s ...path all the time when using the Git terminal, so I was wondering if some of you guys could show me where can I edit the file that has been mentioned (changing a function name) as a hotfix.

The only thing that I have on my PC is a Hugo binary.

**Comment by anthonyfok** [comment]
Hi @ivanjuras, welcome to Hugo!

You might be interested in Dan Hersam's (@jaden) excellent Hugo course on Udemy.  See this thread here:  http://discuss.gohugo.io/t/hugo-course-i-created-on-udemy/620 for the link to the course.

Get it while it is free!  (until January 31)  :-)

As you can see in the videos, we hardly ever use the `-s` option.  Rather, we place the `hugo` executable (or `hugo.exe` if you are on Windows) in a PATH, and we `cd` into the directory of your new Hugo site, and run `hugo` from there.  I think watching Dan's video tutorial will really help you get a sense of the workflow.

**Comment by ivanjuras** [comment]
Hey @anthonyfok thanks for the fast reply and a free link, I'm sure it will help a lot.

The issue I'm having however doesn't have anything to do with my config (since I did place the hugo.exe in a PATH) because everything works just fine IF I place -s at the end of my commands.

Otherwise, whenever Hugo watches the folder, it doesn't output the site in the same folder, but rather in the directory of the binary file (which, in my case, is C:\Hugo).

As a result, I get the error "config not found.." . Not a biggie though, I just have to add the .-s flag at the end (something like hugo server -ws . ) and everything works normally.

**Comment by ivanjuras** [comment]
This is the error that I'm getting (pay attention to the directory that I'm currently in):


Ivan@IVAN-LAPTOP ~/Desktop/test2
$ hugo
ERROR: 2015/01/29 Config not found... using only defaults, stuff may not work
ERROR: 2015/01/29 Unable to find Static Directory:  in C:\hugo\static/
CRITICAL: 2015/01/29 No source directory found, expecting to find it at C:\hugo\content

Ivan@IVAN-LAPTOP ~/Desktop/test2
$

**Comment by anthonyfok** [comment]
Hi @ivanjuras,

Are you running `hugo` as `hugo`?  Or did you type out the full path, as in `C:\Hugo\hugo.exe`?  The actual reason that it is so important to put `hugo.exe` in a `PATH` is that there is a bug in Hugo v0.12 and older versions where if you run `hugo` like this: `C:\Hugo\hugo.exe`, Hugo would somehow think that your website source files reside in `C:\Hugo\`, and tries to look for the `config.toml` there, etc.

Type `where hugo` (inside Windows CMD.exe) or `which hugo` (inside a bash shell, if that is what you meant by Git terminal).  If neither command shows you where `hugo.exe` resides, then **your `hugo.exe` is not on your `PATH`**.  The `PATH` is not just a *path*; `PATH` is a special environment variable that tells Windows where to find your executable programs.

Please view the excellent troubleshooting video at http://gohugo.io/troubleshooting/overview/ where In that video, Dan Hersam explains this problem in details, and shows you how to solve it.  In particular, in your case, you will need to manually add `C:\Hugo` to your PATH, e.g. by running

    set PATH=%PATH%;C:\Hugo

inside the Windows Command Shell (`cmd.exe`), and then `where hugo` should show you the full path.

Or, if you are running from within Git BASH (https://msysgit.github.io/), you are in the bash shell, where you would use `export PATH=$PATH:the_path_to_your_hugo` (sorry, I don't know how msys references Windows paths inside bash...)

http://stackoverflow.com/questions/9546324/adding-directory-to-path-environment-variable-in-windows

(The issue has been fixed in November 2014 for the upcoming v0.13 release.)

**Comment by ivanjuras** [comment]
Ivan@IVAN-LAPTOP ~/Desktop
$ where hugo
c:\hugo\hugo.exe

**Comment by anthonyfok** [comment]
Hi @ivanjuras,

Thanks for posting the exact errors you are seeing:

> ```
Ivan@IVAN-LAPTOP ~/Desktop/test2
$ hugo
ERROR: 2015/01/29 Config not found... using only defaults, stuff may not work
ERROR: 2015/01/29 Unable to find Static Directory: in C:\hugo\static/
CRITICAL: 2015/01/29 No source directory found, expecting to find it at C:\hugo\content
```

My guess is that this special bash shell you are running converts the `hugo` you entered into a full path, i.e. `C:\hugo\hugo.exe`, before passing it onto Windows CMD to run it.  That... hmm... I don't know the solution, unfortunately, except by upgrading to v0.13-DEV, or...

I don't know if it would work, but try this: Copy `hugo.exe` into your ~/Desktop/test2, and run it as `./hugo.exe` and see if it works or not.

For my curiosity sake, which "Git Terminal" are you using?

Perhaps the best solution at the moment is to open a Windows CMD Shell instead and run `hugo` from there.  Maybe that's why Dan Hersam in his video uses the Git BASH terminal only for `git` commands, whereas he runs `hugo` solely from the Windows CMD shell.

**Comment by anthonyfok** [comment]
For reference: The underlying bug was reported in Issue #604 and fixed in Pull Request #663 by @tatsushid.

**Comment by ivanjuras** [comment]
Hey, thanks, can you just tell me where do I pull that branch? Since i only have a binary file on my system.

**Comment by ivanjuras** [comment]
By the way, im using Bash for Windows that comes with git

**Comment by anthonyfok** [comment]
> Hey, thanks, can you just tell me where do I pull that branch? Since i only have a binary file on my system.

Please follow the instruction at http://gohugo.io/overview/installing/ .  In particular, you will need to have the latest [Go](http://golang.org/doc/install) and [Mercurial](http://mercurial.selenic.com/) installed too.  ([Bazaar](http://bazaar.canonical.com/) seems to be no longer needed, but you may install it too if you like.)

The latest source code is in the `master` branch, so the `go get -v github.com/spf13/hugo` command as documented will fetch you the latest v0.13-DEV code.

Enjoy!

**Comment by jaden** [comment]
@anthonyfok You're correct. For the course I was running 0.12 and I ran into this issue. I also just checked and v0.13-DEV is working as expected. In short, @ivanjuras should be able to run Hugo inside the git bash shell with the latest dev version.

**Comment by bep** [comment]
More questions? http://discuss.gohugo.io/
