### ISSUE TITLE
Possibility to offer nightly build and docs in development (master) branch?

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#855]
:wink:

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by XhmikosR** [comment]
@bep: please reconsider this :)  I for example would like to try some features before they hit stable especially the merge configs option. For Windows you can easily just upload the artifact on AppVeyor.
