### ISSUE TITLE
Hugo v0.12 new content builder does not insert date into frontmatter

### ISSUE THREAD

**Issue by sebastianmarkow** [spf13/hugo#865]
I've set `MetaDataFormat` to `YAML` in my config and created an archetype for my post section.
Upon creating a new entry of this very archetype with `hugo new archetype/title.md` the frontmatter looks like:
~~~
---
date: {}
...
---
~~~

**Comment by anthonyfok** [comment]
Hi @sebastianmarkow,

Thank you for your bug report.

After some trials, I was able to reproduce the bug your saw with this combination:

 * Hugo v0.12
 * `MetaDataFormat = "YAML"` (uppercase) in my `config.toml`

It turns out that Hugo expects the value to be in lowercase, as documented on http://gohugo.io/content/archetypes/:

> You can specify a different default format in your site-wide config file (e.g. `config.toml`) using the `MetaDataFormat` directive. Possible values are `"toml"`, `"yaml"` and `"json"`.

With Hugo v0.13-DEV, the situation is better: `MetaDataFormat = "YAML"` gives `2015-02-08T09:09:38.018609794-07:00` rather than `{}`.  However, the nanosecond isn't supposed to be there either.

Examining the source code, there seems to be an inconsistency indeed: a parser.FormatSanitize() function exists to change the format name to lowercase, and it is used in several places, but not for the date.  Time for a bug fix!  :-)

Thanks again @sebastianmarkow for your report!

Cheers,
Anthony

P.S.  I suppose you meant to say `hugo new post/title.md`, otherwise your new post would end up in `content/archetype/title.md` (i.e. in a section named "archetype") rather than `content/post/title.md`.
