### ISSUE TITLE
Escaped # not rendered in headings when it's last character

### ISSUE THREAD

**Issue by hagbarddenstore** [spf13/hugo#879]
Example Markdown:

    # Broken heading \#

This produces the following HTML:

    <h1>Broken heading</h1>

But if I add something after the escaped # it will be rendered.

    # Working heading \# with escaped signs...

And this renders the following HTML:

    <h1>Working heading # with escaped signs...</h1>

Escaping the # sign works everywhere else, but not as the last character.

The bug can be avoided by simply appending a space as the last character, but that's kind of icky.

**Comment by anthonyfok** [comment]
Hello @hagbarddenstore,

Thank you for your attention to details!  This issue relates to https://github.com/russross/blackfriday, the excellent Markdown renderer written in Go.  You may quickly test this by building https://github.com/russross/blackfriday-tool (`go get -v github.com/russross/blackfriday-tool`) and test your Markdown input with it.

So, it would be best if you could take the time to [open a new issue at russross/blackfriday](https://github.com/russross/blackfriday/issues/new) instead, copying what you have written above there; and after that, post a link to that issue here so we (the Hugo project) can keep track of it too.

Thanks for your help!

**Comment by anthonyfok** [comment]
For a wider perspective, it appears that various Markdown engines exhibit different behaviors in your test case:

### John Gruber's original Markdown.pl and GitHub Flavored Markdown (GFM)

`# Broken heading \#` gives `<h1>Broken heading \</h1>`, hence

> # Broken heading \#

### Kramdown

`# Broken heading \#` gives `<h1 id="broken-heading-">Broken heading #</h1>`, i.e.

> <h1 id="broken-heading-">Broken heading #</h1>

which matches your desired output.

----

I haven't tested the other Markdown engines yet.  It seems that out of the three, only Kramdown got it right?

Note that http://daringfireball.net/projects/markdown/syntax#backslash does mention that the backslash may be used to escape the `#` hash mark character.

**Comment by anthonyfok** [comment]
I have taken the liberty to forward this issue upstream to Blackfriday.  Please see https://github.com/russross/blackfriday/issues/146 for continued discussions.

**Comment by bep** [comment]
@hagbarddenstore this should now be fixed in  Blackfriday. Are you able to confirm?

**Comment by bep** [comment]
Never mind, I justed tested it. Works fine now.
