### ISSUE TITLE
Quick start guide does not lead to working state

### ISSUE THREAD

**Issue by anentropic** [spf13/hugo#886]
I followed the [quick start guide](http://gohugo.io/overview/quickstart/) making a new site, a new page, installed the themes, started the server `hugo server --theme=hyde --buildDrafts` as instructed.

The page is blank when I view in browser

If I look in the `/public` folder I can see an `index.xml` file which is titled "recent content" and contains a summary of my new page. But the `index.html` files are all completely empty.

I am guessing the problem is maybe theme/layout related, although the problem persists if I run the server with `hugo server --buildDrafts`

How do I make it work?

**Comment by anentropic** [comment]
`Hugo Static Site Generator v0.13-DEV buildDate: 2015-01-16T08:30:39Z`

installed via Homebrew

**Comment by anentropic** [comment]
```
$ hugo check
pages/main.md (renderer: markdown) (layout: pages/single.html, exists: false) (layout: _default/single.html, exists: false) (layout: theme/pages/single.html, exists: false) (layout: theme/_default/single.html, exists: false)
 canonical => !no target specified!
```

might be this, but the docs don't really say what to do

**Comment by anentropic** [comment]
ah! I was supposed to clone the themes repo _inside my project directory_

it says that on the [installing themes](http://gohugo.io/themes/installing/) doc but not explicitly in the quickstart

**Comment by dcorb** [comment]
This is not a documentation issue only.  This is a major DX issue for beginners.

I was stuck in this problem, because I was re-structuring hugo folders, and forgot the "themes" folder.

Hugo should complain "Hey, the theme doesn't exist", or if you don't have still the site configured (through hugo -t), AND you forgot to use the --theme parameter, then Hugo should output an error "A theme is required".

**Comment by spf13** [comment]
A theme isn't required. Layouts or a theme are.
