### ISSUE TITLE
Render rss via ace/amber template

### ISSUE THREAD

**Issue by sebastianmarkow** [spf13/hugo#926]
Is there a way to render rss via one of the other template engines?

**Comment by bep** [comment]
Not sure. Have you tested it?

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by JayAndCatchFire** [comment]
I've been trying to do this and it doesn't seem to work.  If I put Ace markup in the `rss.xml` file, it doesn't get rendered properly.  If I make an `rss.ace` file, that doesn't get recognized properly by Hugo.  I've also tried `rss.ace.xml` and `rss.xml.ace` with no joy.

**Comment by JayAndCatchFire** [comment]
I found these lines in the code that seem somewhat relevant:
https://github.com/gohugoio/hugo/blob/9bd4236e1b3bee332439eef50e12d4481340c3eb/tpl/tplimpl/template.go#L655
https://github.com/gohugoio/hugo/blob/9bd4236e1b3bee332439eef50e12d4481340c3eb/tpl/tplimpl/template.go#L625

It looks like this was a deliberate choice.  Perhaps this could be a feature request to extend this to Ace and Amber?
