### ISSUE TITLE
Bad HTML in layouts/index.html causes Hugo v0.13 to log error while rendering

### ISSUE THREAD

**Issue by quoha** [spf13/hugo#941]
I created a new site and added four files in `content/post/` to look into a question from the forum. The only item in the layout was `layouts/index.html` containing:
```
<ulclass="params"></ul>
```
Running Hugo causes an error and no output is generated:
```
$ hugo
ERROR: 2015/03/02 Error while rendering homepage: html/template:index.html: expected space, attr name, or end of tag, but got "=\"params\"></ul>\n"
```
Updating the file to put the expected space after the UL tag resolves the issue:
```
$ cat layouts/index.html 
<ul class="params"></ul>

$ hugo
0 of 4 drafts rendered
0 future content 
0 pages created 
0 paginator pages created 
0 categories created
0 tags created
in 10 ms
```
It seems odd that Hugo worries about the format of my HTML.

**Comment by bep** [comment]
Go's `html/template` package worries about this. That's why we have thte `safeHtml`template func.

If we want to send the content through Rob Pike's template parser, I think we got to live with this.

Me, I prefer correct HTML.

Dependening on the consequence of this fault (does it stop rendering?), this may be toned down to a WARN.

**Comment by quoha** [comment]
I agree that correct HTML is the goal. It seems harsh to halt the server because of a typo in a layout file.

If this was demoted to a WARN, would I see the warning on every HTML that was rendered using that layout?

**Comment by bep** [comment]
I think it's best kept as is.
