### ISSUE TITLE
Expose a '.Section' parameter in a section template page.

### ISSUE THREAD

**Issue by H4tch** [spf13/hugo#954]
I'm using this parameter to query into section data within '.Site.Data.section'. I may work around this by using  '.Title', but this value is automatically pluralized. (Why is the blog section's title 'Blogs' and how can I change that?)

**Comment by H4tch** [comment]
Also, it'd be nice if the homepage belonged to the section "homepage". Using the above work around would force me to rename the site's title to "homepage" or "home".

**Comment by bep** [comment]
I'm not sure what you ask for.

There is a Section on Page (and Type) that can be used in queries.

There isn't a Section on Node (taxonomies, home page), but what would be the use case for that? And what be the values? As section is define as "the first folder below content" (my definition), how do that apply to these?

**Comment by H4tch** [comment]
The page that renders summaries of content from the section. The 'section.html' template. It _should_ have a '.Section' attribute describing the section it belongs to. Instead I have to fallback on '.Title'. But for some reason the 'blog' section title is 'Blogs'. Anyways, it seems like a reasonable assumption that the section template rendering section content has a '.Section' parameter. I'm using it to access .Site.Data.section.<section_name> to have customizable templated components on a per-section basis.

**Comment by bep** [comment]
Sure, but these "list pages" can be a mix of data from many sections, which section do they belong to? And I'm not sure what the use case is. There is a use case for knowing if it's the home page (often solved by checking Url == '/'), but other than that?

**Comment by H4tch** [comment]
I have a large collection of modular templated components that need to access data set by the 'section'
currently being rendered. I use 'section' to loosely refer to the Section, Taxonomy, or Homepage. I need the unmanged name of this 'section'. ".Title" is being pluralized automatically for these node pages. So for my 'author' section which is also a taxonomy(section render takes precedent), i have taxonomies.author = "author" to avoid issues I was having in Hugo 0.12 where I couldn;t get the singular form. When the site.com/author 'list' page renders, the '.Title' parameter is equal to "Authors". This is the same for blog, project, stream, etc. It's this type of stuff that causes distrust with the platform, and headaches due to inconsistencies when developing.(This inconsistency pales in comparison to others(How do you get a list of category terms by count from *any type of page* so the categories can be shown in a sidebar?(Hugo implementation of encapsulation is leaky due to the difference between Go data structures and map structures)). Still, its all forgivable since Hugo is relatively unexplored territory.)

Really, Taxonomies should be Sections that also happen to aggregate posts site-wide. Then taxonomy terms can have content pages with custom data fields defined.

tlrd; It's a matter of inconsistency. I don't want Hugo to mangle my data, it should just be a passthrough layer without doing too much automagically. Anyways, it's amazing what can be built on-top of Hugo right now, without ever having to touch Hugo's source, but could be a little bit better. Mainly the arbitary limitations imposed on Shortcode/Template inter-operability, and non-relative Partial template paths.

**Comment by H4tch** [comment]
I've found "pluralizeListTitles' which fixes the .Title issue and will allow me to work around the main issue I'm having.

**Comment by peczony** [comment]
A ~~better~~ more liberating workaround is of course to modify `partials/header.html` to use `.Title` only in pages, not in nodes—and define custom titles checking which node you’re in via url, that way:

```
<title>
{{ if .IsPage }}{{ .Title }}
    {{else}}
      {{ if eq .Url "/blog/" }}My super awesome blog{{end}}
      {{ if eq .Url "/projects/" }}My ming-bogging projects{{end}}
      {{ if eq .Url "/" }}My awesome website{{end}}
    {{ end }}
</title>
```

Which is of course infuriatingly horrible hardcode, but there it is, the best way possible at the moment (AFAIK).

**Comment by ifraixedes** [comment]
I had the same problem.
I have several parameters in `config` file, which I use to parametrise the sections pages using a common layout, actually that layout is `layouts/_defauls/list.html`, under a dictionary which each key is the "section".

When I used `.Title` without `pluralizeListTitles = false`, it didn't work and I realised that was due the pluralisation and I changed the keys to match them as a workaround.

Afterwards I found this issue and I discovered `pluralizeListTitles` so I could rename back the keys to the sections' name. However I do still need to transform lowercase the `.Title` to have more consistent keys and be able to match all of them easily.

Before discover this issue, I was thinking to report the same, "Why a Node doesn't have a `Section`, `Identifier` or whatever property with the exact string used for the folder's name (section)?"

I think that having it doesn't hurt, because if you use `pluralizeListTitles = true`, you can still identify the Node with a deterministic identifier, besides not to have to transform lover or upper case the `.Title`.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
