### ISSUE TITLE
RFE: --buildFuture should optionally accept a date parameter to allow automatic publishing and withdrawal

### ISSUE THREAD

**Issue by rickb777** [spf13/hugo#967]
The --buildFuture option is a boolean. If present, all future posts controlled by "_publishdate_" front-matter are generated.

If --buildFuture were able to specify a date argument, this could define the effective date in the future at which the filtered by "_publishdate_" articles are selected.

This would complement the (missing) "_withdrawdate_" front-matter item that would also allow articles to be withdrawn automatically at set times.

**Comment by rickb777** [comment]
--buildFuture with a date could, in principle, also work retrospectively, producing an image of the site as it had appeared on a certain date in the past.

This would be particularly useful if the "*withdrawdate*" front-matter item gets implemented.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
