### ISSUE TITLE
Relative url in theme: support both root domain and subfolder

### ISSUE THREAD

**Issue by TiTi** [spf13/hugo#985]
Hello,

I've been trying to have only relative urls in my theme ([hurock](https://github.com/TiTi/hurock)) and I manage to did it, but it currently won't work 100% for both types of urls:
- https://titi.github.io/
- https://titi.github.io/myblog/

The idea is of course is to have a theme which work immediately in both cases, and to avoid repetition of the full url. The only 2 places I'm using `{{ .Site.BaseUrl }}` are:
- in the `<base href="" />` element
- in the Home link

My initial problem is that urls generated by `{{ .TableOfContents }}` do not work when using `<base />` element. which i need to easily work for both urls types.

Here are my findings:

---
# baseurl = "https://titi.github.io/"

=> Browser URL (of an article): http://localhost:1313/posts/phabricator/
## With `<base href="{{ .Site.BaseUrl }}" />` :

TableOfContents link: http://localhost:1313/#install-arcanist
=> NOK
(but css and js ok)
## Without `<base />` element:

TableOfContents link: http://localhost:1313/posts/phabricator/#install-arcanist

=> OK but cannot include ressources with a relative path (CSS, JS, ...)

---
# baseurl = "https://titi.github.io/myblog/"

=> Browser URL: http://localhost:1313/myblog/posts/phabricator/
## With `<base href="{{ .Site.BaseUrl }}/" />` :

Note: The extra / in href with subfolder seem to have been fixed in #931

TableOfContents link: http://localhost:1313/myblog/#install-arcanist

=> NOK
(but css and js ok)
## Without `<base />` element:

TableOfContents link: http://localhost:1313/myblog/posts/phabricator/#install-arcanist

=> OK but cannot include ressources with a relative path (CSS, JS, ...)

---

Therefore, `{{ .TableOfContents }}` doesn't work with the `<base />` element.
In the end, I'm screwed if I wan't to have only relatives url with my theme and support both types of urls:
- https://titi.github.io/myblog/
- https://titi.github.io/

It's really too bad. This is why I currently disabled the TableOfContents on my blog.

This issue is probably limited to the `{{ .TableOfContents }}` variable, but it is somewhat tricky to managed relative url with Hugo.

---

For instance, in my sidebar, I've manually added some links to my sections (didn't managed to use `{{.Site.Sections}}` which seems broken) :

```
<a class="sidebar-link" href="posts/">Posts/</a>
<a class="sidebar-link" href="links/">Links/</a>
```

This works fine with both type of urls when using `<base href="<absolute>/" />`.
Whether I'm browsing the home page or an article (subfolder).

However, when the site is at the root level, I got thoses urls:

```
http://localhost:1313//posts/
```

Notice the extra slash?
It works: links are clickable. But it's kinda ugly :-/

I could add an extra slash in my links to fix that:

```
<a class="sidebar-link" href="/posts/">Posts/</a>
<a class="sidebar-link" href="/links/">Links/</a>
```

But then it would broke websites not on root level ; ex: http://localhost:1313/myblog/
Urls would target http://localhost:1313/posts/, which is outside `myblog/`

And it's the same thing whether `baseUrl` ends with a slash or not in `config.toml`...

This is too bad because my theme doesn't work 100% with both urls types.
One fast fix would be to use absolute url for thoses links, but that's kinda not satisfying.

---

Could this by detected by Hugo? I mean the `<base/>` element.
Or somewhat managed in the `config.toml` (either absolute or relative urls always).

One possible solution is to have a dedicated variable to get the relative path to root level, example: `{{ .RelativeUrl }}`

Or maybe something like "~/" like in ASP.Net?

**Comment by bep** [comment]
This was a little too long to take in one go. Maybe related to #811

**Comment by TiTi** [comment]
Update:
It's a little better with hugo v0.14: I do not have an extra slash when using `{{ .Site.BaseURL }}`.

But I'm still having an issue with `{{ .TableOfContents }}` : it doesn't work when using `<base href="{{ .Site.BaseUrl }}/" />` in my `<head>`.

**Comment by bep** [comment]
@TiTi there is another issue about base href and ToC floating around.

**Comment by kastork** [comment]
This suggestion in the op,

> One possible solution is to have a dedicated variable to get the relative path to root level, example: {{ .RelativeUrl }}

Would be helpful in certain situations.  Consider the case of just wanting to distribute your site as a folder archive where the user will simply open index.html as a file on local disc.

RelativeURLs and uglyURLs get you nearly there -- but most themes ask for static assets like css and js with some reference to the base url.   So anything not at the root level gets a bad path to the assets.  If the baseurl value were sensitive to the value of relativeURLs and provided a relative path to the root path, I think it would solve this problem.

**Comment by bep** [comment]
@kastork have look at the ´relURL` and `absURL´ funcs.

**Comment by kastork** [comment]
Thanks for the tip.

I think this would require customizing any theme you want to use this way.  Am I wrong?

**Comment by bep** [comment]
>I think this would require customizing any theme you want to use this way. Am I wrong?

Sure, but that would be the case with your suggestion, too.

If all the URLs in the templates are "correct", then the RelativeURLs setting will get you there.

**Comment by kastork** [comment]
Ok, I'll have to play more with it since I'm obviously missing something.

So far, my experience is that themes who look for css by making some reference to BaseURL get a relative URL, but it is a child path of the directory the page is in, rather than relative to the root directory of the site.

**Comment by bep** [comment]
>but it is a child path of the directory the page is in, 

That is correct, but this is where the magic of `RelativeURLs` config setting comes in.

**Comment by kastork** [comment]
I followed the getting started section of the Hugo site to produce this project.

https://github.com/kastork/relurl-example

It is modified from the tutorial in the following sense:

1. The config is a yaml file
2. relativeURLs and uglyURLs are set
3. the baseurl is set to ""
4. the hugo_robust_theme has been copied in.
5. The site has been built and the result is stored in `public`, which has been committed.

Now, when you open the file `public/index.html` (from the file system, no server) you see the page as expected.  The theme css, js and images load.  (The schema-less items mentioned in the header partial and are normally retrieved from CDNs do not load.  This is expected and would obviously require customization of the theme to vendor and properly wire those assets in the project).

But the point here is to see what happens with the artifacts that _are_ vendored.  They are in paths like `css`.  As long as the page being rendered is at the root of `public`, all is well.

But when you click through to a post (the good to great example), the page fails to load the css and js and images from the theme.  This is because the relative URL that's being generated doesn't point  to something in  `public` (the site's baseURL), but to something in `public/post` that doesn't exist.

So the use-case being suggested is (when relativeURLs is active) to have `{{ .Site.BaseURL }}` produce the root path of the directory which contains the 'site' on the file system expressed in a way that a `file://` url would resolve properly.  In this case:

In the case of a first level child of the root path, like something in `post` I guess this would manifest itself something like:

`../`

This behavior seems to me like what most people would expect to happen when they activate relativeURLs.  Maybe I'm wrong, or maybe there's a reason to avoid that behavior, or maybe there's some way get `.Site.BaseURL` to work that way which I haven't discovered.

**Comment by bep** [comment]
This is getting long for me; I suggest taking this discussion at the forum where it belongs.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by TiTi** [comment]
Hi,
The issue is still there with Hugo 0.19.
Lets try to explain it better this time.
If needed I can open a new issue.

## Issues

Basically I have 2 linked issues:
* Relative ressource linking (ex: `<link rel="stylesheet" href="css/custom.css"/>`) doesn't work without using `<base href="{{ .Site.BaseURL }}" />`
* `.TableOfContents` doesn't work when using `<base href="{{ .Site.BaseURL }}" />`

## Explanation

I'd like my HTML to be small.
Indeed, it's kinda stupid to have a full absolute path like that for every link / ressource:
```
  <link rel="stylesheet" href="http://mysuperlongdomain.com/myblog/css/fonts.css"/>
  <link rel="stylesheet" href="http://mysuperlongdomain.com/myblog/css/normalize.css"/>
  <link rel="stylesheet" href="http://mysuperlongdomain.com/myblog/css/skeleton.css"/>
  <link rel="stylesheet" href="http://mysuperlongdomain.com/myblog/css/custom.css"/>
  ...
```
Therefore I like all internal links to be relative:
```
  <link rel="stylesheet" href="myblog/css/fonts.css"/>
  <link rel="stylesheet" href="myblog/css/normalize.css"/>
  <link rel="stylesheet" href="myblog/css/skeleton.css"/>
  <link rel="stylesheet" href="myblog/css/custom.css"/>
  ...
```
Sounds legit right?
Full path works but ain't sexy and efficient (network wise)
[Also wondering for SEO stuff in case you want to change to domain...]


When doing that with my theme:
* Everything is fine on home page
* No css loaded when i go to a post like http://localhost:1313/2014/10/scalability/ or a list like http://localhost:1313/posts/ or anywhere but home...
Therefore it looks ugly ; lots of 404 in network tab
Indeed it tries to load http://local host:1313/**posts**/css/custom.css which doesn't exists
* `{{ .TableOfContents }}` works has expected
when on post http://localhost:1313/myblog/2014/10/scalability/
section is `<a href="#netflix">Netflix</a>`
hovering result in correct link: http://localhost:1313/myblog/2014/10/scalability/#netflix

## Workaround and other issue

So my fix was to use `<base href="{{ .Site.BaseURL }}" />` in the `<head>`. And it works fine.
But.... it breaks `{{ .TableOfContents }}` 😞 

Indeed HTML section links generated by .TableOfContents continue to be of the form `<a href="#netflix">Netflix</a>`, but hovering targets http://localhost:1313/#netflix ... because of the `<base href="{{ .Site.BaseURL }}" />`

So i had to disable TableOfContents with my theme:
`{{ if and (not .Site.Params.notoc) .TableOfContents }}`


-----

Next is good news:

## Extra slash

I my original issue, I've describe having to specify an extra slash in the base href: `<base href="{{ .Site.BaseUrl }}/" />` to having breaking sites not on root level ; ex: http://localhost:1313/myblog/

Leaking to an extra slash in some home page links:

    http://localhost:1313//posts/

That is no more the case, everything is handled well.
I've tried all combinaisons with/without `<base href` and with either:
* baseurl = "https://titi.github.io"
* baseurl = "https://titi.github.io/"
* baseurl = "https://titi.github.io/myblog"
* baseurl = "https://titi.github.io/myblog/"

## Suggestion

-> re-read the last section in my initial message please

**Comment by rdwatters** [comment]
@TiTi ould you mind please posting this on the forums first to see if the community can help you? https://discuss.gohugo.io

You are unlikely to get the help and attention you need by posting on closed issues. 😄
